### ISSUE TITLE
Integration with different version of react native 

### ISSUE THREAD

**Issue by AmirDoreh** [twilio/twilio-voice-react-native#101]
we have integrated sdk with our application , working smooth on IOS we faced no issue . but when we are trying to build the app or run it on Device/Emulator , we got following issues:

`java.lang.RuntimeException: Duplicate class com.facebook`

then by adding exclude to our build file we could fix it then faced :

`React Native app in Android studio: Cause Argument type mismatch`

by downgrading the gradle version the issue still exists.

Also we tried to build the example of the sdk and again it had issues and did not work.

**Comment by charliesantos** [comment]
Hey @AmirDoreh , thanks for reaching out. We have not seen this error before but doing some research, this seems related to gradle version issues, which I understand you already tried and still failed. Another possible reason why this is happening is, the app is trying to install but there's already another app with the same name. Can you please try clearing your emulator's data and start for fresh? Or if it's a real device, can you try uninstalling the app manually and see if that fixes it?

**Comment by mhuynh5757** [comment]
Thanks all, closing this issue as stale. Please feel free to reopen if the issue is still affecting you.
