### ISSUE TITLE
Not show any Accept/Reject buttons for notification banner on Android

### ISSUE THREAD

**Issue by cpham-rb** [twilio/twilio-voice-react-native#102]
**Description:**
Receive incoming call when app in background or killed
The notification banner shown but there no buttons to Accept or Reject the call

![screenshot-nimbusweb me-2022 09 13-21_11_45](https://user-images.githubusercontent.com/58545551/190303343-7fd697d0-e2f3-4771-9da6-95271e80497e.png)

**Env:**
- Build on real Android device
- Expo: 45
- twilio-voice-react-native: 1.0.0-preview.1

**Comment by charliesantos** [comment]
@cpham-rb thanks for reaching out. Which android device is this happening on, and what version? Also, is this happening on any android device or only specific to this device?

**Comment by cpham-rb** [comment]
> @cpham-rb thanks for reaching out. Which android device is this happening on, and what version? Also, is this happening on any android device or only specific to this device?

This happening on Samsung Galaxy S8

![screenshot-nimbusweb me-2022 09 16-08_06_39](https://user-images.githubusercontent.com/58545551/190534980-a0f6886d-51f0-43a5-a86f-0bb2200724de.png)
![screenshot-nimbusweb me-2022 09 16-08_07_27](https://user-images.githubusercontent.com/58545551/190534984-b9d278c5-2c0c-4291-b51a-d88b591b45fd.png)

**Comment by charliesantos** [comment]
Thanks @cpham-rb . Have you tested on a different device by any chance?

**Comment by cpham-rb** [comment]
@charliesantos when I set the `layout_height` of buttons wrapper: https://github.com/twilio/twilio-voice-react-native/blob/main/android/src/main/res/layout/custom_notification_incoming.xml#L30

The incoming notification banner shown, so I guess the issue with Android XML layout
I not sure this happen on other device.

![screenshot-nimbusweb me-2022 09 21-08_38_11](https://user-images.githubusercontent.com/58545551/191395284-2e5806d8-ceff-4f9a-bd46-f51bbc2407a9.png)

**Comment by kbagchiGWC** [comment]
@cpham-rb 

Thanks for opening the issue and root causing it. 

The example app with the SDK is tested on limited number of devices hence the notification layout may not be optimal for all devices/API levels. Please refer to the Android Documentation on custom notification layout in [here](https://developer.android.com/develop/ui/views/notifications/custom-notification) if you need further details.

Thanks again for bringing this to our attention.

**Comment by liemdo** [comment]
@kbagchiGWC Does it mean the developers are responsible to come up with our own layout? I expect the client works out of the box.

**Comment by hawkinbj** [comment]
Hello @liemdo. This is a Pilot / Preview Release - the SDK is provided as-is and there is little to no "out of the box" functionality available outside of the basic API at this time. We will be adding these sorts of features/support in subsequent release phases. Please see the README for more information

**Comment by periabyte** [comment]
Is there a guide we can follow specifically for react native?

**Comment by mhuynh5757** [comment]
Hi @periabyte, thanks for reaching out. At the moment, the closest thing we have to a guide is our Reference App, which is an example production ready dialer that uses React Native and our library: https://github.com/twilio/twilio-voice-react-native-app

For the future, please submit new issues when they are sufficiently different requests than the original, it really helps us keep track of issues.

For now, I will also close this issue as stale, please reach out and feel free to reopen if the original problem reoccurs.

**Comment by liemdo** [comment]
With the latest version 1.0, the Answer & Decline buttons are still cut off on some old phones such as the Samsung S8 as mentioned in the first comment.
