### ISSUE TITLE
Are you accepting contributions?

### ISSUE THREAD

**Issue by se1exin** [twilio/twilio-voice-react-native#106]
Hi there,

First, thanks for working on this in the open! I know it's still in preview but I have recently replaced the custom Twilio implementation in my RN app with this, and have it live in both the App and Play stores with several hundred active users making calls day-to-day. So far everything is running well!!

I have a few features I want to add and just wanted to see how open you are to taking PRs for them before I spend the time do the extra steps needed (e.g. updating the Example app, writing tests where possible).

The features I have been working on locally are:
- Customise ringtone (re-creates the notification channel on Android, re-inits CallKeep on iOS)
- Customise Android notification buttons (ie colours to match the app branding)

I also have a tweak to the Java version in the base Android gradle file for it to compile for newer versions of RN (use `Java.VERSION_1_8` instead of `11`), but not sure if that is appropriate to include in a PR..?

**Comment by punjasin** [comment]
i am not able to build this on my current react native project 0.65 how do you able to compile it  it alway return package Build does not exist
  @RequiresApi(api = Build.VERSION_CODES.N)
 for me

**Comment by kbagchiGWC** [comment]
@se1exin 

Thanks for using the [twilio-voice-react-native](https://github.com/twilio/twilio-voice-react-native) and your feedback. 
We are proponent of community contribution. If your contributions align with the product guidelines, we will follow internal process for validation before accepting it.

**Comment by se1exin** [comment]
@kbagchiGWC thanks for confirming, I'll roll together a PR soon and see where it goes from there!

@punjasin A temporary fix to get it build is to change `JavaVersion.VERSION_11` to `JavaVersion.VERSION_1_8` in the root `build.gradle` of the library (https://github.com/twilio/twilio-voice-react-native/blob/main/android/build.gradle#L4) in your `node_modules` folder. Note this is only a temporary fix as `npm`/`yarn` may overwrite the changes if you install/remove any other packages
