### ISSUE TITLE
The method await voice.connect(token, params) doesn't do anything. 

### ISSUE THREAD

**Issue by isaacVzz** [twilio/twilio-voice-react-native#109]
Hi, could you help me?
I'm trying to develop a test react native app to make VoIP calls but I'm having issues. I'm using the npm module  @twilio/voice-react-native-sdk
The problem is when I try to use the method **await voice.connect(token, params)**, this method doesn't do anything, I don't get any error or any response, and I'm stuck in this issue. Could someone help us? 
I attach part of code that i'm using to make an outgoing call.

This is my code on React Native where I'm trying to make anoutgoingcall.
![Captura de Pantalla 2022-11-15 a la(s) 18 52 15](https://user-images.githubusercontent.com/52250577/202520061-ae6afcb4-5f71-479e-a1cb-0a2dac07b33b.png)

Server Side to get my Access Token and Make a Call.
![Captura de Pantalla 2022-11-15 a la(s) 18 52 55](https://user-images.githubusercontent.com/52250577/202520269-7921ce73-e69e-4d1f-bd38-e20cd223a172.png)

![Captura de Pantalla 2022-11-15 a la(s) 18 53 06](https://user-images.githubusercontent.com/52250577/202520653-81cd0a56-5cea-4ceb-826c-0e14e6f5965f.png)

Twilio TwiML app 
![TwiML](https://user-images.githubusercontent.com/52250577/202521622-87870cd7-d31f-4c30-a2e7-c907ff4117b5.jpg)

I'm using Ngrok. as my local tunel*

**Comment by charliesantos** [comment]
Hi @isaacVzz , thanks for reaching out. I have a few questions and requests.
- In your callTest function, can you please add a debug log to make sure voice.connect() is getting called?
- I see you are logging the callResponse. Is this line getting called? What does the call object look like?
- Is this on android or ios?
- Can you provide debug logs both from your IDE (ios/android) and JS logs?

**Comment by isaacVzz** [comment]
Hi @charliesantos thank u so much for answer, I appreciate it 
**In your callTest function, can you please add a debug log to make sure voice.connect() is getting called?
I see you are logging the callResponse. Is this line getting called? What does the call object look like?**
I added a debugger in line 36 and my code works fine till this breakpoint. The 'flag 1' it's called without problem but after that my code doesn't do any.

![Captura de Pantalla 2022-11-18 a la(s) 17 18 51](https://user-images.githubusercontent.com/52250577/202825774-a20b75a9-13f3-46ab-8d6f-816cd67ef817.png)

I'm working on IOS and trying to run this app test on a device iPhone with IOS 15.3.1

This is my package.json
![Captura de Pantalla 2022-11-18 a la(s) 18 55 02](https://user-images.githubusercontent.com/52250577/202825891-ab46e6f0-f97f-4e73-b576-c4c554050615.png)

**Comment by charliesantos** [comment]
Thanks @isaacVzz . Can you please provide ios and js debug logs?

**Comment by usmanrwp** [comment]
{"_events":{},"_eventsCount":0,"_state":"connecting","_uuid":"e89968ed-c8b2-43c3-a783-65b2fd3834b9","_customParameters":{},"_from":null,"_sid":null,"_to":null,"_nativeEventHandler":{}}

**Comment by mhuynh5757** [comment]
Hello, thanks for reaching out. Can you confirm @usmanrwp that you are the original poster, I am having trouble keeping track of users. Or, are you a different user encountering the same issue? In any case, debug logs from the native platform (iOS or Android) are necessary to solve this issue.

**Comment by isaacVzz** [comment]
Hi @charliesantos this is my All Output log from Xcode. From JS only I get in my console the output of "flag 1". 
![Captura de Pantalla 2022-11-22 a la(s) 17 09 50](https://user-images.githubusercontent.com/52250577/203440834-fcf57495-1093-47ad-a9d9-60911e2b1ced.png)

And this is my Xcode out put when I press 'Call', this action make the request to voice.connect().
![Captura de Pantalla 2022-11-22 a la(s) 17 10 30](https://user-images.githubusercontent.com/52250577/203441054-25b99167-1634-4fb6-9f1c-862509be65c7.png)

**Comment by mhuynh5757** [comment]
Hi @isaacVzz, from what I can see, your device is having trouble making any network connections to the Twilio services. Can  you ensure it has network connectivity elsewhere? Also, is this a real device or a simulated device? The Twilio Voice SDK only works on real devices.

**Comment by isaacVzz** [comment]
Hi @mhuynh5757 thank u so much, in this case I had to enable in Background Modes the following options, now I have a call connection but still doesn't work.
![Captura de Pantalla 2022-11-22 a la(s) 18 31 28](https://user-images.githubusercontent.com/52250577/203448106-6df2ef9d-42eb-4f1f-a84a-b5c5479309e7.png)

I get the next issue on my IOS Xcode console. 
![Captura de Pantalla 2022-11-22 a la(s) 18 35 03](https://user-images.githubusercontent.com/52250577/203448236-429f9246-f344-4aef-931b-b6ade6a7b93b.png)

**Comment by mhuynh5757** [comment]
Hi @isaacVzz, please make sure the iOS parts of your React Native application is configured to work with the Twilio iOS Voice SDK. See these docs for more details: https://www.twilio.com/docs/voice/sdks/ios

**Comment by GuilhermeLessa** [comment]
@mhuynh5757 you said that voice only works to real devices? I'm able to  call out using a virtual android device, but not able to incomings,  it is the problem? using virtual device?
