### ISSUE TITLE
Change handle "Twilio Frontline"

### ISSUE THREAD

**Issue by liemdo** [twilio/twilio-voice-react-native#119]
When I receive a call, the call log is written with the name "Twilio Frontline." Is it possible to change this handle and disable the app from writing to the native call log?

**Comment by bobiechen-twilio** [comment]
Hi @liemdo 

You can simply change the handle strings in [this file](https://github.com/twilio/twilio-voice-react-native/blob/d5db7164039ee5fe6913fa327ab91c3ebad9d320/ios/TwilioVoiceReactNative%2BCallKit.m#L24) to whatever makes sense to your application.

**Comment by liemdo** [comment]
I can do that by this will require me to fork the project and publish our own version. It would be better if this SDK provides an option to pass in a custom handle and disable writing to the call log.

**Comment by bobiechen-twilio** [comment]
Thanks @liemdo. That makes sense.
I've created a ticket for tracking the progress.
