### ISSUE TITLE
Cannot receive incoming calls on Android 12

### ISSUE THREAD

**Issue by cpham-rb** [twilio/twilio-voice-react-native#123]
On Android 12, the app crashed when receiving incoming call with the error:

![Screenshot_2023-01-10-20-41-41-174_com ringblaze app](https://user-images.githubusercontent.com/58545551/211705295-e8d09b48-6375-432d-986f-c13e3e1c51be.jpg)
---
About the phone:
![Screenshot_2023-01-11-09-19-51-967_com android settings](https://user-images.githubusercontent.com/58545551/211705343-b6960366-9a23-46fd-981a-a65c7842dbaa.jpg)

**Comment by kbagchiGWC** [comment]
@cpham-rb 
Thanks for reporting the issue. We have an internal task to track this issue. We will keep you posted when the release is available with the fix.

**Comment by se1exin** [comment]
I'm hitting the same issue, and with Google Play no longer accepting app updates targeting API 30 I had to develop a fix for myself:

https://github.com/twilio/twilio-voice-react-native/compare/main...se1exin:twilio-voice-react-native:android-12?expand=1

It's a bit hacky, but it's working for me

**Comment by mhuynh5757** [comment]
Hi all, thanks for bringing this up to our attention. Please try out the new beta build of this SDK, it may have addressed this issue.

cc @cpham-rb @se1exin 

Please open another issue if you're still seeing this problem.
