### ISSUE TITLE
How can I make a call to a phone number? (Make Outbound Phone Calls)

### ISSUE THREAD

**Issue by thanhnvpk01168** [twilio/twilio-voice-react-native#129]
I only made 1 call to the phone number, not made a call to 1 app.
when i run the below code
const call = await voice.connect(mytoken, {
                            recipientType: 'phone',
                            To: "+84xxxxxxxxx"
});
My phone doesn't ring or show any incoming calls.

call logs
<img width="1316" alt="Screen Shot 2023-02-04 at 17 35 51" src="https://user-images.githubusercontent.com/58645779/216762321-ee69426b-6492-4576-96db-7a0ab50f2a49.png">

**Comment by charliesantos** [comment]
Hi @thanhnvpk01168 , I see you've submitted and closed this issue soon after. Can you please let us know how did you resolve it? It might be helpful for future contributors :)

**Comment by sshodges** [comment]
> I only made 1 call to the phone number, not made a call to 1 app. when i run the below code const call = await voice.connect(mytoken, { recipientType: 'phone', To: "+84xxxxxxxxx" }); My phone doesn't ring or show any incoming calls.
> 
> call logs <img alt="Screen Shot 2023-02-04 at 17 35 51" width="1316" src="https://user-images.githubusercontent.com/58645779/216762321-ee69426b-6492-4576-96db-7a0ab50f2a49.png">

How did you resolve this? having the same issue

**Comment by sshodges** [comment]
Turns out it doesn't connect from ios emulator. Ran off my own iPhone and it worked: 

1. plug in iphone to laptop
2. npx expo run:ios --device
3. select your phone from list
