### ISSUE TITLE
Error when importing library

### ISSUE THREAD

**Issue by dianamariand92** [twilio/twilio-voice-react-native#133]
Hi, 

I am getting these errors when I am trying to import the library (import { Voice } from '@twilio/voice-react-native-sdk';)

 ERROR  Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.

Thanks

**Comment by liemdo** [comment]
Have you tried to delete the `Podfile.lock` inside the `ios` folder and re-run `pod install`?

**Comment by dianamariand92** [comment]
@liemdo Yes, I removed the `Podfile.lock` and the Pods folder and the I run `pod install`. And I always get this error.

 ERROR  Invariant Violation: `new NativeEventEmitter()` requires a non-null argument.

**Comment by bobiechen-twilio** [comment]
Hi @dianamariand92 

Some of the `pod` development dependencies (for example the Twilio React Native SDK and the Twilio iOS wrapper) are referenced from the `node_modules` folder. To make sure these dependencies are ready, run `yarn install` or whichever way of `node` dependency management way you prefer under the same path of the application's  `package.json`, then run `pod install` again and it should be able to pull the dependencies.

**Comment by dianamariand92** [comment]
Hi @bobiechen-twilio,

Yes, I run `npm install` on the root folder, and all dependencies are installed. Then I run `pod install` on the ios folder. I tried it removing `node_modules` folder, Pods folder and `Podfile.lock` and I still get the same error. I have also installed this library [https://github.com/MrHertal/react-native-twilio-phone](url) Could it be a conflict between both libraries?

**Comment by bobiechen-twilio** [comment]
Hi @dianamariand92 did you also install dependencies in the app folder?

**Comment by liemdo** [comment]
@dianamariand92 There is no reason to install this library and also [https://github.com/MrHertal/react-native-twilio-phone](https://github.com/twilio/twilio-voice-react-native/issues/url). It can create conflicts.

**Comment by mhuynh5757** [comment]
Hi @dianamariand92, please use `yarn` and not `npm` in the root folder. `yarn` is recommended by the official RN docs and will recursively bootstrap the native dependencies where `npm` will not.

**Comment by dianamariand92** [comment]
Hi @liemdo @mhuynh5757  @bobiechen-twilio  I was able to resolve the problem.
