### ISSUE TITLE
Error adding TwilioVoicePushRegistry in AppDelegate.m when using Expo

### ISSUE THREAD

**Issue by maoryadin** [twilio/twilio-voice-react-native#134]
Hello,

I am using Expo and I created a plugin to add some necessary code to the AppDelegate.m file, but I'm getting an error when trying to initialize TwilioVoicePushRegistry at launch. The error message says:

`❌ (/Users/maoryadin/spetz-git/spetz-simulator-app/ios/Spetz/AppDelegate.mm:63:10)
  63 |     self.twilioVoicePushRegistry = [TwilioVoicePushRegistry new];
     |          ^ property 'twilioVoicePushRegistry' not found on object of type 'AppDelegate *'
`

I've checked my code, and I have the property twilioVoicePushRegistry declared in my AppDelegate interface. Here is the relevant code:

```
  #if RCT_NEW_ARCH_ENABLED
  @interface AppDelegate () <RCTCxxBridgeDelegate, RCTTurboModuleManagerDelegate> {
    RCTTurboModuleManager *_turboModuleManager;
    RCTSurfacePresenterBridgeAdapter *_bridgeAdapter;
    std::shared_ptr<const facebook::react::ReactNativeConfig> _reactNativeConfig;
    facebook::react::ContextContainer::Shared _contextContainer;
  }
  @property (nonatomic, strong) TwilioVoicePushRegistry *twilioVoicePushRegistry;
  @end 
  #endif
  
  @implementation AppDelegate
  
  - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
  {
    // ...
  
    // Initialize PKPushRegistry at launch
    self.twilioVoicePushRegistry = [TwilioVoicePushRegistry new];
    [self.twilioVoicePushRegistry updatePushRegistry];
  
    // ...
  }
```

I'm not sure why Xcode is giving me this error. Can anyone help me figure out what's going on here?

Thank you.

**Comment by dwbelliston** [comment]
Hey @maoryadin - would you mind sharing how you did an expo plugin? Any tips on where to start would be great!

**Comment by maoryadin** [comment]
> Hey @maoryadin - would you mind sharing how you did an expo plugin? Any tips on where to start would be great!

Yes, I was able to run the package with Expo, I will share the process when I get on my computer (probably on Sunday).
