### ISSUE TITLE
Add option to detect when device token is set before registering with Twilio Voice

### ISSUE THREAD

**Issue by maoryadin** [twilio/twilio-voice-react-native#136]
There may be cases where the access token is being set before the device token in Twilio Voice, causing an error during registration. To address this, I propose that Twilio add an option to detect when the device token has been successfully set, allowing the registration process to continue without error.

I suggest that Twilio consider adding an option to the Voice object that developers can use to detect when the device token has been set before registering with Twilio Voice. This will enable developers to avoid the current error, and provide a more streamlined and reliable registration process.

Thank you for your consideration.

**Comment by bobiechen-twilio** [comment]
PR at #125.

**Comment by maoryadin** [comment]
The pr is not fix this.
I am still getting this error:
![image](https://user-images.githubusercontent.com/31710467/220273789-bf0e1dc3-a209-4e24-82a2-6e6289240c47.png)
