### ISSUE TITLE
Problem | postNotificationName is called before the observer is created

### ISSUE THREAD

**Issue by maoryadin** [twilio/twilio-voice-react-native#137]
**I am testing with react native expo app. did expo pre-build because needed to add the native code as mention in the description to the AppDelegate file.**

Environment: IOS.

problem: postNotificationName is being called before the observer is created

So after digging and debugging extensively, i can say that there is a problem in the **subscribeToNotificaitons** in **TwilioVoiceReactNative.m** file.

This code:
```
- (void)subscribeToNotifications {
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(handlePushRegistryNotification:)
                                                 name:kTwilioVoicePushRegistryNotification
                                               object:nil];

    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(handleRouteChange:)
                                                 name:AVAudioSessionRouteChangeNotification
                                               object:nil];
}
```

And especially ->

```
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(handlePushRegistryNotification:)
                                                 name:kTwilioVoicePushRegistryNotification
                                               object:nil];
```

is responsible to observe changes in the initialize of the  DeviceToken in the TwilioVoicePushRegistry.m file:

```
- (void)pushRegistry:(PKPushRegistry *)registry
didUpdatePushCredentials:(PKPushCredentials *)credentials
             forType:(NSString *)type {
    if ([type isEqualToString:PKPushTypeVoIP]) {
        [[NSNotificationCenter defaultCenter] postNotificationName:kTwilioVoicePushRegistryNotification
                                                            object:nil
                                                          userInfo:@{kTwilioVoiceReactNativeVoiceEventType: kTwilioVoicePushRegistryNotificationDeviceTokenUpdated,
                                                                     kTwilioVoicePushRegistryNotificationDeviceTokenKey: credentials.token}];
    }
}
```

BUT this pushRegistry is happening before the init of the **subscribeToNotifications** making it impossible to set the deviceToken on the property:
`self.deviceTokenData = eventBody[kTwilioVoicePushRegistryNotificationDeviceTokenKey];`

### **Conclusion**:
**We should first AddObserver and then do PostNotificationName.**

**### How i fixed it?**

Added **#import "TwilioVoicePushRegistry.h"** to **TwilioVoiceReactNative.h**

Added **@property (nonatomic, strong) TwilioVoicePushRegistry *twilioVoicePushRegistry;**

Added the following code to the init of TwilioVoiceReactNative.m:

```
 (instancetype)init {
    if (self = [super init]) {
        _callMap = [NSMutableDictionary dictionary];
        _callInviteMap = [NSMutableDictionary dictionary];
        _cancelledCallInviteMap = [NSMutableDictionary dictionary];
        _audioDevices = [NSMutableDictionary dictionary];

        NSString *reactNativeSDK = kTwilioVoiceReactNativeReactNativeVoiceSDK;
        setenv("global-env-sdk", [reactNativeSDK UTF8String], 1);

        sTwilioAudioDevice = [TVODefaultAudioDevice audioDevice];
        TwilioVoiceSDK.audioDevice = sTwilioAudioDevice;

        TwilioVoiceSDK.logLevel = TVOLogLevelTrace;

        [self subscribeToNotifications];
        [self initializeCallKit];
        [self initializeAudioDeviceList];
        
        **// Initialize PKPushRegistry at launch
          self.twilioVoicePushRegistry = [TwilioVoicePushRegistry new];
          [self.twilioVoicePushRegistry updatePushRegistry];**
    }

    return self;
}
```

**Comment by bobiechen-twilio** [comment]
Hi @maoryadin 

Thanks for sharing the debugging information and although it somehow seems to have been working in my dev environment (PushKit always returns the device token asynchronously after the notification observer is set) but the sequence of PushKit initialization and notification observer could indeed potentially cause the invalid device token issue.

I was concerned that moving the PushKit `pushRegistry` instance into the `TwilioVoiceReactNative` class could cause issue that the app might not be able to initialize PushKit in time order to handle the push notification and report to CallKit. I did a few tests and it seems to work - the application is able to be launched and show incoming call when it was previously terminated.

I will post a PR for this update. Kudos again for debugging and sharing what you found.

-bobie

**Comment by maoryadin** [comment]
> Hi @maoryadin
> 
> Thanks for sharing the debugging information and although it somehow seems to have been working in my dev environment (PushKit always returns the device token asynchronously after the notification observer is set) but the sequence of PushKit initialization and notification observer could indeed potentially cause the invalid device token issue.
> 
> I was concerned that moving the PushKit `pushRegistry` instance into the `TwilioVoiceReactNative` class could cause issue that the app might not be able to initialize PushKit in time order to handle the push notification and report to CallKit. I did a few tests and it seems to work - the application is able to be launched and show incoming call when it was previously terminated.
> 
> I will post a PR for this update. Kudos again for debugging and sharing what you found.
> 
> -bobie

Bobbie, we could also create a Singleton object called PushKitManager that maintains the shared state of the PushKit registration. init it in AppDelegate, and then access it in the relevant files using 
`@property (nonatomic, strong) NSString *deviceToken; // Shared variable for the device token
`

would you like that i will create a PR for that?

**Comment by bobiechen-twilio** [comment]
PR created #143.
