### ISSUE TITLE
[iOS] callkit conflict with react native callkeep

### ISSUE THREAD

**Issue by thanhnvpk01168** [twilio/twilio-voice-react-native#141]
i am using react native callkeep to show incoming call when calling video call.

specifically when i start call from react native callkeep it calls to your callkit.

can you help me this issue?

**Comment by bobiechen-twilio** [comment]
Hi @thanhnvpk01168 

We would need more information to assist you integrating the SDK such as the error message when the module conflict is happening. Could you share the use case of your video call and the use case of the Voice React Native SDK?

The iOS CallKit integration is baked into the React Native SDK provided by the Twilio SDK team to guarantee smooth interaction with the system.

**Comment by kpchoy** [comment]
It seems like original issue is stale. Please create a new issue if you are experiencing problems.
