### ISSUE TITLE
Video calls are supported?

### ISSUE THREAD

**Issue by maoryadin** [twilio/twilio-voice-react-native#145]
In a situation where my users will need to enable video calls in the VoIP, I would like to know if the library supports video calls.

**Comment by bobiechen-twilio** [comment]
@maoryadin 
Video is not supported by this SDK. Please check out the [Twilio Video SDKs](https://www.twilio.com/docs/video) or [twilio-video-react-native](https://github.com/twilio/twilio-video-react-native) if you plan to add video capability to your application.
