### ISSUE TITLE
[Android]Don't receive incoming calls

### ISSUE THREAD

**Issue by mohsinali-823788** [twilio/twilio-voice-react-native#146]
Don't receive incoming calls on (Android) not even called listener or not receive any notification from twilio but can call to someone other phone number.

---------------------------------
-App.js-

import React, {useEffect, useState} from 'react';
import {View, Text, TouchableOpacity, Dimensions} from 'react-native';
// import TwilioVoice from 'react-native-twilio-programmable-voice';
import axios from 'axios';
import {Voice} from '@twilio/voice-react-native-sdk';
import messaging from '@react-native-firebase/messaging';

const voice = new Voice();
const App = () => {
  const [token1, setToken1] = useState('');
  const initTelephonyWithToken = async token => {
    if (token !== '') {
      try {

        const success1 = await voice.register(token);
        console.log('token success 2 ===> ', success1);
        allistner();

      } catch (err) {
        console.log('error ====>', err);
      }
    }
  };

  const saveFirebaseToken = async () => {
    const fcmToken = await messaging()?.getToken();
    console.log('fcmToken ====> ', fcmToken);
    const res = await axios.post(
      `https://99328-fe3-8b5d.ngrok.io/Firebase/register`,
      {
        userUniqueId: 'WA6BGPBNGPVRTRT',
        Token: fcmToken,
      },
    );

    console.log('res  22222 ====> ', res);
  };

  const getTokenAPI = async () => {
     saveFirebaseToken();
      const res = await axios.get(
        `https://9328-fe3-8b5d.ngrok.io/Call/Token?Identity=client:WA6BGPBNGPVRTRT`,
      );
      console.log('res ====> ', res?.data?.body?.token);
      setToken1(res?.data?.body?.token);
      initTelephonyWithToken(res?.data?.body?.token);
  };

  const onPress = async () => {
      const call = await voice.connect(token1, {
        To: 'client:WA6BGPBNGPVRTRT',
        From: '13324551640',
        recipientType: 'client',
        phoneNumber: 'client:WA6BGPBNGPVRTRT',
        Twilio_PhoneNumber: '13324551640',
      });
  };

  const getFcm = async () => {
    const fcm = await messaging()?.getToken();
    console.log('fcm =====> ', fcm);
  };

  useEffect(() => {
    const unsubscribe = messaging().onMessage(async remoteMessage => {
      Alert.alert('A new FCM message arrived!', JSON.stringify(remoteMessage));
    });

    getTokenAPI();

    return unsubscribe;
  }, []);

  const allistner = () => {
    voice.on('registered', callInvite => {
      console.log('registered ====> ', callInvite);
      // callInvite.accept();
    });
    voice.on('callInvite', callInvite => {
      console.log('callInvite ====> ', callInvite);
      callInvite.accept();
    });
  };
  return (
    <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
      <TouchableOpacity
        onPress={getFcm}
        style={{
          alignSelf: 'center',
          alignItems: 'center',
          justifyContent: 'center',
          width: 100,
          height: 100,
          backgroundColor: 'red',
          borderRadius: 20,
        }}>
        <Text style={{fontWeight: 'bold'}}> Get FCM Token</Text>
      </TouchableOpacity>
      <TouchableOpacity
        onPress={onPress}
        style={{
          alignSelf: 'center',
          alignItems: 'center',
          justifyContent: 'center',
          width: 100,
          height: 100,
          backgroundColor: 'red',
          borderRadius: 20,
        }}>
        <Text style={{fontWeight: 'bold'}}> Make Call</Text>
      </TouchableOpacity>
    </View>
  );
};
export default App;

---------------------------------

-index.js-

import {AppRegistry} from 'react-native';
import App from './App';
import React from 'react';
import {name as appName} from './app.json';
import messaging from '@react-native-firebase/messaging';

messaging().setBackgroundMessageHandler(async remoteMessage => {
  console.log('Message handled in the background!', remoteMessage);
});

function HeadlessCheck({isHeadless}) {
  if (isHeadless) {
    // App has been launched in the background by iOS, ignore
    return null;
  }

  return <App />;
}
AppRegistry.registerComponent(appName, () => HeadlessCheck);

----------------------------------------

And all other server side configuration about twilio official documentation. 
Need help & I shall be thankful to you in advance.

**Comment by bobiechen-twilio** [comment]
Hi @mohsinali-823788 

Do you have a Twilio Call SID when trying to make calls to the Android client but did not receive the incoming call notification?

**Comment by mohsinali-823788** [comment]
I used .Net Core and my caller code to make a call is:

----------------------------
using Client = Twilio.TwiML.Voice.Client;

var CallbackStatusUrl = $"{origin}/Call/CallbackStatus";

var statusCallbackEventList1 = new[]{
                Client.EventEnum.Answered,
                Client.EventEnum.Completed
            }.ToList();

dial.Client(phoneNumber.Replace("client:", ""), statusCallback: new Uri(CallbackStatusUrl), statusCallbackMethod: Twilio.Http.HttpMethod.Post, statusCallbackEvent: statusCallbackEventList1);

**Comment by bobiechen-twilio** [comment]
@mohsinali-823788 

The code snippet, especially the `dial.Client()`, you provided should result in a Twilio Call SID, and you should be able to see the call in the Twilio developer console (Monitor > Logs > Calls). If the `dial.Client()` call is made successfully you should also see the child leg Call SID in the call logs. In case something went wrong while making the call to the mobile client, you should see an error in the console or receive a notification.

**Comment by mohsinali-823788** [comment]
@bobiechen-twilio Thanks, but this is all done already. Even web to web client call received successfully but when i call from web to mobile then i cant receive call or notification or console in a listener. when i register a user in mobile then web client consider that user offline. But in case if i online same user from web it consider it online and call go ahead. 
Please guide me. I already apply all things according to twilio official documentation. Thanks

**Comment by sajin-csvote** [comment]
I had to add following lines to ./android/app/src/main/AppManifest.xml

```
     <service
        android:name="com.twiliovoicereactnative.VoiceFirebaseMessagingService"
        android:stopWithTask="false"
        android:exported="true">
      <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
      </intent-filter>
    </service>
    <service
        android:enabled="true"
        android:name="com.twiliovoicereactnative.IncomingCallNotificationService"
        android:exported="true">
      <intent-filter>
        <action android:name="ACTION_ACCEPT" />
        <action android:name="ACTION_REJECT" />
      </intent-filter>
    </service>
```

**Comment by GuilhermeLessa** [comment]
> I had to add following lines to ./android/app/src/main/AppManifest.xml, taken from reference app
> 
> ```
>      <service
>         android:name="com.twiliovoicereactnative.VoiceFirebaseMessagingService"
>         android:stopWithTask="false"
>         android:exported="true">
>       <intent-filter>
>         <action android:name="com.google.firebase.MESSAGING_EVENT" />
>       </intent-filter>
>     </service>
>     <service
>         android:enabled="true"
>         android:name="com.twiliovoicereactnative.IncomingCallNotificationService"
>         android:exported="true">
>       <intent-filter>
>         <action android:name="ACTION_ACCEPT" />
>         <action android:name="ACTION_REJECT" />
>       </intent-filter>
>     </service>
> ```

@bobiechen-twilio @mhuynh5757 would be nice mention it  and all of other requirements to call on the home of this repo doc

**Comment by mhuynh5757** [comment]
Hi all, thanks for the good community discussion. We've since added documentation to our repo about necessary Android manifest changes.
