### ISSUE TITLE
Android: Native interface is not shown on outgoing and incoming calls.

### ISSUE THREAD

**Issue by dianamariand92** [twilio/twilio-voice-react-native#154]
Hello, 

When making outbound calls and incoming calls, the native android UI is not displayed, on iOS it is.

**Comment by mhuynh5757** [comment]
Hi @dianamariand92 this is by design. We have no plans to support `ConnectionService` at the moment. I will surface this to my team and we can discuss internally, but we are unable to commit at this time.
