### ISSUE TITLE
How can i set the callerid to my calls 

### ISSUE THREAD

**Issue by AmirDoreh** [twilio/twilio-voice-react-native#157]
i have verified and added two numbers to registered phone numbers , i want to specify which number wanna be set as caller id , how can i get to that ? 

I am using Nodejs as backend service , and i am setting the caller id in the /voice route where twiml configure calls :

![Screenshot 2023-03-31 at 5 39 04 PM](https://user-images.githubusercontent.com/45465967/229151480-f4d05aa4-ee5d-4fcb-9ac0-375b48b076d9.png)

**Comment by mhuynh5757** [comment]
Hi @AmirDoreh thanks for reaching out. You seem to be on the right track, as long as the value of your `callerId` variable is set to one of your registered numbers, your TwiML should be correct.

**Comment by AmirDoreh** [comment]
thats right , the question is how can i pass that callerId number from the RN app in order to call the target from that specific caller id ? 

i want to have a dynamic structure in order to let users to be able to select number from mobile app and call the target from that number. 

@mhuynh5757

**Comment by AmirDoreh** [comment]
any idea ? @mhuynh5757

**Comment by mhuynh5757** [comment]
Hi @AmirDoreh please read the Twilio documentation here, it may be able to answer your question.

https://www.twilio.com/docs/voice/api/outgoing-caller-ids

For further assistance, I would recommend the official Twilio Support channels you can access from the Twilio homepage, as this question is outside the scope of this repository.
