### ISSUE TITLE
Voice Object Return empty Events

### ISSUE THREAD

**Issue by ZamsolSupportTeam** [twilio/twilio-voice-react-native#158]
Hi Team,
I'm try to use mention module but not able to fetch events.
see here response: 
{"_events": {}, "_eventsCount": 0, "_handleAudioDevicesUpdated": [Function anonymous], "_handleCallInvite": [Function anonymous], "_handleCallInviteAccepted": [Function anonymous], "_handleCallInviteRejected": [Function anonymous], "_handleCancelledCallInvite": [Function anonymous], "_handleError": [Function anonymous], "_handleNativeEvent": [Function anonymous], "_handleRegistered": [Function anonymous], "_handleUnregistered": [Function anonymous], "_nativeEventHandler": {"voiceEventAudioDevicesUpdated": [Function anonymous], "voiceEventCallInvite": [Function anonymous], "voiceEventCallInviteAccepted": [Function anonymous], "voiceEventCallInviteCancelled": [Function anonymous], "voiceEventCallInviteRejected": [Function anonymous], "voiceEventError": [Function anonymous], "voiceEventRegistered": [Function anonymous], "voiceEventUnregistered": [Function anonymous]}}
Can you please help?

**Comment by mhuynh5757** [comment]
Hi @ZamsolSupportTeam could you please elaborate on your issue? Have you bound listeners to the `voice` object you instantiated? Do you have any code snippets of how you're initializing and using the SDK?

**Comment by ZamsolSupportTeam** [comment]
see my code snap below.

import { Voice } from '@twilio/voice-react-native-sdk';
const voice = new Voice();
initVoiceModule();
let accessTokenVoice;
async function initVoiceModule() {
  try {
    accessTokenVoice = await getAccessTokenFromServer();
  } catch (err) {
      console.err(err)
  }
}
async function getAccessTokenFromServer()
{
  const twilio_token = await AsyncStorage.getItem("twilio_token");
  const success1=await voice.register(twilio_token);
  console.log('Token success 2 ===> ', success1);
  return twilio_token;
}

voice.on('register', (callInvite) => {
    console.log("Call Invite register Successfully")
  });
  voice.on('callInvite', (callInvite) => {
    callInvite.accept();
  });
const params={PhoneNumber: to_number,To:to_number,From:selected_from_number,CallerId: selected_from_number,groupId: leadGroup,leadId:callleadId,teamId: managerId, lead_table: lead_table, added_by: memberId, record: record,'recipentType':'client'};
const call = await voice.connect(twilioToken, params);

**Comment by mhuynh5757** [comment]
Hi @ZamsolSupportTeam, thanks for providing the code snippet. I'm still uncertain of your issue, however. Have you tried to bind listeners to the call object at the end of your snippet? Something like this:

```
call.on(Call.Event.Connected, () => { ... });
```

(Also in the future, please wrap code with the triple backtick for preformatted text. It helps tremendously with code-readability.)

**Comment by ZamsolSupportTeam** [comment]
Hi Team,

Yes, but when I initialize const voice = new Voice(); 

I got an empty Event as mentioned in the first comment.

I don't have any list of event listeners which I call.

Can you mention the list of events and why I got an empty list?

Please help very long time we are waiting to resolve these issues.

Thanks

**Comment by mhuynh5757** [comment]
Hi @ZamsolSupportTeam, apologies for letting this fall through the cracks. Please try again with the latest version of our SDK, we have resolved a lot of issues. Please reopen if this problem is still occurring for you.
