### ISSUE TITLE
Making call from background state - no microphone

### ISSUE THREAD

**Issue by wesdewitte** [twilio/twilio-voice-react-native#163]
When you make an outgoing call from the app running in the background state on android 13+. 
Then the microphone of the app does not work.

Tested with the base app in test/app

Its easy to reproduce:
Steps
- Have something that triggers the call in about 30 sec ( i used react-native-background-actions)
- Put the app on the background and lock phone
- Call starts fine
- You cant hear the caller, but the caller can hear someone on the otherside of the line

Is this a known issue or is there already a fix for this behaviour?

**Comment by jdegger** [comment]
Issue seems similar to something like:
- I try to connect a call to someone
- While connecting, I background my app because I'm impatient 
- When the other person pick ups the call, they can't hear me
- When I manually mute/unmute myself it works again

Seems like there is a problem with requesting the microphone permission in the background. 

@Twilio: is there an exception for microphone usage in the background for VOIP-apps? How can we avoid this issue?

**Comment by wesdewitte** [comment]
@mhuynh5757 Any internal update regarding this ticket?

**Comment by congkhanh24** [comment]
<img width="570" alt="Screenshot 2023-06-07 at 15 12 42" src="https://github.com/twilio/twilio-voice-react-native/assets/74224788/d452e27c-27df-4705-b1f0-688a0d5d402e">

I have met issue similar and fixed it like that

**Comment by mhuynh5757** [comment]
Apologies for the delay @wesdewitte.

Thank you for providing a potential fix @congkhanh24, is it possible for you to attempt this @wesdewitte?

**Comment by jiahui747** [comment]
@congkhanh24 Hey, your solution seems very promising. Could you provide information on how and where you added that xml to? Do you need to add it to the Twilio SDK source code? Cheers

**Comment by congkhanh24** [comment]
I just checked on beta version beta.2 and it didn't happen. Microphone works normally

**Comment by jiahui747** [comment]
> I just checked on beta version beta.2 and it didn't happen. Microphone works normally

Seems to still have the problem after I update to beta.2. I will test it a little more and update if I find anything useful.

**Comment by afalls-twilio** [comment]
@jiahui747 @congkhanh24 Was this on an Android API-34 device?

**Comment by jiahui747** [comment]
> @jiahui747 @congkhanh24 Was this on an Android API-34 device?

Hi, this is on an Android version 13.0

**Comment by afalls-twilio** [comment]
@jiahui747 I was unable to reproduce the issue. I tested on a Nexus 4a (Android-13) & the steps I followed were...
1) Place a call with the RN test app & background the RN app
2) lock screen, then have the receiver of the call accept the call
3) receiver should be able to hear the caller speak... if not, then the bug has been reproduced

are these steps correct?

**Comment by wesdewitte** [comment]
@afalls-twilio I my original case it was:

1. Put the app in background & lock screen
2. Start call
3. On the receiver end: You cant hear the caller, but the caller can hear someone on the otherside of the line

**Comment by jiahui747** [comment]
@afalls-twilio This is my case:

1. Start call on an Android phone with the SDK and have the receiver pick up. At the beginning both side can hear each other.
2. The Android phone will slowly have the screen black out until the screen is fully black (this could take a minute or two) but the call should still work for a minute or two after the screen turns black. 
3. While the screens black don't tap the screen but wait for 3+ minutes and the receiver will stop hearing anything because the microphone turned off.
4. You can check that the microphone was turned off by tapping the screen and checking the microphone icon on the top right corner of the screen.

**Comment by afalls-twilio** [comment]
@wesdewitte I attempted to follow those instructions but was unable to reproduce it. I have attached a video of that [here](https://drive.google.com/file/d/1mg6gUd_e_3J13kjaEf3SoSUy3qeXeH89/view?usp=sharing). Also, What device are you using?

@jiahui747 Same issue, was not able to reproduce. 

If either are willing, I have a branch that may contain a fix given that both examples provided involved android 13+. Try out the branch and let me know if it fixes the issue..Thanks! (branch name: afalls/VBLOCKS-1641/Audio-Microphone-issues)

**Comment by jiahui747** [comment]
@afalls-twilio Sorry the waits are not long enough and the flow was not correct. I will try to create a video of the problem and post it here along with more information about the device I'm using to test. But thanks for trying.

**Comment by TimChandra** [comment]
I'm a colleague of @jiahui747. Here is the video showing the issue he described: https://drive.google.com/file/d/1OYfwsLIS9vReHyTuZZVhzMIqP7KmbINK/view?usp=sharing.

In the beginning of the video, you can hear my voice going through to the callee phone. After the screen on the caller phone fades to black, you can still hear my voice on the callee phone. Around the 1 minute mark of the call, my voice stops going through. The microphone only becomes active again after I activate the screen and going back to the app (you can see the microphone indicator on the top right corner of the screen).

Here is the code I used for the app, using @twilio/voice-react-native-sdk v1.0.0-beta.2:

`
import { useEffect, useState } from "react";
import { Button, View } from "react-native";
import { Call, Voice } from "@twilio/voice-react-native-sdk";
import { Audio } from "expo-av";

import { service } from "./service";

const App = () => {
  const [call, setCall] = useState<Call | null>(null);

  useEffect(() => {
    Audio.requestPermissionsAsync();
  }, []);

  const makeCall = async () => {
    const {
      data: { token },
    } = await service.get("/token");
    const voice = new Voice();
    const call = await voice.connect(token);
    setCall(call);
  };

  const stopCall = async () => {
    await call?.disconnect();
  };

  return (
    <View>
      <Button title="call" onPress={makeCall} />
      <Button title="stop" onPress={stopCall} />
    </View>
  );
};

export { App };
`

And I just set up a simple incoming voice call webhook on my server:

`
import { RequestHandler } from "express";
import { twiml } from "twilio";

const startCall: RequestHandler = async (req, res, next) => {
  try {
    const twimlRes = new twiml.VoiceResponse();
    twimlRes.dial({ callerId: process.env.FROM_NUMBER }, process.env.TO_NUMBER);
    res.type("xml").send(twimlRes.toString());
  } catch (err) {
    next(err);
  }
};

export { startCall };
`

**Comment by afalls-twilio** [comment]
@TimChandra Thanks! I was able to reproduce it and I have a [PR](https://github.com/twilio/twilio-voice-react-native/pull/196) with come changes that fix it!
