### ISSUE TITLE
AudioDevice.Type Mismatch in iOS

### ISSUE THREAD

**Issue by treycucco** [twilio/twilio-voice-react-native#165]
The string values for `AudioDevice.Type` in iOS do not match those in TypeScript and Android. TypeScript and Android use all-lowercase names, while iOS has title-case constants.

Comparing an Audio Device's type to an enum value always fails on iOS. Instead it's necessary to `toLowerCase` the type before comparing.

TypeScript:

https://github.com/twilio/twilio-voice-react-native/blob/2c64693a6e426a9eaa4d86e02afc6e633cc54d1f/src/AudioDevice.tsx#L78-L88

iOS:

https://github.com/twilio/twilio-voice-react-native/blob/2c64693a6e426a9eaa4d86e02afc6e633cc54d1f/ios/TwilioVoiceReactNative.m#L26-L28

Android:

https://github.com/twilio/twilio-voice-react-native/blob/2c64693a6e426a9eaa4d86e02afc6e633cc54d1f/android/src/main/java/com/twiliovoicereactnative/AudioSwitchManager.java#L62-L67

**Comment by mhuynh5757** [comment]
Hi @treycucco thanks for bringing this one up to our attention. I've filed an internal ticket to investigate further.

**Comment by mhuynh5757** [comment]
Hi @treycucco we've fixed this issue with pull request #183. Please file another ticket if you encounter any issues, thanks for your patience.
