### ISSUE TITLE
iOS: No known class method for selector 'handleNotification:delegate:delegateQueue:'

### ISSUE THREAD

**Issue by djinely** [twilio/twilio-voice-react-native#167]
<img width="1125" alt="Screenshot 2023-05-15 at 14 22 21" src="https://github.com/twilio/twilio-voice-react-native/assets/11662157/6e1c33b0-d717-4924-8b4b-333c6e64c7fe">

Running native project with Expo.

**Comment by omerts** [comment]
@djinely Can you look at the log and add it here as well? I think this  might be related to https://github.com/twilio/twilio-voice-react-native/issues/161

**Comment by djinely** [comment]
@omerts build is failing at compile time, while the issue you reported is at run time.

**Comment by yagitoshiro** [comment]
@djinely I bumped into the same problem and this helped me out.

Edit Podfile and added `IPHONEOS_DEPLOYMENT_TARGET`
```
  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
      end
    end
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
```

and then removed Podfile.lock and Pods directory. And reinstalled all the dependencies with `--repo-update` option.

```
pod install --repo-update
```

Hope this helps you.

**Comment by mhuynh5757** [comment]
Thanks all for the community discussion. I'm going to close this issue as stale for now, please reopen if this issue is still occurring in the latest version of the SDK.
