### ISSUE TITLE
[iOS]Outgoing Call Issues on IOS Device

### ISSUE THREAD

**Issue by ZamsolSupportTeam** [twilio/twilio-voice-react-native#169]
I'm trying to make outgoing call with "@twilio/voice-react-native-sdk" but getting Error "Cannot read property 'voice_connect_ios' ".

here is my code
import { Voice } from '@twilio/voice-react-native-sdk';
const voice = new Voice();
initVoiceModule();
let accessTokenVoice;
async function initVoiceModule() {
  try {
    accessTokenVoice = await getAccessTokenFromServer();
  } catch (err) {
      console.err(err)
  }
}
async function getAccessTokenFromServer()
{
  const twilio_token = await AsyncStorage.getItem("twilio_token");
  const success1=await voice.register(twilio_token);
  console.log('Token success 2 ===> ', success1);
  return twilio_token;
}

voice.on('register', (callInvite) => {
    console.log("Call Invite register Successfully")
  });
  voice.on('callInvite', (callInvite) => {
    callInvite.accept();
  });

const params={PhoneNumber: to_number,To:to_number,From:selected_from_number,CallerId: selected_from_number,groupId: leadGroup,leadId:callleadId,teamId: managerId, lead_table: lead_table, added_by: memberId, record: record,'recipentType':'client'};
  
const call = await voice.connect(twilioToken, params);

Note: Using Other module i'm able to make outgoing call with above token.
Please help.

**Comment by mhuynh5757** [comment]
Hi @ZamsolSupportTeam thanks for reaching out. What platform are you attempting this on? It seems like iOS, if so, what device and iOS version?

**Comment by ZamsolSupportTeam** [comment]
Hi Team,

Yes, I'm using React Native IOS Platform.

Device iphone 13 Version 16.5

Thanks for your Reply.

**Comment by mhuynh5757** [comment]
Hi @ZamsolSupportTeam apologies for the delayed response. Could you use the latest version of the SDK and see if the problem still occurs? Also, are you using a physical device, or a simulator?

**Comment by mhuynh5757** [comment]
Hi @ZamsolSupportTeam I'd like to close this issue as stale for now, please feel free to reach out if you are still encountering issues.
