### ISSUE TITLE
iOS no ringback sound when making a call

### ISSUE THREAD

**Issue by omerts** [twilio/twilio-voice-react-native#172]
Hello,

When making a call in iOS, there is no ringback (the sound the caller hears while waiting for an answer) sound, but once the other side answers you can hear fine.

**Comment by omerts** [comment]
Finally found the undocumented solution.

For iOS you have to put a file named `ringtone.wav` under the main project. 
For Android, there is a default ringtone, but you can change it by putting a file named ringtone.wav under: `http://android/app/src/main/res/raw/`.

Trying to change the ringtone using [TwiML](https://www.twilio.com/docs/voice/twiml/dial?code-sample=code-dial-a-phone-number-from-a-twilio-client&code-language=Ruby&code-sdk-version=5.x#ringtone) has not effect.

This needs to really be added to the documentation. @bobiechen-twilio

**Comment by mhuynh5757** [comment]
Hi @omerts, thanks for bringing this one up and providing a workaround. We've filed an internal ticket to improve the documentation around this.
