### ISSUE TITLE
Twilio push notification handler overrides existing VoIP handlers

### ISSUE THREAD

**Issue by frances3006** [twilio/twilio-voice-react-native#175]
We are currently integrating our React native application with this library. Our application already handles VoIP notifications for video calls with another provider and when we integrate this library, the setup for our VoIP push notifications with our pre-existing provider no longer works and the notifications do not come through.

We suspect the issue might originate from these lines: https://github.com/twilio/twilio-voice-react-native/blob/2c64693a6e426a9eaa4d86e02afc6e633cc54d1f/ios/TwilioVoicePushRegistry.m#LL33C1-L37C2  

Would it be possible to fix this issue, or add in some customisability (possibly that we can add into our AppDelegate) so that we can use both Twilio and our existing provider at the same time for VoIP push notifications?

**Comment by frances3006** [comment]
hi @bobiechen-twilio , just wanted to add here that we have the same issue with Android. Do you have any pointers on how to handle it on android, or do you have any plans for changes to support this use case?

**Comment by kpchoy** [comment]
We currently do no plan to support this usecase. There should be no issue having multiple firebase listeners from our testing. Please open another issue if you need further assistance.
