### ISSUE TITLE
Example App 'yarn install' does nothing

### ISSUE THREAD

**Issue by kjdfjhdjkh** [twilio/twilio-voice-react-native#178]
When I follow the instructions on the test/app page and perform Step 3 that has me do "yarn install", there is no output or error message. It simply does nothing at all.

**Comment by kjdfjhdjkh** [comment]
Oops, sorry!

I'm using Node 18.16.0 and Yarn 1.22.19. NPM is at 9.7.1

**Comment by kjdfjhdjkh** [comment]
It's bizarre, because no yarn commands work in that twilio-voice-react-native folder after cloning the repository and switching to the directory. I've been trying to figure out if there's a log file outputted somewhere, but even running it with --verbose does nothing at all.

**Comment by mhuynh5757** [comment]
Hi @kjdfjhdjkh sorry for the delayed response. I saw your activity in the Reference App repository and it seems like you were able to get that working? It also uses `yarn` so I'm assuming `yarn` worked in that directory for you? If so, not sure what would cause the difference between this folder and that one... 😵

**Comment by kjdfjhdjkh** [comment]
No worries 😊

Yeah, the Reference App worked fine following the directions with that, and yarn works with all other apps I've used it with, but for some weird reason it doesn't work in that specific one.

What should the output actually be after running that command? Is there any way to identify if it's actually doing anything after I run the command?

**Comment by mhuynh5757** [comment]
Hmm. Could you try `yarn` instead of `yarn install` on step 3?

**Comment by kjdfjhdjkh** [comment]
Trying `yarn` instead of `yarn install` on step 3 doesn't output anything either 🤔

**Comment by mhuynh5757** [comment]
This is very strange. I'm doing `yarn` inside the root of the repo, and it works as expected. I see ```
yarn run v1.22.19
$ yarn run build:constants && yarn --cwd test/app && yarn && yarn pods
$ node ./scripts/constants.js
[1/4] 🔍  Resolving packages...
...
``` and it seems to function just fine for me...

Unfortunately it seems like it's some environment thing on your end. I'm sorry I couldn't help more 😞

**Comment by kjdfjhdjkh** [comment]
Very strange. I'll try it on another computer, but if it's working for you, then it probably is my environment.

No worries Michael, thank you for looking into it 😊

Have a fabulous rest of your week!

**Comment by kjdfjhdjkh** [comment]
After looking into this more, it seems if I add "shell: true" under the options in bootstrap.js, the `yarn install` command starts resolving the packages and fetching the packages, but then it shows the following error:

```
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/twilio/api-documenter.git
Directory: C:\twilio-voice-react-native
Output:
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by kjdfjhdjkh** [comment]
I managed to get it further by adding the ssh key to my Github account with these instructions:

https://stackoverflow.com/questions/2643502/git-how-to-solve-permission-denied-publickey-error-when-using-git

However, now I get the following error when trying to run `yarn install`:
```
$ yarn install
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "react-native > metro-react-native-babel-transformer@0.59.0" has unmet peer dependency "@babel/core@*".
[4/4] Building fresh packages...
$ yarn run build:constants && bob build
yarn run v1.22.19
$ node ./scripts/constants.js
C:\twilio-voice-react-native\scripts\constants.js:29
    throw new Error(`Constants source malformed on line: ${idx}.`);
          ^

Error: Constants source malformed on line: 0.
    at parse (C:\twilio-voice-react-native\scripts\constants.js:29:11)
    at Array.map (<anonymous>)
    at parseConstants (C:\twilio-voice-react-native\scripts\constants.js:32:56)
    at transform (C:\twilio-voice-react-native\scripts\constants.js:155:28)
    at async main (C:\twilio-voice-react-native\scripts\constants.js:177:3)

Node.js v18.16.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
{
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 19556,
  stdout: null,
  stderr: null
}
```

I'm on a Windows machine using GIT Bash.

**Comment by mhuynh5757** [comment]
Hi @kjdfjhdjkh thanks for reaching out. Your testing and feedback is invaluable, it will certainly help iron out the frustrations and improve the experience for everyone. I really appreciate it. I'll try to address your posts in order.

* It seems like the bootstrap script that the RN team put into the boilerplate doesn't work well under Windows and git bash, we'll file an internal ticket to investigate further. It seems like `shell: true` is a quick solution.
* The `api-documenter` dependency is a fork of an open-source tool that we modified for our use-case. We didn't see a need to publish to `npm` since it's only for us to generate documentation, but it seems like it won't pull properly if users don't have a authenticated git client. I'm thinking if we specify pulling via https in the `package.json` it might solve this issue.
* Lastly, I'm curious as to why the `constants` script is failing. I'm assuming that you've made no changes to the `constants/constants.src` file, so perhaps the Regex parser functions differently in Windows git bash, perhaps the script expects Windows line-endings instead of Unix-like line-endings.

**Comment by kjdfjhdjkh** [comment]
> Hi @kjdfjhdjkh thanks for reaching out. Your testing and feedback is invaluable, it will certainly help iron out the frustrations and improve the experience for everyone. I really appreciate it. I'll try to address your posts in order.
> 
>     * It seems like the bootstrap script that the RN team put into the boilerplate doesn't work well under Windows and git bash, we'll file an internal ticket to investigate further. It seems like `shell: true` is a quick solution.

It does seem like a Windows exclusive issue. I tried it under an Ubuntu VM and it at least got past the Resolving packages stage.

> 
>     * The `api-documenter` dependency is a fork of an open-source tool that we modified for our use-case. We didn't see a need to publish to `npm` since it's only for us to generate documentation, but it seems like it won't pull properly if users don't have a authenticated git client. I'm thinking if we specify pulling via https in the `package.json` it might solve this issue.
> 
I can confirm that changing line 64 from:
```
"api-documenter": "github:twilio/api-documenter#v0.0.1",
```
to:
```
"api-documenter": "https://github.com/twilio/twilio-api-documenter#v0.0.1",
```
resolves the unauthenticated client issue.

>     * Lastly, I'm curious as to why the `constants` script is failing. I'm assuming that you've made no changes to the `constants/constants.src` file, so perhaps the Regex parser functions differently in Windows git bash, perhaps the script expects Windows line-endings instead of Unix-like line-endings.

Yes, this was with no modifications to any of the script files. Interestingly enough, this issue was also resolved upon performing the steps in Ubuntu instead of Windows, so I think you may be onto something.

I'm happy to test any modifications to files on the Windows install if you'd like.

**Comment by mhuynh5757** [comment]
Hi @kjdfjhdjkh apologies for not having a response for you. Unfortunately Windows Git Bash is not a platform we support (but we'd like to able to!). We have a ticket internally to track this, and I'm going to close this ticket for now.
