### ISSUE TITLE
Get call object in react native app on accepting the call from notification when the app is in killed state

### ISSUE THREAD

**Issue by GopendraK** [twilio/twilio-voice-react-native#180]
Hello,

Is there any way that i can get the reference to call object in the react native app on accepting the call directly from notification when the app is in killed state.

**Comment by mhuynh5757** [comment]
Hi @GopendraK thanks for reaching out. You should bootstrap the Voice SDK state as soon as possible in your JS code. Check out the "bootstrap" function in the `test/app` folder for an example on how to do it.

https://github.com/twilio/twilio-voice-react-native/blob/main/test/app/src/hook.ts#L336

**Comment by congkhanh24** [comment]
Hi @mhuynh5757. function voice.getCalls() always return _customParameters: {}, help me fix it. thank you!

**Comment by congkhanh24** [comment]
I debugged and edited the function **acceptCall** in the file **IncomingCallNotificationService**  like this. It works ok.
<img width="841" alt="Screenshot 2023-07-04 at 17 24 00" src="https://github.com/twilio/twilio-voice-react-native/assets/74224788/d45b428a-bfb0-40d0-aa28-aadcae546c99">

**Comment by mhuynh5757** [comment]
Hi @congkhanh24, thanks for reaching out. Is this a separate issue from the original post? If so, please make a new issue.

**Comment by congkhanh24** [comment]
No @mhuynh5757

**Comment by mhuynh5757** [comment]
Hi @congkhanh24 this should be resolved in the latest release. Please update the dependency and try again. I'm going to close this issue as stale for now, please reopen if you need further assistance.
