### ISSUE TITLE
Notification not showing banner if I swipe up notification before

### ISSUE THREAD

**Issue by congkhanh24** [twilio/twilio-voice-react-native#186]
when I have an incoming call. I receive a push notification and if I swipe up this notification and wait it was canceled. after that I continue to recieve another call invite -> Notification not showing the banner, it just shows in the notification bar.

I want to it always shows even if I swipe up notifications. Who can help me? Thanks a lot!

https://github.com/twilio/twilio-voice-react-native/assets/74224788/247383c1-e56a-4c07-ba9b-244786136db9

**Comment by kpchoy** [comment]
Please update to the latest version of the sdk. It seems like original issue is stale. Please create a new issue if you are experiencing problems.
