### ISSUE TITLE
Access Token is about to expire event 

### ISSUE THREAD

**Issue by MykolaKobetiakCloudGenie** [twilio/twilio-voice-react-native#188]
Hi,

I am currently building RN Expo app.  Incoming and outgoing for IOS works fine, but I am not sure how to manage access token ttl.
I am not receiving any event about the token being close to expiring or even when the token is already expired.
Any ideas here?

**Comment by MykolaKobetiakCloudGenie** [comment]
The problem was resolved. An access token is used to register an incoming call event listener (push notifications), and once it is registered successfully you do not need to refresh the token to register the incoming call listener again when the token expires. The only place which should be checked is outgoing calls, before each outgoing it is good to check token validity, and if it is invalid for some reason or expired just request a new one from your server and do a call(also you can register voice with new token again).

If I am wrong, please correct me. And thanks for the awesome library!

**Comment by tamdvyounetgroup** [comment]
how to implement it
