### ISSUE TITLE
How to add an icon on the native call screen to the button that takes you to the application ?

### ISSUE THREAD

**Issue by AlekseiEDT** [twilio/twilio-voice-react-native#191]
How to add an icon on the native call screen to the button that takes you to the application ? 

<img width="350" alt="image" src="https://github.com/twilio/twilio-voice-react-native/assets/138133071/5f896c49-00fc-4ad9-bb5f-d0a0ce7932f9">

**Comment by bobiechen-twilio** [comment]
Hi @AlekseiEDT 

Thanks for reaching out. To set an app icon in the iOS native call view, you can use the `Voice.setCallKitConfiguration()` method and the [callKitIconTemplateImageData](https://github.com/twilio/twilio-voice-react-native/blob/main/src/type/CallKit.ts#L14C5-L14C33) property to assign the image. 

The image should be in PNG format and 80x80 in size. You will also need to add the file into the Xcode project:
<img width="379" alt="Screenshot 2023-08-03 at 3 53 03 PM" src="https://github.com/twilio/twilio-voice-react-native/assets/16326574/e8bf6f73-531d-4cd8-94bd-1919e1591672">

-bobie

**Comment by mhuynh5757** [comment]
Hi all, going to close this issue as it seems the original problem has been solved. Thanks!

**Comment by dwbelliston** [comment]
Anyone know how to do this with expo? Is there a way to provide the image to the xcode assets?
