### ISSUE TITLE
How to add a hold button on the native iPhone call screen?

### ISSUE THREAD

**Issue by AlekseiEDT** [twilio/twilio-voice-react-native#192]
How to add a hold button on the native iPhone call screen?

<img width="351" alt="image" src="https://github.com/twilio/twilio-voice-react-native/assets/138133071/55c450ea-20c6-48d2-a3c4-1c8caaaa437f">

**Comment by mhuynh5757** [comment]
Hi @AlekseiEDT, I'd like to close this issue as stale for now. Please feel free to reopen or file another issue if you still need assistance.
