### ISSUE TITLE
IOS native call screen is not hiding after hanging up from the app screen.

### ISSUE THREAD

**Issue by MykolaKobetiakCloudGenie** [twilio/twilio-voice-react-native#194]
- Device: iPhone 12
 - OS: 16.5.1

Hi there!
I am building a VoIP app using RN + EXPO. 

Currently, I am facing an issue with incoming calls IOS native screen.
The problem appears only when the app was backgrounded before.  

Steps:  Incoming call appears on the native ios screen, after accepting the call, the app becomes active and I am redirected to the call screen inside my application. After pressing the hung-up button on the app screen call was successfully disconnected but the native ios screen is still there and the seconds on the native IOS call screen continue to count.

![MicrosoftTeams-image (6)](https://github.com/twilio/twilio-voice-react-native/assets/126026642/ff48fd02-5d18-4395-a7f7-5d4647065e0f)
![MicrosoftTeams-image (7)](https://github.com/twilio/twilio-voice-react-native/assets/126026642/1d721c7c-56a3-4ae8-9533-e1935c523c1e)
![MicrosoftTeams-image (8)](https://github.com/twilio/twilio-voice-react-native/assets/126026642/6938b89b-8b65-4dea-a882-6ba1d9a7f2c6)
![MicrosoftTeams-image (9)](https://github.com/twilio/twilio-voice-react-native/assets/126026642/6d619f1a-bcae-4b61-b198-2746b958bfe5)
![MicrosoftTeams-image (10)](https://github.com/twilio/twilio-voice-react-native/assets/126026642/be70d974-ce8f-4202-ab35-b4b718b3a06a)

**Comment by MykolaKobetiakCloudGenie** [comment]
Thanks for the response @bobiechen-twilio 

Unfortunately, I am not able to do what you are asking for...

**Comment by congkhanh24** [comment]
@MykolaKobetiakCloudGenie
Do you use function `voice.setCallKitConfiguration({ callKitIconTemplateImageData: 'icon', });`. I have the issue same as you. After removed it, I didn't meet this issue

**Comment by dev3whistlebiz** [comment]
Had the same issue but invoking voice.setCallKitConfiguration before voice.register seems to resolve the issue

**Comment by kpchoy** [comment]
It seems like original issue is stale. Please create a new issue if you are experiencing problems.
