### ISSUE TITLE
Android incoming calls 

### ISSUE THREAD

**Issue by MykolaKobetiakCloudGenie** [twilio/twilio-voice-react-native#195]
- Device: Pixel 7

Hey,

I am building a VoIP app with RN + EXPO.
Currently, I am facing an issue with incoming calls on Android device (development build). 
IOS work fine.

The problems are: 
 - push notification is showing for a short period of time, as regular push.
- There is no accept/decline buttons on push notification.
- There is no ringing signal on the caller's side.
- No "call invite" event.

I trayed with simulators. Have no idea what it can be here. Could you help, please?
![MicrosoftTeams-image](https://github.com/twilio/twilio-voice-react-native/assets/126026642/3f3243cb-c46d-4b94-ad3f-24a3ac6079d9)

**Comment by mhuynh5757** [comment]
Hi @MykolaKobetiakCloudGenie thanks for reaching out. What version of Android is your emulator running?

**Comment by MykolaKobetiakCloudGenie** [comment]
Hi @mhuynh5757 

It is a real device Pixel 7. I found where was the problem. I have an expo push notification, there was a conflict between Twilio push and mine.

To manage this I added a custom plugin that modifies AndroidManifest.xml adding there needed Twilio RN services. Now it works well. Next step I will add a .java service for managing push as mentioned here 160.

Thank you for the reply!

**Comment by amitava82** [comment]
@MykolaKobetiakCloudGenie Can you please tell me how you configured push notification for expo app since expo already handle the push notification service? I'm not sure where can I get server key.

**Comment by MykolaKobetiakCloudGenie** [comment]
> @MykolaKobetiakCloudGenie Can you please tell me how you configured push notification for expo app since expo already handle the push notification service? I'm not sure where can I get server key.

This link should help you. You will have to add a service for handling notifications from Twilio and from Expo separately.

Server Key you can get from Fairbase (Need to create account and add your app there)
![image](https://github.com/twilio/twilio-voice-react-native/assets/126026642/ba958bbb-2f7f-4870-8f6f-98eabc7de953)


https://github.com/twilio/twilio-voice-react-native/issues/116

**Comment by askel4dd** [comment]
Cloud Messaging API (Legacy) on new Firebase accounts is not enabled by default, so there is an extra step to enable it before you will see it like on the screenshot above
