### ISSUE TITLE
Android - Customizing the UI of push notifications in the background

### ISSUE THREAD

**Issue by ka-ito** [twilio/twilio-voice-react-native#200]
Hello,

Is it possible to customize the UI of push notifications in the background on Android?
I would like to have a notification display similar to iOS when a push notification arrives.

**Comment by afalls-twilio** [comment]
@ka-ito Unfortunately, there is not a way today at the JS layer. If you are willing to modify the sdk, you can change these layout files [here](https://github.com/twilio/twilio-voice-react-native/tree/main/android/src/main/res/layout) and the mapping of ids associated with your layout to code [here](https://github.com/twilio/twilio-voice-react-native/blob/b33546955426f4562a9f535f6257985f27247ede/android/src/main/java/com/twiliovoicereactnative/NotificationUtility.java#L73) & [here](https://github.com/twilio/twilio-voice-react-native/blob/b33546955426f4562a9f535f6257985f27247ede/android/src/main/java/com/twiliovoicereactnative/NotificationUtility.java#L114)

**Comment by kpchoy** [comment]
This issue is stale, please open a new issue if you are experiencing issues.
