### ISSUE TITLE
Android - Can not control audio device during outbound ringing

### ISSUE THREAD

**Issue by omerts** [twilio/twilio-voice-react-native#201]
# Issue

## Pre-submission Checklist
- [V] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [V] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [V] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
When an outbound call is made, you can't control the audio device, and changing the audio device has no effect. 

## Reproduction Steps
1. Make an outgoing call
2. Before the other side answers press the speaker icon to change to the speaker device

## Expected Behavior
The ringing tone should be outputted from the speaker

## Actual Behavior
Ringing tone stays in the earpiece 

## Reproduction Frequency
100%

## Software and Device Information
 - Device: Any android device
 - OS: Android 
 - React version: 18.2.0
 - React Native version: 0.71.7
 - Node version: 18.16.0
 - npm or yarn version: yarn 1.22.19

## Additional Context
Seems to be caused by this PR https://github.com/twilio/twilio-voice-react-native/pull/61

**Comment by afalls-twilio** [comment]
@omerts this issue should be fixed as of beta.4 those changes referred in the PR have been changed.
