### ISSUE TITLE
How to change the caller's number to a different value on the native call screen, for an incoming call.

### ISSUE THREAD

**Issue by AlekseiEDT** [twilio/twilio-voice-react-native#207]
## Screenshots
<img width="452" alt="image" src="https://github.com/twilio/twilio-voice-react-native/assets/138133071/9e8e608a-5812-450b-ad21-59cc179b0acd">
<img width="453" alt="image" src="https://github.com/twilio/twilio-voice-react-native/assets/138133071/d66743d7-f3e6-44cb-a353-d9faa63bf1d9">

## Software and Device Information
 - Device: [e.g. iPhone 8]
 - OS: [e.g. iOS 16.3]
 - React version: [e.g. 18.2.0]
 - React Native version: [e.g. 0.71.6]

## Additional Context
I didn't find in the library, how I can change the number of the caller's, who calls me, to some other value, on the call screen. This only for incoming call. Please help me with this.

**Comment by MykolaKobetiakCloudGenie** [comment]
@AlekseiEDT you can use on BE side custom parameters and pass displayName there.

For example: client.parameter({ name: 'displayName', value: contact.firstName + ' ' + contact.lastName });

**Comment by AlekseiEDT** [comment]
@MykolaKobetiakCloudGenie, @bobiechen-twilio, thanks, that helped me.

**Comment by kpchoy** [comment]
Please update to the latest version. The new api should cover this usecase. Please open another issue if you still experience problems.

**Comment by periabyte** [comment]
@kpchoy can you provide an example to switch from `displayName` to the new API?
