### ISSUE TITLE
The creation of release builds for iOS and Android was unsuccessful.

### ISSUE THREAD

**Issue by jaisonjam1988** [twilio/twilio-voice-react-native#216]
# Issue

## Pre-submission Checklist
- [x] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
When I use "./gradlew assembleRelease" to construct a release build, I get the following problem.

In Android:

error: export declaration must be at top level of module     
export var Listener;

In IOS:

error node_modules/@twilio/voice-react-native-sdk/src/Call.tsx: "Export" statement may only appear at the top level in file node_modules/@twilio/

voice-react-native-sdk/src/Call.tsx

**Comment by mhuynh5757** [comment]
Hi @jaisonjam1988 could you share your environment setup? There's a lot of dependencies with React Native so please be as verbose as possible. Node version, NDK/Java versions, etc.

**Comment by dianamariand92** [comment]
Hi @mhuynh5757  I have the same problem. I was using node 16.20.2 and I have the same problem on IOS. I upgraded node version to 18.17.1 and still getting the same error. 

"react": "18.2.0
"react-native": "0.72.4"


![Screen Shot 2023-08-23 at 1 35 31 AM](https://github.com/twilio/twilio-voice-react-native/assets/36927150/3f07a66c-c538-4bb4-baab-0bcda34d16f7)

![WhatsApp Image 2023-08-23 at 1 37 58 AM](https://github.com/twilio/twilio-voice-react-native/assets/36927150/af6624bb-f5bb-4c9c-9ae0-e8d69ebccc97)

**Comment by mhuynh5757** [comment]
Hi all, can you confirm if you are using Expo?

**Comment by dianamariand92** [comment]
Hi @mhuynh5757, 

No, I am not using expo. Using React Native CLI.

**Comment by mhuynh5757** [comment]
I see, thanks for the information. Do you mind attempting to build and run the test app that's part of this repo? It is located within `test/app`. This should provide more information to me about this issue.

**Comment by dianamariand92** [comment]
@mhuynh5757 The only way around this error was to remove the export instance in (exxport namespace Listener) in node_modules/@twilio/voice-react-native-sdk/src/Voice.tsx (line 1037) and in node_modules/@twilio/voice-react-native-sdk/src/Voice.tsxCall.tsx (line 1050). Those lines are generating the error. I hope this helps!

**Comment by tuncaulubilge** [comment]
> Hi @mhuynh5757 I have the same problem. I was using node 16.20.2 and I have the same problem on IOS. I upgraded node version to 18.17.1 and still getting the same error.
> 
> "react": "18.2.0 "react-native": "0.72.4"
> 

@dianamariand92 has reported the issue occurring on Node 18 yet the issue is closed with the suggestion of updating to node 18. 

Also both @dianamariand92 and @gbinu42 have suggested simple solutions to make this library compatible with the older versions of node. It's difficult to understand why these suggestions were ignored and the issue was closed without a solution.

**Comment by tuncaulubilge** [comment]
Also worth mentioning that Node 18 has become the recommended version by React Native only on the latest version (0.73).

You can see RN 0.72 recommends Node 16, and 0.71 recommends Node 14: https://reactnative.dev/docs/0.72/environment-setup

Initial release for React Native 0.73 was 3 months ago (which is much younger than this issue), with patches still being rolled out, so it's safe to assume most consumers of this library still hasn't migrated to React Native 0.73 and potentially to Node 18+
