### ISSUE TITLE
Error unregistering device from Twilio

### ISSUE THREAD

**Issue by dianamariand92** [twilio/twilio-voice-react-native#218]
# Issue

## Pre-submission Checklist
- [x ] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [x ] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [x ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 

Getting this error when unregistering 

 LOG  Voice on unregister {"_events": {}, "_eventsCount": 0, "_handleAudioDevicesUpdated": [Function anonymous], "_handleCallInvite": [Function anonymous], "_handleCallInviteAccepted": [Function anonymous], "_handleCallInviteNotificationTapped": [Function anonymous], "_handleCallInviteRejected": [Function anonymous], "_handleCancelledCallInvite": [Function anonymous], "_handleError": [Function anonymous], "_handleNativeEvent": [Function anonymous], "_handleRegistered": [Function anonymous], "_handleUnregistered": [Function anonymous], "_nativeEventHandler": {"voiceEventAudioDevicesUpdated": [Function anonymous], "voiceEventCallInvite": [Function anonymous], "voiceEventCallInviteAccepted": [Function anonymous], "voiceEventCallInviteCancelled": [Function anonymous], "voiceEventCallInviteNotificationTapped": [Function anonymous], "voiceEventCallInviteRejected": [Function anonymous], "voiceEventError": [Function anonymous], "voiceEventRegistered": [Function anonymous], "voiceEventUnregistered": [Function anonymous]}} 
 LOG Unregister Error:     [Error: Registration in progress. Please try again later]

## Reproduction Steps
This is how I am initializing 
const voice = new Voice();
await voice.initializePushRegistry();

And when I am executing the unregister 
await voice.unregister(token);

## Expected Behavior
Unregister the device without any error.

## Actual Behavior
Generate the following error:
Unregister Error:     [Error: Registration in progress. Please try again later]

## Reproduction Frequency
It doesn't always happen. I can't determine when it happens. Sometimes the error is different and refers to the Pushkit registering itself when it should do an unregister.

## Software and Device Information
**Please complete the following information.**
 - Device: iPhone 13 Pro
 - OS: IOS 16
 - React version: 18.2.0
 - React Native version: 0.72.4
 - Node version: 16.20.2
 - npm or yarn version: 8.19.4

**Comment by bobiechen-twilio** [comment]
Hi @dianamariand92

As the error message suggests, another registration/unregistration task is still in progress or the boolean flag indicating this was not reset properly when the JS bundle was restarted. Any chance you can find the log message in the Xcode debugger?

**Comment by dianamariand92** [comment]
Hi @bobiechen-twilio 

Thanks for your reply. Actually, as I said in the issue, this happens sometimes. If I get the error again I'll post it here.
