### ISSUE TITLE
Incoming Calls issue on multiple devices

### ISSUE THREAD

**Issue by dianamariand92** [twilio/twilio-voice-react-native#221]
# Issue

## Pre-submission Checklist
- [x ] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [ x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [x ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
We have an integration that works on web, android and ios. When there is an incoming call, it rings on all devices, but when the call is hung up on Android or IOS, the call is automatically disconnected on the other device that did not reject the call. In the case of the web, the call continues ringing correctly. I don't think this behavior is related to Android or IOS but to receiving the call on multiple mobile devices.

## Reproduction Steps
To reproduce this error, you can receive the call on several mobile devices at the same time and then reject the call on one of them, which will end up rejecting the call on the others.

## Expected Behavior
Only reject the call on the device that rejected it and continue ringing in the others.

## Actual Behavior
The call is terminated on all devices.

## Reproduction Frequency
Always

## Screenshots
LOGS: Canceled call received on the Android device where the call was not rejected.
![image](https://github.com/twilio/twilio-voice-react-native/assets/36927150/ffd76158-be2b-4b36-a3f3-2282712eb4bf)

LOGS: Call rejected on the IOS device where the call was rejected
![image](https://github.com/twilio/twilio-voice-react-native/assets/36927150/a414a91a-e1cb-4ac8-a61c-16784f9e9135)

## Software and Device Information
**Please complete the following information.**
-  Device: iPhone 13 Pro
- OS: IOS 16
- React version: 18.2.0
- React Native version: 0.72.4
- Node version: 16.20.2
- npm or yarn version: 8.19.4

**Comment by bobiechen-twilio** [comment]
Hi @dianamariand92 

Sorry it took us longer to respond. As you may have observed, this is the design of the Programmable Voice client - all clients with the same identity will ring and the incoming call ends (canceled) when the call is accepted or rejected by one of the clients.
There was actually a bug on the iOS side where the pending call invite map is not updated properly, which results in the call-invite-rejected event, although the correct status should be "canceled". This is the PR that fixed the bug: https://github.com/twilio/twilio-voice-react-native/pull/217.

-bobie

**Comment by dianamariand92** [comment]
Hi @bobiechen-twilio I don't understand why the call should terminate on all clients with the same identity if one of them rejects it. It should continue ringing the other clients because perhaps one of them can answer it.

**Comment by MykolaKobetiakCloudGenie** [comment]
> Hi @bobiechen-twilio I don't understand why the call should terminate on all clients with the same identity if one of them rejects it. It should continue ringing the other clients because perhaps one of them can answer it.

For something like this, you can create devices with different IDs and use sequential property for Parallel/Serial  calling

**Comment by dianamariand92** [comment]
Hi @bobiechen-twilio @MykolaKobetiakCloudGenie 

When an incoming call is received, Twilio only allows the call to be propagated to 10 IDs. I have an account with more than 10 subusers. When users log in to the web application the identifier is client:123456web for all users. Now when users log in to the mobile application the identifier is client:123456app. This allows me to have more than 10 users and for everyone to receive calls in the mobile and web applications. The problem is that the mobile application rejects the call for all users if one of them rejects the call, however, in the web application, this does not happen. In Twilio the status of the call with identifier client:123456app becomes Busy. In the case of the web application, the call continues Ringing even if one or more users reject the call.

I need to solve this problem. Thank you.

**Comment by MykolaKobetiakCloudGenie** [comment]
Hi @dianamariand92 , is the id for all mobile apps the same?

**Comment by dianamariand92** [comment]
@MykolaKobetiakCloudGenie  @bobiechen-twilio  Yes, it is. To clarify, in the web app I use the .ignore() function but in the mobile app, I don't have this function.

**Comment by MykolaKobetiakCloudGenie** [comment]
> @MykolaKobetiakCloudGenie @bobiechen-twilio Yes, it is. To clarify, in the web app I use the .ignore() function but in the mobile app, I don't have this function, and I use .reject() for the Call Invite when one of the users rejects the call.

there is .disconnect() on mobile app

I have just tested it with 2 devices with the same ID, the second one continues to ring after the call was rejected on another app. You can check your BE logic, maybe you are updating the call status to COMPLETED, and that's the reason why the call is disconnected.

**Comment by MykolaKobetiakCloudGenie** [comment]
> > > @MykolaKobetiakCloudGenie @bobiechen-twilio Yes, it is. To clarify, in the web app I use the .ignore() function but in the mobile app, I don't have this function, and I use .reject() for the Call Invite when one of the users rejects the call.
> > 
> > 
> > there is .disconnect() on mobile app
> > I have just tested it with 2 devices with the same ID, the second one continues to ring after the call was rejected on another app. You can check your BE logic, maybe you are updating the call status to COMPLETED, and that's the reason why the call is disconnected.
> 
> @MykolaKobetiakCloudGenie Did you use callInvite.reject() or did you use call.disconnect() in your test?

.reject()

**Comment by MykolaKobetiakCloudGenie** [comment]
> > > @MykolaKobetiakCloudGenie @bobiechen-twilio Yes, it is. To clarify, in the web app I use the .ignore() function but in the mobile app, I don't have this function, and I use .reject() for the Call Invite when one of the users rejects the call.
> > 
> > 
> > there is .disconnect() on mobile app
> > I have just tested it with 2 devices with the same ID, the second one continues to ring after the call was rejected on another app. You can check your BE logic, maybe you are updating the call status to COMPLETED, and that's the reason why the call is disconnected.
> 
> @MykolaKobetiakCloudGenie Did you use callInvite.reject() or did you use call.disconnect() in your test?

sorry, my bad, I have different ids: ios_123 and android_123. That's the reason why it is working. I already forgot about it...

**Comment by bobiechen-twilio** [comment]
@MykolaKobetiakCloudGenie I believe if the `invite.reject()` is called on one client, the rest of the mobile clients will all get canceled.

@dianamariand92 I am afraid this is the expected behavior. Technically you should be able to do nothing to the invite by not calling `reject()` or `accept()`. You might need a bit of CallKit end-call operation in the native iOS layer of the SDK so the incoming call UI can be dismissed to achieve the `.ignore()` equivalent.

**Comment by dianamariand92** [comment]
@MykolaKobetiakCloudGenie What version of the SDK are you using? I am using 1.0.0-beta3 and I see in Twilio Logs how the call is Busy when I reject the CallInvite. This is my code. I have a list of phones and if the user doesn't have the phone assigned I reject the call for that specific user. The callInvite.reject() function ends (stops ringing) the call for all the other users. 

`voice.on('callInvite', callInvite => {
      AsyncStorage.getItem('phones').then(phones => {
        phones = JSON.parse(phones);
        for (const i in phones) {
          if (callInvite._customParameters.call_to == phones[i]) {
            return;
          }
        }
        console.log('Rejecting Call');
        callInvite.reject();
      });
    });`

**Comment by dianamariand92** [comment]
> @MykolaKobetiakCloudGenie I believe if the `invite.reject()` is called on one client, the rest of the mobile clients will all get canceled.
> 
> @dianamariand92 I am afraid this is the expected behavior. Technically you should be able to do nothing to the invite by not calling `reject()` or `accept()`. You might need a bit of CallKit end-call operation in the native iOS layer of the SDK so the incoming call UI can be dismissed to achieve the `.ignore()` equivalent.

Ok @bobiechen-twilio thank you. I'll try to do some work on the SDK to achieve what I need.
