### ISSUE TITLE
"Registered"/"Unregistered" event not firing in iOS

### ISSUE THREAD

**Issue by periabyte** [twilio/twilio-voice-react-native#228]
# Issue

## Pre-submission Checklist
- [x] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
The event "registered" is not firing on iOS. But fires on Android version. I also checked the `TwilioVoiceReactNative.m` file but these are the only defined events

```swift
NSString * const kTwilioVoiceReactNativeEventKeyCall = @"call";
NSString * const kTwilioVoiceReactNativeEventKeyCallInvite = @"callInvite";
NSString * const kTwilioVoiceReactNativeEventKeyCancelledCallInvite = @"cancelledCallInvite";
```

## Reproduction Steps
in a component 

```jsx
import { Voice } from '@twilio/voice-react-native-sdk';

const voice = new Voice();
const Component = () => {
  useEffect(() => {
    voice.on(Voice.Event.Registered, (e) => {
      // this will show in android but not in iOS
      console.log("registered");
    });

    return () => {
      voice.removeAllListeners();
    };
  }, []);
  
  return <View />
}

export default Component;
```

## Expected Behavior
There should also be a "registered" or "unregistered" event for iOS

## Actual Behavior
Only Android receives the aforementioned events;

## Reproduction Frequency
100%

## Software and Device Information
**Please complete the following information.**
 - Device: iPhone 12 mini
 - OS: iOS 16
 - React version: 18.2.0
 - React Native version: 0.72.3
 - Node version: 16.15.0
 - npm or yarn version: 1.22.19

**Comment by mhuynh5757** [comment]
Hi @periabyte thanks for bringing this to our attention. I've filed a ticket to investigate this further.

**Comment by ErfanOrangetoolz** [comment]
Hi @mhuynh5757, Is there any update on this issue? I am also facing this issue.

**Comment by GuilhermeLessa** [comment]
@periabyte @ErfanOrangetoolz but are you calling the register method with token?

**Comment by kpchoy** [comment]
Please update to the latest version. Please open another issue if you are still experiencing this issue.
