### ISSUE TITLE
not to connect call call clicks only programmable voice hear not to connect the call

### ISSUE THREAD

**Issue by Nagoorkani27** [twilio/twilio-voice-react-native#229]
import { Call, Voice } from '@twilio/voice-react-native-sdk';

    const token = token;
    const voice = new Voice();

    // Allow incoming calls
    await voice.register(token);

    // Handle incoming calls
    voice.on('callInvite', (callInvite) => {
      callInvite.accept();
    });
    // setInterval(
    //   ()=> console.log(call.getState()) , 1000
    //   )
    // Make an outgoing call

   const params={PhoneNumber: "+918665642548",To:"+918665642548",From:"+12512203378",record: "true",'recipentType':'client'};
   const call= await voice.connect(token,params);
    console.log(call,"callllllllllllll")
    
    This is the Log
     {"_customParameters": {}, "_events": {"connected": {"context": [Circular], "fn": [Function anonymous], "once": false}}, "_eventsCount": 1, "_from": null, "_handleConnectFailureEvent": [Function anonymous], "_handleConnectedEvent": [Function anonymous], "_handleDisconnectedEvent": [Function anonymous], "_handleNativeEvent": [Function anonymous], "_handleQualityWarningsChangedEvent": [Function anonymous], "_handleReconnectedEvent": [Function anonymous], "_handleReconnectingEvent": [Function anonymous], "_handleRingingEvent": [Function anonymous], "_initialConnectedTimestamp": undefined, "_isMuted": undefined, "_isOnHold": undefined, "_nativeEventHandler": {"callEventConnectFailure": [Function anonymous], "callEventConnected": [Function anonymous], "callEventDisconnected": [Function anonymous], "callEventQualityWarningsChanged": [Function anonymous], "callEventReconnected": [Function anonymous], "callEventReconnecting": [Function anonymous], "callEventRinging": [Function anonymous]}, "_sid": null, "_state": "connecting", "_to": null, "_uuid": "8a70f9eb-6ce9-4efd-9c86-f6f78998ccdb"} callllllllllllll

Only hear Programmable Voice Demo account application error code

**Comment by mhuynh5757** [comment]
Hi @Nagoorkani27 thanks for reaching out. It seems like your TwiML may not be configured properly. Please check out this documentation to set up your Programmable Voice configurations: https://www.twilio.com/docs/voice/sdks

**Comment by Nagoorkani27** [comment]
call connected but how to end this call? customer side call end  call state is connected how to call end and get state? @mhuynh5757

**Comment by Nagoorkani27** [comment]
thanks @mhuynh5757

**Comment by Nagoorkani27** [comment]
hello @mhuynh5757 react native ios build not work not to connect call
