### ISSUE TITLE
Cannot read properties of undefined ( reading 'voice_register)

### ISSUE THREAD

**Issue by hamza153** [twilio/twilio-voice-react-native#235]
# Issue

## Pre-submission Checklist
- [x] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
I am trying to implement the library on RN for Android Platform by receiving the token from my backend service but every time I try registering my device with the received token, I receive the error saying "Cannot read properties of undefined ( reading 'voice_register) "

## Expected Behavior
The device should register with the given token and must be able to receive and make calls from there onwards.

## Actual Behavior
 I receive the error saying "Cannot read properties of undefined ( reading 'voice_register) "

## Screenshots
Attached is the screenshot of the error produced and the code snippet.

![WhatsApp Image 2023-10-06 at 02 41 02_8e83d828](https://github.com/twilio/twilio-voice-react-native/assets/40839974/a807c093-e37e-4f98-b129-f9423ff5aeff)
![WhatsApp Image 2023-10-06 at 02 41 49_4f0f87d5](https://github.com/twilio/twilio-voice-react-native/assets/40839974/241789fa-3c6d-4a2c-8acb-e406bd2ed436)

**Comment by ubaidrajputtmetastaq** [comment]
Have the same issue, please help guys. I am also unable to make it work on android physical device. Getting the same exact error. My job depends on this, please helppp.

**Comment by kpchoy** [comment]
hi @hamza153 I have ran the example app for this project and I am able to successfully register my android device. Have you tried setting up our example app in this repo: https://github.com/twilio/twilio-voice-react-native/tree/main/test/app ?

From your error it looks like you may be fetching the `accesstoken` incorrectly but it is hard to tell with the provided code snippet

**Comment by FoolCoder** [comment]
@kpchoy i am trying to implement this and i have the same issue
voice sdk code:
//token from api to create voice
const voice = new Voice(token);
  await voice.register();// this where i get the error

  voice.on('callInvite', callInvite => {
    callInvite.accept();
  });

  return voice;

**Comment by kpchoy** [comment]
@FoolCoder it seems like you are not fetching the `accessToken` correctly. Can you try fetching the token similar to the example in our API docs? https://www.twilio.com/docs/iam/access-tokens#create-an-access-token-for-voice
