### ISSUE TITLE
react native ios mute unmute not working 

### ISSUE THREAD

**Issue by dheerajgill25** [twilio/twilio-voice-react-native#241]
I am using this  "@twilio/voice-react-native-sdk": "1.0.0-beta.2", version when i hit the mute button its working in android but in ios it's not 
const handleMute = async () => {
    const call = callMap.get(String(activeCall?.id));
    const _isMute = await call?.mute(!isMuted);
    setIsMuted(Boolean(_isMute));
  };

**Comment by kpchoy** [comment]
Hi @dheerajgill25 can you try updating to "1.0.0-beta.3"? I think we may have fixed the mute button issue you are seeing. See our release notes: https://github.com/twilio/twilio-voice-react-native/releases

**Comment by dheerajgill25** [comment]
Thank you for your support @kpchoy
