### ISSUE TITLE
Short Playback of Custom `ringtone.wav` Before Transition from `RINGING` to `CONNECTED`

### ISSUE THREAD

**Issue by ggogobera** [twilio/twilio-voice-react-native#242]
# Question

## Pre-submission Checklist
- [x] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
I've been integrating the React Native Voice SDK into my app and have come across a potential user experience concern. I have successfully set a custom `ringtone.wav` as per the [documentation](https://github.com/twilio/twilio-voice-react-native/blob/main/docs/play-outgoing-call-ringback-tone.md). However, the behavior I'm observing is as follows:

1. Upon initiating a call, the `ringtone.wav` begins to play.
2. Almost immediately (within one second), the call state transitions from `RINGING` to `CONNECTED`, which stops the custom ringtone playback.
3. After this transition, there's a noticeable silence of about 6-7 seconds before the default carrier ringtone begins to play.

This flow is causing some confusion as I hear a brief snippet of our custom ringtone, followed by a prolonged silence, and then finally the default carrier ringtone.

### I'd like to inquire about the following:

**User Experience Improvement:** Is there a way to improve this experience? Ideally, I'd prefer to have the custom `ringtone.wav` play continuously until the carrier ringtone begins, or at least ensure that there isn't a prolonged silence between the two ringtones.

**Carrier Ringtone Prediction:** Is it technically feasible to predict or know when the default carrier ringtone will start? This information might help us better manage the transition between the custom ringtone and the default carrier ringtone.

This may be down to what a carrier does. I want to understand what the possibilities are to improve the UX given that you have the documentation about custom ringtones. Thanks!

## Software and Device Information
**Please complete the following information.**
 - Device: iPhone 15
 - OS: iOS 17
 - React version: 18.2.0
 - React Native version: 0.72.6
 - Node version: 18.14.0
 - npm version: 9.3.1

**Comment by bobiechen-twilio** [comment]
Hi @ggogobera 

There are a couple of moving parts involved here but from the SDK's perspective the behavior seems expected. Is it possible to provide Twilio Call SIDs so we can analyze both from the SDK and the signaling connection establishment?

-bobie

**Comment by ggogobera** [comment]
Thanks for chiming in!

I'll share the event lists for one of the conferences.

<details>
  <summary>Client to Twilio</summary>

|DATE (PDT) | EVENT|
| -- | --|
|2023-11-02 05:21:31 | signaling-state: have-local-offer|
|2023-11-02 05:21:31 | connection: outgoing|
|2023-11-02 05:21:31 | ice-gathering-state: gathering|
|2023-11-02 05:21:31 | ice-candidate: ice-candidate|
|2023-11-02 05:21:31 | ice-candidate: ice-candidate|
|2023-11-02 05:21:31 | ice-candidate: ice-candidate|
|2023-11-02 05:21:31 | ice-candidate: ice-candidate|
|2023-11-02 05:21:31 | ice-candidate: ice-candidate|
|2023-11-02 05:21:31 | ice-candidate: ice-candidate|
|2023-11-02 05:21:32 | settings: edge|
|2023-11-02 05:21:32 | connection: ringing|
|2023-11-02 05:21:32 | ice-candidate: ice-candidate|
|2023-11-02 05:21:33 | settings: codec|
|2023-11-02 05:21:33 | signaling-state: stable|
|2023-11-02 05:21:34 | ice-connection-state: checking|
|2023-11-02 05:21:34 | pc-connection-state: connecting|
|2023-11-02 05:21:34 | connection: accepted-by-remote|
|2023-11-02 05:21:34 | ice-candidate: selected-ice-candidate-pair|
|2023-11-02 05:21:34 | ice-gathering-state: complete|
|2023-11-02 05:21:34 | pc-connection-state: connected|
|2023-11-02 05:21:34 | connection: connected|
|2023-11-02 05:21:34 | ice-connection-state: connected|
|2023-11-02 05:21:34 | ice-connection-state: completed|
|2023-11-02 05:21:43 | audio-level-warning-raised: constant-audio-input-level|
|2023-11-02 05:22:07 | connection: disconnect-called|
|2023-11-02 05:22:07 | ice-connection-state: closed|
|2023-11-02 05:22:07 | pc-connection-state: closed|
|2023-11-02 05:22:07 | signaling-state: closed|
|2023-11-02 05:22:08 | connection: disconnected-by-local|
</details>

<details>
  <summary>Twilio → Recipient Carrier</b></summary>

|DATE (PDT) | EVENT|
|-- | --|
|2023-11-02 05:21:35 | connection: initiated|
|2023-11-02 05:21:48 | connection: ringing|

</details>

As you can see the call was initiated at `05:21:31`. The ringing started at `05:21:48`. 

So this comes down to a long delay between the call being initiated and the carrier tone heard. And it varies in the ~8-25 seconds range from call to call.

Currently, our app starts a timer immediately after a call is initiated. So imagine, you are making a call and hearing the first tone somewhere around the ~8-25 second mark. 

We considered [Play outgoing call ringback tone while waiting for the callee to answer the call](https://github.com/twilio/twilio-voice-react-native/blob/main/docs/play-outgoing-call-ringback-tone.md#play-outgoing-call-ringback-tone-while-waiting-for-the-callee-to-answer-the-call), but since the state switches from RINGING to CONNECTED almost immediately, it doesn't solve our issue.

I think it's best to start a timer once the callee answers the call.

**Comment by bobiechen-twilio** [comment]
Thanks for the update @ggogobera 

Since there is no Call SID so I cannot be sure what's been configured, but have you considered enabling the [answerOnBridge flag](https://www.twilio.com/docs/voice/twiml/dial#answeronbridge) in your <Dial> verb or Call API? By enabling this flag, the mobile client caller (first/parent call leg) will only receive the "connected" event when the call is answered by the other cal leg.

**Comment by ggogobera** [comment]
I've just sent the SIDs via email.

Since the status switched immediately to `CONNECTED` I assume the `answerOnBridge` flag was disabled. (Notably, [Play outgoing call ringback tone while waiting for the callee to answer the call](https://github.com/twilio/twilio-voice-react-native/blob/main/docs/play-outgoing-call-ringback-tone.md#play-outgoing-call-ringback-tone-while-waiting-for-the-callee-to-answer-the-call) says that the flag is enabled by default).

Does activating the `answerOnBridge` setting solely affect when the `connected` event is received? Or does it also shift the responsibility to the client app to manage the "busy" state, ringing, and other related functions?

**Comment by bobiechen-twilio** [comment]
Thanks @ggogobera, and indeed from the Call SID you provided the `answerOnBridge` flag is not enabled (which is the default value). There could be edge cases, especially when different carriers might have slightly different implementation, but generally with this flag enabled, the caller will only receive the connected event when the signaling and media connections are established and audio begin flowing in both directions. 

Other than the timing of getting the `connected` transition, your application/callback should continue to receive call state updates with the flag on.

Let me know if the behavior meets the expectation.

**Comment by ggogobera** [comment]
Since the default value is false, the doc needs updating. It was confusing seeing it say the default value is true. :)

All clear. Thanks for bearing with me!

I'll close this issue as I got all the answers.
