### ISSUE TITLE
CustomParameters are always empty

### ISSUE THREAD

**Issue by greenraze13** [twilio/twilio-voice-react-native#243]
I am using the exmple app that is in repo.
VOICE CALL IS WORKING FINE.

i am tryIng to send CustomParameters like 

 const connectHandler = React.useCallback(
    async (to: string, typeOfCall: string) => {
      const call = await voice.connect(token, {
        params: {
          recipientType: 'Phone',
          typeOfCall: typeOfCall,
          to: to,
          callerId: 'Absolute',
          From: 'client',
        Caller name : "JOHN"
        },
      });
      callHandler(call);
    },
    [callHandler, token, voice],
  );

but my  recentCallInvite  is  {"accept": [Function accept], "callSid": "xxxxxxxxxxx", "customParameters": {}, "from": "client:clientid", "reject": [Function reject], "to": "client:linguisticid"}

 
## Reproduction Steps
 [[twilio-voice-react-native](https://github.com/twilio/twilio-voice-react-native/app](https://github.com/twilio/twilio-voice-react-native/tree/main/test/app)]

## Expected Behavior
 Receiver  app should receive CustomParameters not empty object 

## Actual Behavior
 Receiver  app is showing   {"accept": [Function accept], "callSid": "xxxxxxxxxxx", "customParameters": {}, "from": "client:clientid", "reject": [Function reject], "to": "client:linguisticid"}

why "customParameters": {} 

 

## Software and Device Information
 Android to Android 
 "@twilio/voice-react-native-sdk": "^1.0.0-rc8",
    "react": "18.2.0",
    "react-native": "0.72.6",

**Comment by bobiechen-twilio** [comment]
Hi @greenraze13 

https://www.twilio.com/docs/voice/twiml/client#custom-parameters
The custom parameters are added as <Parameter> in the <Client> verb in the TwiML response returned from your TwiML app. Parameters from the SDK `connect()` methods will be included as request parameters to the URL of your TwiML webhook. The application has to determine what gets to be added to the custom parameters when the call is delivered to the receiver.
