### ISSUE TITLE
How to receive calls

### ISSUE THREAD

**Issue by prototypeninja** [twilio/twilio-voice-react-native#250]
Hi. Can someone describe to me how I can receive calls on my react native application? I tried voice.on('callInvite', (callInvite) => {
  callInvite.accept();
});

but I don't receive anything. I have already created the node js server that I use to receive and send calls with the javascript sdk. but with react native I don't get anything. If I can have a step to follow to set it up that would help me a lot please. I don't know if I should use firebase notification and if so then how to do it. just an example. THANKS

**Comment by prototypeninja** [comment]
Hi @bobiechen-twilio 
I'm using React-Native on Android.
the onRegistered event works. but I don't get an onCallInvite
I share with you my server code and my client code
`/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 */

import React,{useEffect, useState} from 'react';
import {
  
  Text,
  View,
} from 'react-native';
import { Voice } from '@twilio/voice-react-native-sdk';

function App() {

  const voice = new Voice();
    const [token, setToken] = useState('');
    const [identity, setIdentity] = useState('');

    const fetchToken = async () => {
        try {
            const userId = 'jean';
            const response = await fetch(`https://crm.locationedf.com/voip/app/token/?id=${userId}`);
            
            if (!response.ok) {
                throw new Error('Network response was not ok');
            }

            const data = await response.json();
            await voice.register(data.token);

            voice.on('callInvite', (callInvite) => {
              console.log(callInvite)
              // callInvite.accept();
            });




            setToken(data.token);
            setIdentity(data.identity);



        } catch (error) {
            console.error('There was a problem with the fetch operation:', error);
        }
    };

    useEffect(() => {
        fetchToken();
    }, []); 

   

    
    return (
        <View>
            <Text>Token: {token}</Text>
            <Text>Identity: {identity}</Text>
        </View>
    );
}


export default App;
`

when I call it rings but I have nothing in the callInvite console log

**Comment by bobiechen-twilio** [comment]
@prototypeninja 

Is it possible to provide us a Twilio Call SID where you experienced the problem?

**Comment by prototypeninja** [comment]
@bobiechen-twilio 

{
    'AccountSid': 'ACd814cee533f04af69c9a0bdbbda0b71d',
    'ApiVersion': '2010-04-01',
    'CallSid': 'CAb791552e7ec9aee2d48075ded8d0fa84',
    'CallStatus': 'ringing',
    'CallToken': '%7B%22parentCallInfoToken%22%3A%22eyJhbGciOiJFUzI1NiJ9.eyJjYWxsU2lkIjoiQ0FiNzkxNTUyZTdlYzlhZWUyZDQ4MDc1ZGVkOGQwZmE4NCIsImZyb20iOiIrMTQzNzc4MTQ1ODUiLCJ0byI6IisxNDM4Nzk4MDI4OCIsImlhdCI6IjE3MDEyMDk0MTMifQ.ibPFbYYu59FMD5kI64vNXFccZOEK2Z2MpIC9T9QdY50DAHc_Okg2W9ZW6QNcLQW9l1YtotAmvZ2K9npdrlWtsQ%22%2C%22identityHeaderTokens%22%3A%5B%5D%7D',
    'Called': '+14387980288',
    'CalledCity': '',
    'CalledCountry': 'CA',
    'CalledState': 'Quebec',
    'CalledZip': '',
    'Caller': '+14377814585',
    'CallerCity': 'Toronto',
    'CallerCountry': 'CA',
    'CallerState': 'Ontario',
    'CallerZip': '',
    'Direction': 'inbound',
    'From': '+14377814585',
    'FromCity': 'Toronto',
    'FromCountry': 'CA',
    'FromState': 'Ontario',
    'FromZip': '',
    'To': '+14387980288',
    'ToCity': '',
    'ToCountry': 'CA',
    'ToState': 'Quebec',
    'ToZip': ''
}




here is the information the server receives when I call the client

**Comment by bobiechen-twilio** [comment]
Thanks for providing the Call SID @prototypeninja.

The call that was made to the callee client actually encountered a push notification delivery error `52104 Mismatched GCM/FCM sender ID`. You might want to check the Firebase Cloud Messaging configuration. Also please let us know if you are seeing this error in your Twilio developer's console.

I also noticed that on the caller leg, we received a `500 Internal Server Error` response when sending updates to your status callback endpoint.

**Comment by prototypeninja** [comment]
hi @bobiechen-twilio 
Can you please describe to me the normal steps to configure Firebase and Twilio?

**Comment by bobiechen-twilio** [comment]
@prototypeninja I am not the Android expert but you can follow our Android SDK quickstart for your FCM setup: https://github.com/twilio/voice-quickstart-android#7-create-a-push-credential-using-your-fcm-server-key

**Comment by prototypeninja** [comment]
@bobiechen-twilio 
I followed this, and I didn't understand much. That’s even where I integrated Firebase into Twilio. However, it doesn't seem to work. Do you know anyone to recommend to me? It’s important to me and I can’t seem to make any progress.

**Comment by prototypeninja** [comment]
Good evening @bobiechen-twilio .
thank you for your help. I have done the various tests and configuration but I do not see 52104 Mismatched GCM/FCM sender ID in my console on twilio. And I still don't receive a call invitation

**Comment by prototypeninja** [comment]
@afalls-twilio 
If it's for changing the state of the call when it hangs up, it's normal that the api link returns a 500. I had to configure everything necessary regarding twilio, firebase, and other but nothing works I don't receive any calls on the react native application. I even gave the notification permissions on the application but nothing. whereas I had to develop a web application with the javascript sdk and everything works correctly there. but with react native I can make an outgoing call but an incoming call I don't even receive a log. yet it rings at the caller

**Comment by prototypeninja** [comment]
If you can do a little tutorial on how to do it on react native or an article that will help a lot. Just a simple application that makes and receives calls with react native and node js. Please especially describe the procedures on twilio related to notification with firebase and other if it has any

**Comment by afalls-twilio** [comment]
@prototypeninja place a break point in the `onMessageReceived(RemoteMessage remoteMessage)` in VoiceFirebaseMessagingService.java. Is it receiving a firebase message?

**Comment by prototypeninja** [comment]
@afalls-twilio Hello, I use react native. Can you tell me where I can find the java file you mentioned?

**Comment by khoa5773** [comment]
@afalls-twilio my app did not receive a firebase message. How can I fix that?

**Comment by kpchoy** [comment]
It seems the original issue has been stale. Please open a new issue if you are still experiencing problems.
