### ISSUE TITLE
Voice call is getting disconnected automatically

### ISSUE THREAD

**Issue by codal-hkrishnani** [twilio/twilio-voice-react-native#251]
Voice call is getting disconnected automatically

I have implemented this library for audio calls, and this is my code which i've written to initiate voice call.

```
 const connectHandler = React.useCallback(
    async (params: any) => {
      try {
        console.log('params =>>>>>', params);

        const call = await voice.connect(token, {
          params,
        });

        console.log('call =>>>>>', call, JSON.stringify(call));

        callHandler(call);
      } catch (error) {
        console.log('error:', error);
      }
    },
    [callHandler, token, voice],
  );
```
<img width="764" alt="Screenshot 2023-11-29 at 1 26 18 PM" src="https://github.com/twilio/twilio-voice-react-native/assets/78357231/f22a5fa8-1771-47b5-a3aa-dacca3097303">

As you can see in first console log, I am getting _state: "disconnected" and in second console which is in JSON.stringify _state: "connecting"

The issue I am facing is,
- call is disconnected immediately when I initiate the call

**Comment by bobiechen-twilio** [comment]
Hi @codal-hkrishnani 

From the Call SID in the screenshot, the call was disconnected by the local almost immediately after the call was made, i.e. `call.disconnect()` was called. Can you check if this is done by perhaps another event listener in the application?

**Comment by codal-hkrishnani** [comment]
@bobiechen-twilio - I am running it on simulator. And I tried running it on real device and what I found is i am getting this error?

_Error: Failed to initialize PushKit device token_

**Comment by bobiechen-twilio** [comment]
Hi @codal-hkrishnani 

Looks like the PushKit is not properly set up for the iOS app. Please follow our Programmable Voice [iOS SDK quickstart README](https://github.com/twilio/voice-quickstart-ios#bullet6) to set up and configure the Apple VoIP service for your application.

And no, you don't need to do the Apple VoIP setup and call `Voice.register()` if all you need (for now) is just making outbound calls from the mobile client.

**Comment by rajeevCs** [comment]
Hi @codal-hkrishnani 
is your issue solved or it persist, I am also having that same, issue, whenever I try to initiate a call from ios, the call is initiated and immediately disconnected .as of now I only need to place the call.

**Comment by codal-hkrishnani** [comment]
Yes @rajeevCs, my issue is resolved what issue was that I was calling voice.register() method which was not required and I was calling that. second this I was initialising call from simulator. So make sure you are initialising call from real device only

**Comment by mhuynh5757** [comment]
Hi all, thanks for the community discussion. Yes, unfortunately our library does not work on a simulator, this is expected and there is nothing that we can do about it. This is a limitation imposed by Apple. I'm going to close this issue, as it seems the original problem has been solved.
