### ISSUE TITLE
[IOS] can't disconnect the call of voice.getCalls() list

### ISSUE THREAD

**Issue by congkhanh24** [twilio/twilio-voice-react-native#252]
can't disconnect the call of voice.getCalls() list on IOS

i was call `call.disconnect()` but the call not disconnect
Do we have an end all call function to foreclose all of the calls?

Hi @bobiechen-twilio help me resolve it. Thanks!

**Comment by bobiechen-twilio** [comment]
@congkhanh24 please provide debugging logs from the Xcode debugger.

**Comment by congkhanh24** [comment]
when I was killing app ios, I had an incoming call -> I clicked accept in call kit ui -> my app open and i used `voice.getCalls()`  function to init the calls but when i click the button on my app to disconnect the call, it doesn't work.

I didn't have debugging logs because when i kill app ios it doesn't logs in Xcode

**Comment by bobiechen-twilio** [comment]
Hi @congkhanh24 

- Are you able to open the .xcodeproj or .xcworkspace and run the app with Xcode debugger attached?
- Is it possible to print out the `Call` returned from `voice.getCalls()`? does it have a valid UUID?
- Do you get any error when you try to call `call.disconnect()`?
- Also when you say "killing app iOS", what exactly are you trying to do?

**Comment by congkhanh24** [comment]
Hi @bobiechen-twilio
1. I able to open Xcode debugger but my case is killed app -> app state is killed and I click accept in callkit UI my app is open. At that time i didn't see new logs
2. Yes, i received the calls from `voice.getCalls()`
3. When I call function call.disconnect() i didn't see any error. It only happend on IOS, android work fine

**Comment by bobiechen-twilio** [comment]
Thanks for the update.
To attach the debugger in this case, you can follow [this guide](https://developer.apple.com/documentation/xcode/customizing-the-build-schemes-for-a-project) and update the scheme so it starts the debug session when the app is launched by the incoming call push notification.
<img width="774" alt="Screenshot 2023-11-29 at 8 59 51 PM" src="https://github.com/twilio/twilio-voice-react-native/assets/16326574/8fc25826-2a36-4eb9-9d34-d20fbaf5138b">

**Comment by congkhanh24** [comment]
<img width="531" alt="Screenshot 2023-12-06 at 11 19 54" src="https://github.com/twilio/twilio-voice-react-native/assets/74224788/4eaa9e67-5c2b-4746-ac0c-3e73bfe5d5b2">
Hi @bobiechen-twilio. This is logs a see when I call disconnect function

**Comment by bobiechen-twilio** [comment]
Thanks @congkhanh24. From the log it does show that the end-call request submitted from the iOS SDK to the iOS CallKit framework failed due to the invalid UUID. 

If you haven't, could you please try the example app (under the `test/app` folder) in the RN SDK repo and see if you are still getting this error?

**Comment by bobiechen-twilio** [comment]
Hi @congkhanh24 

Thanks for the update. I am still able to successfully accept and disconnect the call using the example app under `test/app`. (the app was terminated and re-launched by the incoming call notification)

Can you print out the UUID of the calls, both when you are accepting and disconnecting?

**Comment by bobiechen-twilio** [comment]
Are you seeing any error messages in the debugger when you call this method?

**Comment by congkhanh24** [comment]
<img width="408" alt="Screenshot 2023-12-08 at 10 59 43" src="https://github.com/twilio/twilio-voice-react-native/assets/74224788/ba87feea-ab31-4e76-8cb4-0a7d2e35dd11">
<img width="649" alt="Screenshot 2023-12-08 at 10 59 54" src="https://github.com/twilio/twilio-voice-react-native/assets/74224788/8aae4e0a-eff2-43be-ac54-0c871c144dd4">

It doesn't log from SDK, it just logs in my js code. Can you try `test/app folder` with my issue?

**Comment by kpchoy** [comment]
Closing this for now, please open another issue if you are still experiencing the problem
