### ISSUE TITLE
Call QualityWarningsChanged event data always undefined. 

### ISSUE THREAD

**Issue by traxx10** [twilio/twilio-voice-react-native#254]
# Issue

## Pre-submission Checklist
- [x] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
Hello and thanks for the beta. I am listening for a call event *QualityWarningsChanged* when making an outgoing call, the event is fired but there is no data returned by this event. According to the api docs, i should be getting one of those events but i get undefined instead.

![Screenshot 2023-11-30 at 6 58 31 AM](https://github.com/twilio/twilio-voice-react-native/assets/31565764/0da48e69-9517-41bc-b694-34dca84d328a)

## Reproduction Steps
1. Make an outgoing call
2. Listen for *QualityWarningsChanged* event
3. Console log event and you will see undefined.

## Expected Behavior
The network quality event should be returned
![Screenshot 2023-11-30 at 6 58 31 AM](https://github.com/twilio/twilio-voice-react-native/assets/31565764/0da48e69-9517-41bc-b694-34dca84d328a)

## Actual Behavior
I get undefined when i log the data

## Reproduction Frequency
Always

## Software and Device Information
**Please complete the following information.**
 - Device: [e.g. iPhone 12, Pixel 3]
 - OS: [e.g. iOS 16, Android API Level 31]
 - React version: [e.g. 18.1.0]
 - React Native version: [e.g. 0.70.9]
 - Node version: [e.g. 16.18.1]
 - npm or yarn version: [e.g. 8.19.2, 1.22.19]

**Comment by mhuynh5757** [comment]
Hi @traxx10 thanks for the detailed bug report. I've filed a ticket to track this internally, we really appreciate the thorough details on your issue!

**Comment by mhuynh5757** [comment]
Hi @traxx10 we have released `1.0.0` and the product is now GA. Please update to the latest version at your earliest convenience. Thank you for your patience and for helping us by filing this ticket, we really appreciate the feedback!
