### ISSUE TITLE
App killed android Voice call Notification callkeep issue.

### ISSUE THREAD

**Issue by kirit-codal** [twilio/twilio-voice-react-native#257]
Hi,

I have implemented the library according to the documentation and working fine for iOS, In Android I need to call when the App is killed/Background, So there is a fire in the notification but I don't see the callkeep. is there already implementation in it. Can you help me how to integrate the call notification for android? 

Code : 

```
 const bootstrap = async () => {
      if (Platform.OS === 'ios') {
        await voice.initializePushRegistry();
      } else {
        const options = {
          ios: {
            appName: 'My app name',
          },
          android: {
            alertTitle: 'Permissions required',
            alertDescription:
              'This application needs to access your phone accounts',
            cancelButton: 'Cancel',
            okButton: 'ok',
            additionalPermissions: [
              PermissionsAndroid.PERMISSIONS.READ_PHONE_STATE,
            ],
            selfManaged: true,
            foregroundService: {
              channelId: 'com.app.grollsø',
              channelName: 'Foreground service for my app',
              notificationTitle: 'My app is running on background',
              notificationIcon: 'Path to the resource icon of the notification',
            },
          },
        };

        RNCallKeep.setup(options).then(accepted => {
          console.log('accepted', accepted);
        });
        RNCallKeep.registerPhoneAccount(options);
        RNCallKeep.registerAndroidEvents();
        RNCallKeep.setAvailable(true);

        RNCallKeep.addEventListener('didReceiveStartCallAction', ({handle}) => {
          console.log('didReceiveStartCallAction', handle);
        });
        RNCallKeep.addEventListener(
          'didDisplayIncomingCall',
          ({callUUID, handle, fromPushKit}) => {
            console.log('didDisplayIncomingCall', callUUID);
          },
        );
      }
```

**Comment by bobiechen-twilio** [comment]
Hi @kirit-codal 

Thanks for reaching out. The Voice React Native SDK does not have the CallKeep package integrated. Please you can follow our [example app](https://github.com/twilio/twilio-voice-react-native/tree/main/test/app) or the [SDK reference app](https://github.com/twilio/twilio-voice-react-native-app) for incoming call integration.

**Comment by afalls-twilio** [comment]
@kirit-codal That is due to the priority of the notification, if you look [here](https://github.com/twilio/twilio-voice-react-native/blob/7a476cf71e0d671cb7004d66e6b305bb4598454a/android/src/main/java/com/twiliovoicereactnative/IncomingCallNotificationService.java#L225) you can see that the notification is created with normal priority, if you can change the code, change the priority to HIGH and the notification will pop up.

**Comment by kirit-codal** [comment]
@afalls-twilio Thanks it's working for me, I add the patch for now. update this one in your next release.

**Comment by kirit-codal** [comment]
it's working according to your suggestion.
