### ISSUE TITLE
[IOS] The app crashes when creating a call on iPhone 13 Pro Max(iOS 16.6.1)

### ISSUE THREAD

**Issue by Andrew-Koniushiy** [twilio/twilio-voice-react-native#260]
# Issue

## Description 
Hi.
The app crashes when creating a call on iPhone 13 Pro Max(iOS 16.6.1)
We have stacktrace from the tester in the screenshot.
Log: TwilioVoice: -[TVOConnectOptions coreOptionsWithMediaFactory:callMessageObserver:] + 664

It works on other devices: iPhone 11(iOS 16.3.1) and iPhone 6s(iOS 15)

## Reproduction Steps
1. just creating a call 

## Expected Behavior
the app shouldn't crash

## Actual Behavior
the app crashes

## Reproduction Frequency
replays every time

## Screenshots
<img width="883" alt="Screen Shot 2023-12-20 at 22 38 00" src="https://github.com/twilio/twilio-voice-react-native/assets/3028511/05e1d207-63e0-4dd0-b8ab-660136bafe69">

## Software and Device Information
System:
    OS: macOS 12.7.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 34.25 MB / 16.00 GB
    Shell: 5.2.15 - /usr/local/bin/bash
  Binaries:
    Node: 18.14.0 - /usr/local/bin/node
    Yarn: 1.22.21 - ~/Projects/react_projects/go-coaching/go-coaching/Server/node_modules/.bin/yarn
    npm: 9.3.1 - /usr/local/bin/npm
    Watchman: 2023.02.13.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.14.3 - /Users/andrew/.rvm/gems/ruby-2.7.4/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild

**Comment by bobiechen-twilio** [comment]
Hi @Andrew-Koniushiy 

Thanks for reaching out and providing the crash stacktrace. Could you please check the value (don't paste directly in the reply) of the `token` when calling the `Voice.connect()` method?

**Comment by kpchoy** [comment]
Hi @Andrew-Koniushiy please open another issue if you are still experiencing this problem. Will close for now.
