### ISSUE TITLE
Expo Support

### ISSUE THREAD

**Issue by Elue-dev** [twilio/twilio-voice-react-native#263]
Not an issue but a question, does this library support react native apps built with Expo?

**Comment by mhuynh5757** [comment]
Hi all, our team here at Twilio has not tested the library with Expo, but we have seen some users attempt to integrate the library with Expo. Please see this related issue for discussion regarding Expo: https://github.com/twilio/twilio-voice-react-native/issues/132

**Comment by Elue-dev** [comment]
> Hi all, our team here at Twilio has not tested the library with Expo, but we have seen some users attempt to integrate the library with Expo. Please see this related issue for discussion regarding Expo: #132

thank you, helpful
