### ISSUE TITLE
No tones are generated in the application when using the sendDigits function

### ISSUE THREAD

**Issue by dianamariand92** [twilio/twilio-voice-react-native#267]
# Issue

## Pre-submission Checklist
- [ x] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
You do not hear tones when you press the digits and send the digits with the sendDigits function.

## Reproduction Steps
 1. After establishing a call, use the sendDigits function to send DTMF digits.

## Expected Behavior
1. Listen to the tones when you press the digits.

## Actual Behavior
You do not hear tones when you press the digits and send the digits with the sendDigits function.

## Reproduction Frequency
100%

## Software and Device Information
**Please complete the following information.**
 - Device: Iphone 13 Pro
 - OS: IOS 15
 - React Native version: 0.72.4
 - Node version: 24.4.0
 - npm: 10.2.4

**Comment by mhuynh5757** [comment]
Hi @dianamariand92 thanks for reaching out. I will discuss with the team the scope of this feature request. This is by design at the moment and not a bug.

**Comment by dwbelliston** [comment]
For closure, is this still unplanned work?

**Comment by imthepitts** [comment]
Hello everyone 👋🏻 Zack here, product manager for Twilio Voice SDK. We don't have current plans for audible DTMF tones in the mobile SDKs. However, this is achievable by adding some logic to your app to play DTMF audio files locally, similar to our JavaScript SDK.

You can download the DTMF sound files from this [source](https://www.twilio.com/docs/voice/sdks/javascript/twiliodevice#deviceoptionssounds-properties-and-default-sounds) and play them from your app. The logic for playing these sounds can be handled via a player, such as [react-native-sound-player](https://www.npmjs.com/package/react-native-sound-player).
