### ISSUE TITLE
CustomParameters are always empty on Android if call was answered using Push notification

### ISSUE THREAD

**Issue by MykolaKobetiakCloudGenie** [twilio/twilio-voice-react-native#268]
I am trading to get CustomParameters from const calls = await voice.getCalls(); after the call was answered using push notification. On Android, it is empty all the time.

Steps: Kill the app, and make an inbound call to the app. Answer the call using the Answer button on Push Notification. 
On Registered event listener try to get the calls list using await voice.getCalls();, after forEach call from list try to get CustomParameters. They are empty.

Device: Pixel 7
"@twilio/voice-react-native-sdk": "1.0.0-rc8",
"react-native": "0.72.6"

**Comment by afalls-twilio** [comment]
@MykolaKobetiakCloudGenie  thank you for reporting this issue. This bug will be fixed in the next release.

**Comment by MykolaKobetiakCloudGenie** [comment]
Thanks for a quick answer @afalls-twilio . Do you have any estimates of when the fix can be released?

**Comment by MykolaKobetiakCloudGenie** [comment]
@afalls-twilio Hi there, could share some estimates of when you are planning to release this fix? For us, this bug is critical it is affecting our production customers.

**Comment by mhuynh5757** [comment]
Hi @MykolaKobetiakCloudGenie, apologies but we do not have a timeline for this yet. But please rest assured that we are aware of the issue and working to get the fix out as soon as possible.

**Comment by MykolaKobetiakCloudGenie** [comment]
@mhuynh5757 Thank you very much for the clarification!

**Comment by mhuynh5757** [comment]
Hi @MykolaKobetiakCloudGenie we have released `1.0.0` and the product is now GA. Please update at your earliest convenience, thank you for your patience! This issue has been addressed in the `1.0.0` release.
