### ISSUE TITLE
How to set Incoming ringtone?

### ISSUE THREAD

**Issue by tim-acst** [twilio/twilio-voice-react-native#270]
At least on Android, the notification sound just loops a standard beep, which is quite aggravating. Is there a simple way to override what sound is used on incoming notification / call? It would also be nice to change iOS, but Android is the most pressing at the moment. Thanks!

**Comment by afalls-twilio** [comment]
@tim-acst it would require a code change but you can replace the ringtone sounds in the sdk.. they are [here](https://github.com/twilio/twilio-voice-react-native/tree/main/android/src/main/res/raw)

**Comment by tim-acst** [comment]
I'm wondering if something's wrong with my setup. On Android, I don't get a ringtone at all. It's just a repeating Android ding sound. Is it maybe some sort of permissions issue?

**Comment by kpchoy** [comment]
Hi @tim-acst are you still experiencing this issue? Please use the latest version of the sdk and open another issue if you still experience the issue. Will close for now.
