### ISSUE TITLE
[21218] Invalid sid application

### ISSUE THREAD

**Issue by mondeee** [twilio/twilio-voice-react-native#275]
any solution to this, which doesnt make sense if i have inavalid applicationSid then i should not be able to create accessToken at all. i tried 3 diff twilio accounts on this but i get the same error when initating a call check my code snippet below
"You attempted to initiate an outbound phone call with an invalid ApplicationSid. The application may not exist anymore or may not be available within your account."

```
  const outgoingCallResult = await voice.connect(token, {params: { to: '+13XXXXXXX}});
  ```

after this i get "connecting" status.
then it goes to my listener "ConnectFailure" 
```
  outgoingCallResult.on(Call.Event.ConnectFailure, (error) =>
        console.error('ConnectFailure:', error),
      );
```
which returns this
`ConnectFailure: [InvalidApplicationSid: InvalidApplicationSid (21218): Invalid ApplicationSid]`

also all of this implementation is based from the sampleapp

**Comment by mondeee** [comment]
also this actions is not being added to the call logs from twilio console, any idea what i did wrong

**Comment by MykolaKobetiakCloudGenie** [comment]
@mondeee Hi there, not sure why you see this error message, but you can check your Twilio credentials on the BE side, probably something wrong there. Also connect should include the access token and params with To: +13xxxxxxx, and From: your Twilio number.

**Comment by mondeee** [comment]
> @mondeee Hi there, not sure why you see this error message, but you can check your Twilio credentials on the BE side, probably something wrong there. Also connect should include the access token and params with To: +13xxxxxxx, and From: your Twilio number.

i didnt see any "From" param in the example app https://github.com/twilio/twilio-voice-react-native-app, will try to do so. i think im missing a config also from the twilio console

**Comment by mondeee** [comment]
this was issue to twiML app not being setup and twiML sid is needed. but how do you guys setup the backend for requestURL of twilio voice

**Comment by mhuynh5757** [comment]
Hi @mondeee, I am glad to see that you were able to resolve your token issue. As for the backend setup, that is unfortunately out of the scope of this Issue Board. Please see this documentation on TwiML for further help. Please feel free to reach out to Twilio support for further help.

https://www.twilio.com/docs/voice/twiml
