### ISSUE TITLE
How can I establish a connection with the incoming call to my Twilio number?

### ISSUE THREAD

**Issue by magedov** [twilio/twilio-voice-react-native#279]
# Issue

## Pre-submission Checklist
- [x] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 

When my verified Twilio account number is called, the incoming information is as follows:
{
  "Called": "",
  "ToState": "",
  "CallerCountry": "",
  "Direction": "inbound",
  "CallerState": "",
  "ToZip": "",
  "CallSid": "",
  "To": "",
  "CallerZip": "",
  "ToCountry": "",
  "CallToken": "",
  "CalledZip": "",
  "ApiVersion": "",
  "CalledCity": "",
  "CallStatus": "",
  "From": "",
  "AccountSid": "",
  "CalledCountry": "",
  "CallerCity": "",
  "ApplicationSid": "",
  "ToCity": "",
  "FromCountry": "",
  "Caller": "",
  "FromCity": "",
  "CalledState": "",
  "FromZip": "",
  "FromState": ""
}

How can I communicate with the caller when my Twilio number is called? What should be the code on the server side? When I use the following code, a new call is initiated. I don't understand how to establish a relationship with the incoming call.

const call = await client.api.calls.create({
  url: "",
  to: 'client:',
  from: "",
}).catch(e => console.log("call err", e));
Could you guide me on how to handle the incoming call and communicate with the caller on the server side?

**Comment by mhuynh5757** [comment]
Hi @magedov, thanks for reaching out. Unfortunately this question is a bit of scope of this repo's Issues page, but let me try to point you in the right direction.

Please check out the Twilio Programmable Voice docs here: https://www.twilio.com/docs/voice

You will want to configure the handlers on your phone number within the Twilio console. Please consider reaching out to Twilio's official support if you are interested in further assistance. Thanks!
