### ISSUE TITLE
Android build getting failed in ^1.0.0-beta.4

### ISSUE THREAD

**Issue by Buwaneka-Sumanasekara** [twilio/twilio-voice-react-native#281]
# Issue

## Pre-submission Checklist
- [*] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [ *] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [ *] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 

Android build failed after installed  "@twilio/voice-react-native-sdk": "^1.0.0-beta.4" version. But ios build working fine

## Reproduction Steps
1. install  "@twilio/voice-react-native-sdk": "^1.0.0-beta.4", package
2. Run android project by using yarn android 

## Expected Behavior
Project should be open in the device without faile
<img width="702" alt="Screenshot 2024-01-23 at 22 05 27" src="https://github.com/twilio/twilio-voice-react-native/assets/17542497/35834689-6cba-4acc-94a6-514d20ac14d0">
d

## Actual Behavior
Android Project getting failed with following logs

```
BUILD FAILED in 1m 10s

    at makeError (/Users/buwaneka/Projects/Gotradie/org/gt-mobileapp/node_modules/execa/index.js:174:9)
    at /Users/buwaneka/Projects/Gotradie/org/gt-mobileapp/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/buwaneka/Projects/Gotradie/org/gt-mobileapp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/buwaneka/Projects/Gotradie/org/gt-mobileapp/node_modules/@react-native-community/cli/build/index.js:142:9)
```

Note: I'm using Mac m1 (running on rossetta 2)

Here is the build gradle file SDK versions  and ndk versions

```
  buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
        kotlinVersion = "1.6.10"

        if (System.properties['os.arch'] == "aarch64") {
            // For M1 Users we need to use the NDK 24 which added support for aarch64
            ndkVersion = "24.0.8215888"
        } else {
            // Otherwise we default to the side-by-side NDK version from AGP.
            ndkVersion = "21.4.7075529"
        }
    }

```

React versions are
```

"react": "18.1.0",
"react-native": "0.70.9",
```

**Comment by mhuynh5757** [comment]
Hi @Buwaneka-Sumanasekara thanks for reaching out. Have you been able to compile and run an Android React Native application in the past? Also, have you been using our SDK and prior versions and been able to compile with former versions?

**Comment by mhuynh5757** [comment]
Hi @Buwaneka-Sumanasekara I'm going to close this issue as stale for now, please feel free to reach out if you need further assistance.
