### ISSUE TITLE
Android incoming call push notification in dark mode 

### ISSUE THREAD

**Issue by dianamariand92** [twilio/twilio-voice-react-native#282]
# Issue

## Pre-submission Checklist
- [ x] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [ x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [x ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
Push notifications for incoming calls do not show the caller's name when the phone (android) is in dark mode. Also, the incoming call sound is like any other notification.

## Reproduction Steps
1. Incoming call.

## Expected Behavior
Display the caller's name in white and make a sound similar to the phone tone when receiving the call.

## Actual Behavior
The incoming call sounds like a notification and in dark mode the caller name appears black and cannot be read

## Reproduction Frequency
100%

## Screenshots
![1706046254579](https://github.com/twilio/twilio-voice-react-native/assets/36927150/ca18bec7-5566-46b2-8875-0a3041419ee8)

## Software and Device Information
**Please complete the following information.**
 - Device: Samsung Galaxy S24
 - OS: Android
 - React version: 18.2.0
 - React Native version: 0.72.4
 - Node version: 20.10.0
 - npm or yarn version: 10.2.3

**Comment by afalls-twilio** [comment]
@dianamariand92  thanks for reporting the issue, yeah, we are currently not changing the coloring due to darkmode, so the test is black and the system set the background to black, causing the text to 'disappear'.

**Comment by dianamariand92** [comment]
Hi @afalls-twilio thanks I was able to resolve the issue by adding this function in Notification Utility.java  file 

`  private static boolean isDarkModeEnabled(Context context) {
    int nightModeFlags = context.getResources().getConfiguration().uiMode & Configuration.UI_MODE_NIGHT_MASK;
    return nightModeFlags == Configuration.UI_MODE_NIGHT_YES;
  }` and then in the notification builder 

`int titleTextColor = isDarkModeEnabled(context) ? Color.WHITE : Color.BLACK;
remoteViews.setTextColor(R.id.notif_title, titleTextColor);
`

I hope you add these changes in the next release. 
Thank you,

**Comment by afalls-twilio** [comment]
@dianamariand92  Thanks for info. FYI: in the next release we will be using the system call notifications.
