### ISSUE TITLE
Error Urgent: VoiceApplicationProxy error after updating the Library to latest version 

### ISSUE THREAD

**Issue by dianamariand92** [twilio/twilio-voice-react-native#285]
# Issue

## Pre-submission Checklist
- [x ] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [x ] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [x ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
After updating the SDK to the latest version "@twilio/voice-react-native-sdk": "^1.0.0-beta.4", I am getting the error 
![image](https://github.com/twilio/twilio-voice-react-native/assets/36927150/0a217bdd-74d1-4fb4-bd57-c66b8117ebf6)

## Reproduction Steps
1. Update to the latest version of the app and try to run the application in Android Studio. 

## Expected Behavior
No getting any error

## Actual Behavior
![image](https://github.com/twilio/twilio-voice-react-native/assets/36927150/0a217bdd-74d1-4fb4-bd57-c66b8117ebf6)

## Reproduction Frequency
100%

## Screenshots
![image](https://github.com/twilio/twilio-voice-react-native/assets/36927150/0a217bdd-74d1-4fb4-bd57-c66b8117ebf6)
![image](https://github.com/twilio/twilio-voice-react-native/assets/36927150/fb3751a7-719c-4a07-9cdf-01d389291837)

## Software and Device Information
**Please complete the following information.**
 - Device: Pixel 3a API 34
 - OS: Android
 {
  "name": "ProspectX",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest",
    "postinstall": "patch-package",
    "setup-ios": "npx react-native setup-ios-permissions && cd ios && pod install",
    "debug-build-android": "react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/ && cd android && ./gradlew assembleDebug && cd ..",
    "release-build-android": "cd android && ./gradlew bundleRelease && cd .."
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.19.2",
    "@react-native-firebase/app": "^18.3.0",
    "@react-native-firebase/messaging": "^18.3.0",
    "@react-navigation/bottom-tabs": "^6.5.8",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.13",
    "@twilio/voice-react-native-sdk": "^1.0.0-beta.4",
    "@twotalltotems/react-native-otp-input": "^1.3.11",
    "axios": "^1.4.0",
    "libphonenumbers": "^1.3.0",
    "moment": "^2.29.4",
    "numeral": "^2.0.6",
    "patch-package": "^8.0.0",
    "react": "18.2.0",
    "react-native": "0.72.4",
    "react-native-calendar-picker": "^7.1.4",
    "react-native-document-picker": "^8.2.1",
    "react-native-dropdown-picker": "^5.4.6",
    "react-native-file-viewer": "^2.1.5",
    "react-native-fs": "^2.20.0",
    "react-native-gifted-chat": "^2.4.0",
    "react-native-image-picker": "^5.6.1",
    "react-native-linear-gradient": "^2.8.2",
    "react-native-paper": "^5.10.3",
    "react-native-permissions": "^3.8.4",
    "react-native-raw-bottom-sheet": "^2.2.0",
    "react-native-render-html": "^6.3.4",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-safe-area-context": "^4.7.1",
    "react-native-screens": "^3.29.0",
    "react-native-simple-dialogs": "^2.0.1",
    "react-native-svg": "^13.12.0",
    "react-native-svg-transformer": "^1.1.0",
    "react-native-toast-message": "^2.1.6",
    "react-native-track-player": "^4.0.1-nightly-47b2d08033563ef4d7e76a7f061c244ac3dba1ec",
    "react-redux": "^8.1.2",
    "redux": "^4.2.1",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.4.2"
  },
  "reactNativePermissionsIOS": [
    "Camera",
    "Microphone",
    "PhotoLibrary",
    "Notifications",
    "MediaLibrary"
  ],
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/eslint-config": "^0.72.2",
    "@react-native/metro-config": "^0.72.11",
    "@tsconfig/react-native": "^3.0.0",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.76.8",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "twilio": "^4.14.0"
  },
  "engines": {
    "node": ">=16"
  }
}
- node: 20.10.0
 - npm or yarn version: 10.2.3

**Comment by dianamariand92** [comment]
I used "@twilio/voice-react-native-sdk": "^1.0.0-beta.3" and everything worked fine. I saw the changes in the latest reference app and there are many things that I don't see in my MainActivity.java and MainApplication.java. Also, a lot of things related to Firebase and IncomingCallNotificationUi were removed from Manifest.xml. Please you need to provide a step-by-step document to migrate from one version to another because you are also fixing bugs that we need.

**Comment by a2mta** [comment]
faced the exact same problem, downgrade on beta3 helped 


![IMAGE 2024-01-28 13:13:54](https://github.com/twilio/twilio-voice-react-native/assets/4593732/1449dd49-4840-499d-b7d3-d7590f7d16ab)

**Comment by mhuynh5757** [comment]
Hi all, thanks for reaching out. We've refactored the Android native helpers in the library to make it easier for developers to integrate the library into their applications. Please take a look at this document for a usage guide:

https://github.com/twilio/twilio-voice-react-native/blob/main/docs/migration-guide-beta.4.md

For further reference, please see the Reference App and the native Android code that is needed:

https://github.com/twilio/twilio-voice-react-native-app/tree/main/app/android/app/src/main/java/com/twiliovoicereactnativereferenceapp

**Comment by traxx10** [comment]
> Hi all, thanks for reaching out. We've refactored the Android native helpers in the library to make it easier for developers to integrate the library into their applications. Please take a look at this document for a usage guide:
> 
> https://github.com/twilio/twilio-voice-react-native/blob/main/docs/migration-guide-beta.4.md
> 
> For further reference, please see the Reference App and the native Android code that is needed:
> 
> https://github.com/twilio/twilio-voice-react-native-app/tree/main/app/android/app/src/main/java/com/twiliovoicereactnativereferenceapp

Not everyone is proficient with the steps outlined on the link, i struggled so much with this on Kotlin since my app is on the latest version of react native. The reference app is based on java as well and not Kotlin.

**Comment by afalls-twilio** [comment]
@traxx10 @dianamariand92 ok,  the changes were to make integration easier, regardless of it being in kotlin or java, there should be less things to change now... so lets start 1 step at a time... 
1) can you share with me your AndroidManifest.xml, and your Kotlin or java files that contain the ReactNative Activity binding and the React Native Applicaiton binding (Application.java & Acitivy.java)?

**Comment by dianamariand92** [comment]
Hi @afalls-twilio  I had to downgrade to beta.3, these are the files you mention.

**AndroidManifest.xml**
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
package="com.prospectx">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.Manifest.permission.RECORD_AUDIO" />
    
    <uses-permission android:name="android.permission.USE_FULL_SCREEN_INTENT" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.DISABLE_KEYGUARD" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    
    <uses-permission android:name="android.permission.BIND_TELECOM_CONNECTION_SERVICE"/>
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.CALL_PHONE" />
    <uses-permission android:name="android.permission.READ_CONTACTS" />
    <uses-permission android:name="android.permission.READ_PHONE_NUMBERS" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION" />
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />
    

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|screenSize|smallestScreenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize"
        android:exported="true">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>     
      
      
      <service android:name="com.twiliovoicereactnative.VoiceFirebaseMessagingService" android:stopWithTask="false" android:exported="true">
        <intent-filter>
          <action android:name="com.google.firebase.MESSAGING_EVENT" />
        </intent-filter>
      </service>
      <service android:enabled="true" android:name="com.twiliovoicereactnative.IncomingCallNotificationService" android:foregroundServiceType="microphone" android:exported="true">
        <intent-filter>
          <action android:name="ACTION_ACCEPT" />
          <action android:name="ACTION_REJECT" />
        </intent-filter>
      </service>
      <activity
        android:name="com.twiliovoicereactnative.NotificationProxyActivity"
        android:parentActivityName=".MainActivity"
        android:noHistory="true"
        android:excludeFromRecents="true"
        android:taskAffinity=""
        android:launchMode="singleTask"
        android:theme="@android:style/Theme.Translucent.NoTitleBar"
        android:exported="true" />  
    </application>
</manifest>
`

**MainActivity.java** 

`package com.prospectx;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint;
import com.facebook.react.defaults.DefaultReactActivityDelegate;

public class MainActivity extends ReactActivity {

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
    return "ProspectX";
  }

  /**
   * Returns the instance of the {@link ReactActivityDelegate}. Here we use a util class {@link
   * DefaultReactActivityDelegate} which allows you to easily enable Fabric and Concurrent React
   * (aka React 18) with two boolean flags.
   */
  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new DefaultReactActivityDelegate(
        this,
        getMainComponentName(),
        // If you opted-in for the New Architecture, we enable the Fabric Renderer.
        DefaultNewArchitectureEntryPoint.getFabricEnabled());
  }
}
`

**MainApplication.java**


`package com.prospectx;

import android.app.Application;
import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint;
import com.facebook.react.defaults.DefaultReactNativeHost;
import com.facebook.soloader.SoLoader;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost =
      new DefaultReactNativeHost(this) {
        @Override
        public boolean getUseDeveloperSupport() {
          return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          // Packages that cannot be autolinked yet can be added manually here, for example:
          // packages.add(new MyReactNativePackage());
          return packages;
        }

        @Override
        protected String getJSMainModuleName() {
          return "index";
        }

        @Override
        protected boolean isNewArchEnabled() {
          return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
        }

        @Override
        protected Boolean isHermesEnabled() {
          return BuildConfig.IS_HERMES_ENABLED;
        }
      };

  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
      // If you opted-in for the New Architecture, we load the native entry point for this app.
      DefaultNewArchitectureEntryPoint.load();
    }
    ReactNativeFlipper.initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
  }
}
`

**Comment by afalls-twilio** [comment]
@dianamariand92 so here is how you would change it for beta.4

**_AndroidManifest.xml_**
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.prospectx">
<uses-permission android:name="android.permission.DISABLE_KEYGUARD" />
<uses-permission android:name="android.permission.BIND_TELECOM_CONNECTION_SERVICE"/>
<uses-permission android:name="android.permission.READ_PHONE_STATE" />
<uses-permission android:name="android.permission.CALL_PHONE" />
<uses-permission android:name="android.permission.READ_CONTACTS" />
<uses-permission android:name="android.permission.READ_PHONE_NUMBERS" />
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION" />


<application
  android:name=".MainApplication"
  android:label="@string/app_name"
  android:icon="@mipmap/ic_launcher"
  android:roundIcon="@mipmap/ic_launcher_round"
  android:allowBackup="false"
  android:theme="@style/AppTheme">
  <activity
    android:name=".MainActivity"
    android:label="@string/app_name"
    android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|screenSize|smallestScreenSize|uiMode"
    android:launchMode="singleTask"
    android:windowSoftInputMode="adjustResize"
    android:exported="true">
    <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
    </intent-filter>
  </activity>     
</application>
```
_**MainActivity.java**_
```
package com.prospectx;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint;
import com.facebook.react.defaults.DefaultReactActivityDelegate;

public class MainActivity extends ReactActivity {

  private final VoiceActivityProxy activityProxy = new VoiceActivityProxy(
    this,
    permission -> {
      if (Manifest.permission.RECORD_AUDIO.equals(permission)) {
        Toast.makeText(
          MainActivity.this,
          "Microphone permissions needed. Please allow in your application settings.",
          Toast.LENGTH_LONG).show();
      } else if ((Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) &&
        Manifest.permission.BLUETOOTH_CONNECT.equals(permission)) {
          Toast.makeText(
            MainActivity.this,
            "Bluetooth permissions needed. Please allow in your application settings.",
            Toast.LENGTH_LONG).show();
      } else if ((Build.VERSION.SDK_INT > Build.VERSION_CODES.S_V2) &&
        Manifest.permission.POST_NOTIFICATIONS.equals(permission)) {
          Toast.makeText(
            MainActivity.this,
            "Notification permissions needed. Please allow in your application settings.",
            Toast.LENGTH_LONG).show();
      }
    });
  
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    activityProxy.onCreate(savedInstanceState);
  }

  @Override
  public void onDestroy() {
    activityProxy.onDestroy();
    super.onDestroy();
  }

  @Override
  public void onNewIntent(Intent intent) {
    super.onNewIntent(intent);
    activityProxy.onNewIntent(intent);
  }
  @Override
  protected String getMainComponentName() {
    return "ProspectX";
  }
}
```
_**MainApplication.java**_
```
package com.prospectx;

import android.app.Application;
import com.facebook.react.PackageList;
import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint;
import com.facebook.react.defaults.DefaultReactNativeHost;
import com.facebook.soloader.SoLoader;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {
  private final VoiceApplicationProxy voiceApplicationProxy;
  private final MainReactNativeHost mReactNativeHost;
  

  public MainApplication() {
    super();
    mReactNativeHost = new MainReactNativeHost(this);
    voiceApplicationProxy = new VoiceApplicationProxy(mReactNativeHost);
  }
  
  @Override
  public ReactNativeHost getReactNativeHost() {
    return mReactNativeHost;
  }

  @Override
  public void onCreate() {
    super.onCreate();
    voiceApplicationProxy.onCreate();
    SoLoader.init(this, /* native exopackage */ false);
    // Remove the following line if you don't want Flipper enabled
    initializeFlipper(this, getReactNativeHost().getReactInstanceManager());
  }

  @Override
  public void onTerminate() {
    // Note: this method is not called when running on device, devies just kill the process.
    voiceApplicationProxy.onTerminate();
    super.onTerminate();
  }
}
```

_**MainReactNativeHost.java**_
```
package com.prospectx;

import android.app.Application;

import com.facebook.react.PackageList;
import com.facebook.react.ReactPackage;
import com.twiliovoicereactnative.VoiceApplicationProxy;

import java.util.List;

public class MainReactNativeHost extends VoiceApplicationProxy.VoiceReactNativeHost {
  public MainReactNativeHost(Application application) {
    super(application);
  }
  @Override
  public boolean getUseDeveloperSupport() {
    return BuildConfig.DEBUG;
  }
  @Override
  protected List<ReactPackage> getPackages() {
    List<ReactPackage> packages = new PackageList(this).getPackages();
    packages.addAll(super.getPackages());
    // Packages that cannot be autolinked yet can be added manually here
    // packages.add(new MyReactNativePackage());
    return packages;
  }
  @Override
  protected String getJSMainModuleName() {
    return "index";
  }
}
```

Now, I don't have a way of testing it because I don't have your application but hopefully this will give you enough info to get the idea. you can also look at the demo app in the SDK [here](https://github.com/twilio/twilio-voice-react-native/tree/main/test/app/android/app/src/main/java/com/example/twiliovoicereactnative) as an example.

**Comment by dianamariand92** [comment]
@afalls-twilio Thank you so much. I'll check it and comment here if it works.

**Comment by dmitriy-uvin** [comment]
Hi @afalls-twilio, what changes are required for IOS? Is it enough to install only package for it?

**Comment by dmitriy-uvin** [comment]
@dianamariand92 any updates?

**Comment by himanshupkarak** [comment]
@afalls-twilio I have changed those file as you suggested, But now i am getting this error

[
<img width="339" alt="Screenshot 2024-02-05 at 6 05 20 PM" src="https://github.com/twilio/twilio-voice-react-native/assets/105435093/d0a9fc5e-6ba3-4f8c-829f-164ebff986f3">
](url)

**Comment by dianamariand92** [comment]
@afalls-twilio I have the same error as @himanshupkarak 
![image](https://github.com/twilio/twilio-voice-react-native/assets/36927150/39fd1a21-5351-42d9-84e2-6a7734c9e818)

**Comment by dmitriy-uvin** [comment]
@himanshupkarak and @dianamariand92
That problem is fixable, try to investigate your .java files, review https://github.com/dmitriy-uvin/mobile-dialpad, there is Kotlin but the logic is the same.

**Comment by himanshupkarak** [comment]
@dianamariand92 have you tried?

@dmitriy-uvin I made a new react native project which has kotlin files (*not java) and updated those 3 files as mentioned here ->  https://github.com/dmitriy-uvin/mobile-dialpad

- I also checked my package.json and androidmenifest files, everything looks fine to me but still getting this error in terminal

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

**Comment by dmitriy-uvin** [comment]
This is not all log message. Please provide the full one.

**Comment by himanshupkarak** [comment]
ok will provide.

I also clone your suggested repo and here i got another error message
<img width="339" alt="Screenshot 2024-02-05 at 10 54 24 PM" src="https://github.com/twilio/twilio-voice-react-native/assets/105435093/4bfd07b4-63b6-4fd9-a399-395a1709fb8b">

can you help on this?

**Comment by dmitriy-uvin** [comment]
I didn't tell you to clone it, but just to review how to solve your issue. I don't know how to solve issue in my repo. That is why I am here.

**Comment by afalls-twilio** [comment]
@dmitriy-uvin  As for iOS, I don't think there was a refactor of that platform, @bobiechen-twilio would know better though.

**Comment by dmitriy-uvin** [comment]
@afalls-twilio Hi, about the error "Unable to start..." That exactly when everything that needed is started, npm run start and then, from terminal npm run android (or press "a" in previously launched "npm run start").

Are these changes enough to have it working properly (MainActivity, MainApplication, MainReactNativeHost)?

**Comment by afalls-twilio** [comment]
@dmitriy-uvin did you run `adb reverse tcp:8081 tcp:8081`?

**Comment by dmitriy-uvin** [comment]
@afalls-twilio Nah, doesn't work

**Comment by afalls-twilio** [comment]
@dmitriy-uvin no, there should be no issue with kotlin vs java, in fact they both get translated to the same thing, java byte code.

**Comment by dmitriy-uvin** [comment]
@afalls-twilio thank you for your help, I don't fully understand how, but my app is running now after command
```
npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
```
I run it, deleted assets, rerun it and it works.

**Comment by dmitriy-uvin** [comment]
Do you have any Twilio communitiy - Slack, Discord, etc? So developers who trying to integrate with twilio can help each other. If not, do you think it makes sense to create it?

**Comment by himanshupkarak** [comment]
thankyou @afalls-twilio it works fine now

**Comment by dianamariand92** [comment]
@afalls-twilio It works for me too.

**Comment by dianamariand92** [comment]
Hi @afalls-twilio. After changing the files you told me the app works (without error) in Android, but I am not receiving the notification of the incoming call. Do you think there is something else I should add to the files you send me? I am receiving the info of the call through Firebase, but the SDK doesn't fire the notification of the incoming call. In beta3 was working fine.

**Comment by dianamariand92** [comment]
@afalls-twilio The only way I got the notification was by adding this code in the AndroidManifest.xml

`<service android:name="com.twiliovoicereactnative.VoiceFirebaseMessagingService" android:stopWithTask="false" android:exported="true">
    <intent-filter>
      <action android:name="com.google.firebase.MESSAGING_EVENT" />
    </intent-filter>
  </service>`

I believed this was no longer necessary. Maybe I'm missing something.

**Comment by himanshupkarak** [comment]
@dianamariand92 have you completed these steps?

## Incoming call notifications

### Android

On Android platforms, the Twilio Voice Android SDK uses Firebase Cloud Messaging (FCM) to deliver call notifications to users. FCM requires a `google-services.json` file that can be generated in a Firebase project. Once the `google-services.json` file is generated, it must be placed in the `app/android/app` folder before any Android build can be completed.

See the Twilio Voice Android SDK [Quickstart](https://github.com/twilio/voice-quickstart-android#bullet1) for more information.

**Comment by dianamariand92** [comment]
@himanshupkarak Hi, thank you for your help. Yes, I have the google-services.json file. 
![image](https://github.com/twilio/twilio-voice-react-native/assets/36927150/d37d0ec8-f404-4315-996c-0af97c0cc0c6)
