### ISSUE TITLE
not working with expo  android

### ISSUE THREAD

**Issue by GaganJatana55** [twilio/twilio-voice-react-native#286]
<img width="315" alt="Screenshot 2024-01-29 at 12 17 34 PM" src="https://github.com/twilio/twilio-voice-react-native/assets/104757856/e90abebf-8826-456e-98c0-2cdd57bde7f7">
after adding dependency getting this error , the package is available in node modules, can anyone tell something about this, i need it for making calls only not receiving yet.

the package.json is 
{
  "name": "zing-app-ui",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "pods": "cd example && pod-install --quiet",
    "test:eslint": "echo \"\\033[33mRunning eslint check\" &&  eslint .",
    "test:tsc": "echo \"\\033[33mRunning typescript check\" && tsc"
  },
  "dependencies": {
    "@babel/plugin-proposal-export-namespace-from": "^7.18.9",
    "@dietime/react-native-date-picker": "^1.2.1",
    "@expo/webpack-config": "~18.0.1",
    "@fanchenbao/react-native-scroll-indicator": "^0.2.1",
    "@pdftron/webviewer": "^8.12.1",
    "@react-native-async-storage/async-storage": "1.17.11",
    "@react-native-community/netinfo": "9.3.7",
    "@react-native-community/slider": "4.4.2",
    "@react-native/metro-config": "^0.73.2",
    "@twilio/video-processors": "^2.0.0",
    "@twilio/voice-react-native-sdk": "^1.0.0-beta.4",
    "@twilio/voice-sdk": "^2.7.1",
    "axios": "^1.4.0",
    "dayjs": "^1.11.9",
    "expo": "~48.0.21",
    "expo-auth-session": "~4.0.3",
    "expo-av": "~13.2.1",
    "expo-constants": "~14.2.1",
    "expo-crypto": "~12.2.1",
    "expo-document-picker": "~11.5.4",
    "expo-file-system": "~15.2.2",
    "expo-font": "~11.1.1",
    "expo-image-picker": "~14.1.1",
    "expo-linear-gradient": "~12.1.2",
    "expo-linking": "~4.0.1",
    "expo-router": "^1.0.0",
    "expo-splash-screen": "~0.18.2",
    "expo-status-bar": "~1.4.4",
    "formik": "^2.4.2",
    "i18next": "^23.5.1",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "moment-timezone": "^0.5.43",
    "nativewind": "^2.0.11",
    "pod-install": "^0.1.39",
    "pusher-js": "^8.3.0",
    "qs": "^6.11.2",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-dropzone": "^14.2.3",
    "react-file-picker": "^0.0.6",
    "react-i18next": "^13.2.1",
    "react-native": "0.71.14",
    "react-native-big-calendar": "^4.5.0",
    "react-native-calendars": "^1.1300.0",
    "react-native-collapsible": "^1.6.1",
    "react-native-date-picker": "^4.3.3",
    "react-native-device-info": "^10.11.0",
    "react-native-document-picker": "^4.3.0",
    "react-native-draggable": "^3.3.0",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-gridview": "^0.1.2",
    "react-native-indicators": "^0.17.0",
    "react-native-pager-view": "6.1.2",
    "react-native-popable": "^0.4.3",
    "react-native-popover-view": "^5.1.8",
    "react-native-reanimated": "2.17.0",
    "react-native-reanimated-carousel": "^3.5.1",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "react-native-simple-radio-button": "^2.7.4",
    "react-native-tab-view": "^3.5.2",
    "react-native-toast-message": "^2.1.6",
    "react-native-twilio-video-webrtc": "^3.2.0",
    "react-native-web": "~0.18.10",
    "react-outside-click-handler": "^1.3.0",
    "react-phone-number-input": "^3.3.7",
    "react-timer-hook": "^3.0.7",
    "rn-country-dropdown-picker": "^2.1.8",
    "slugify": "^1.6.6",
    "twilio": "^4.15.0",
    "twilio-video": "^2.27.0",
    "twrnc": "^3.6.4",
    "use-file-picker": "^2.1.1",
    "usehooks-ts": "^2.9.1",
    "yup": "^1.2.0",
    "zustand": "^4.3.9"
  },
  "devDependencies": {
    "@babel/core": "^7.20.2",
    "@types/react": "~18.0.27",
    "@types/react-native": "^0.72.2",
    "@typescript-eslint/eslint-plugin": "^5.60.1",
    "@typescript-eslint/parser": "^5.60.1",
    "autoprefixer": "^10.4.14",
    "eslint": "^8.43.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-config-universe": "^11.2.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-react": "^7.32.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "postcss": "^8.4.26",
    "postcss-loader": "^4.2.0",
    "prettier": "^2.8.8",
    "prettier-plugin-tailwindcss": "^0.3.0",
    "react-native-dotenv": "^3.4.9",
    "tailwindcss": "3.3.2",
    "typescript": "^4.9.4"
  },
  "overrides": {
    "metro": "0.76.0",
    "metro-resolver": "0.76.0"
  },
  "private": true,
  "volta": {
    "node": "14.21.3"
  },
  "engines": {
    "node": "14.21.1"
  },
  "resolutions": {
    "@babel/core": "^7.20.2",
    "babel-loader": "^8.3.0"
  }
}

**Comment by GaganJatana55** [comment]
main application voice proxy was not intialized

**Comment by dianamariand92** [comment]
@GaganJatana55 Could you tell me how you initialized it? I have the same error.

**Comment by GaganJatana55** [comment]
> @GaganJatana55 Could you tell me how you initialized it? I have the same error.

check the reference app  you will find the  files under android folder  main activity and other

**Comment by amitava82** [comment]
There needs to be a clear instructions how to integrate with existing project. When readme file says npm install package then people expect it to work without any other modifications.
