### ISSUE TITLE
Urgent: For two days now, incoming calling with the app in the background or disabled does not work on iOS 17.

### ISSUE THREAD

**Issue by dianamariand92** [twilio/twilio-voice-react-native#293]
# Issue

## Pre-submission Checklist
- [ x] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [ x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [ x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
For two days now, incoming calling with the app in the background or disabled does not work on iOS 17.

## Reproduction Steps
1. Receiving an incoming call.

## Expected Behavior
Show the incoming call.

## Actual Behavior
Does not show the incoming call on the phone when the application is in background or killed. If the call is received when the application is open.

## Reproduction Frequency
100%

## Software and Device Information
**Please complete the following information.**
 - Device: iPhone 13 pro
 - OS: iOS 17.3
 {
  "name": "ProspectX",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest",
    "postinstall": "patch-package",
    "setup-ios": "npx react-native setup-ios-permissions && cd ios && pod install",
    "debug-build-android": "react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/ && cd android && ./gradlew assembleDebug && cd ..",
    "release-build-android": "cd android && ./gradlew bundleRelease && cd .."
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.19.2",
    "@react-native-firebase/app": "^18.3.0",
    "@react-native-firebase/messaging": "^18.3.0",
    "@react-navigation/bottom-tabs": "^6.5.8",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.13",
    "@twilio/voice-react-native-sdk": "^1.0.0-beta.3",
    "@twotalltotems/react-native-otp-input": "^1.3.11",
    "axios": "^1.4.0",
    "libphonenumbers": "^1.3.0",
    "moment": "^2.29.4",
    "numeral": "^2.0.6",
    "patch-package": "^8.0.0",
    "react": "18.2.0",
    "react-native": "0.72.4",
    "react-native-calendar-picker": "^7.1.4",
    "react-native-document-picker": "^8.2.1",
    "react-native-dropdown-picker": "^5.4.6",
    "react-native-file-viewer": "^2.1.5",
    "react-native-fs": "^2.20.0",
    "react-native-gifted-chat": "^2.4.0",
    "react-native-image-picker": "^5.0.2",
    "react-native-linear-gradient": "^2.8.2",
    "react-native-paper": "^5.10.3",
    "react-native-permissions": "^3.8.4",
    "react-native-raw-bottom-sheet": "^2.2.0",
    "react-native-render-html": "^6.3.4",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-safe-area-context": "^4.7.1",
    "react-native-screens": "^3.24.0",
    "react-native-simple-dialogs": "^2.0.1",
    "react-native-svg": "^13.12.0",
    "react-native-svg-transformer": "^1.1.0",
    "react-native-toast-message": "^2.1.6",
    "react-native-track-player": "^4.0.1-nightly-47b2d08033563ef4d7e76a7f061c244ac3dba1ec",
    "react-redux": "^8.1.2",
    "redux": "^4.2.1",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.4.2"
  },
  "reactNativePermissionsIOS": [
    "Camera",
    "Microphone",
    "PhotoLibrary",
    "Notifications",
    "MediaLibrary"
  ],
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/eslint-config": "^0.72.2",
    "@react-native/metro-config": "^0.72.11",
    "@tsconfig/react-native": "^3.0.0",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.76.8",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0"
  },
  "engines": {
    "node": ">=16"
  }
}

**Comment by bobiechen-twilio** [comment]
Hi @dianamariand92 can you provide a Call SID when this is happening? although the fact that your app can receive call notification when the app is active indicates there should be no issue related to push notification delivery.

I've just tried the app on iOS 17 and was able to get the call notification when the app is backgrounded or terminated.

Do you see any information in the Xcode debugger? typically this could be due to application not reporting the VoIP push notification to CallKit new incoming call in a timely manner (and iOS might terminate your app with an exception) or when the app is on focus/do-no-disturb mode, which would result in an error when the SDK is reporting the call to iOS CallKit.

-bobie

**Comment by dianamariand92** [comment]
Hi @bobiechen-twilio thanks for your help. I am using apn package (https://www.npmjs.com/package/apn)  with the following code to simulate an incoming call.

`
const apn = require('apn');

// Configure APN credentials
const options = {
    key: '/Users/diananaranjo/Work/Projects/APN/voip-key-px-dev-rsa.pem', // Path to the APNs authentication key
    cert: '/Users/diananaranjo/Work/Projects/APN/voip-cert-px-dev.pem', // Path to the APNs authentication key
    production: false // Set to true if sending push notifications to production environment
};

const apnProvider = new apn.Provider(options);

// Create a new notification
const notification = new apn.Notification();
notification.alert = 'VoIP APN Testing!';
notification.payload = {
    twi_account_sid: "ACd03be974b9fd7d4e47b2ec78781420e9",
    twi_answer_timeout: "600",
    twi_call_sid: "CA6528d621be8c4bc583521dd4d2b73423",
    twi_from: "+13526182752",
    twi_message_id: "RU409eafa24909dee8da3cb941550f217c",
    twi_params: "call_sid=CAe637650cd92a747a8ee04d9c4e16306a&call_to=%2B13526182752",
    twi_stir_status: "TN-Validation-Passed-A",
    twi_to: "client:cb027839app",
    twi_bridge_token: "eyJ6aXAiOiJERUYiLCJjdHkiOiJ0d2lsaW8tZnBhO3Y9MSIsImVuYyI6IkEyNTZHQ00iLCJhbGciOiJkaXIiLCJ0d3IiOiJ1czEiLCJraWQiOiJTQVNfUzNfX19LTVNfdjEifQ..2f0phLKzI40bYYPY.0Nkid-pfRGrj355oXsKmpt-aahUSWycV1YhgxLS3Yfv6JW3Mo6jJfvEa355wI84EMH9rG70MNxSMrhZnWnJ0EXBUN5ZdsVgrBZ2ODxrGheLu0fjP-wKlQ-ZM7jztymSNMpWRzCFy9zEVf-Dk6FxAsV2zYdAaMj3zTV3zTojOKPX6fWHgdlKSzpHfceAb8H8pQLHYJmiTrIWN_fa84ppfIt8hMUpoL4HKNNNI1ix0QYVpanPLWP8aSNeGE2riOha3d14r3SvLKRPnBE5zwoNUuqInm1tsmmbcdNuyCbAMFLwvyX3o77emzOLdBF7hym8voYuJZXcAHuBEBj97HOmRy17LEwTx1tWdkoukKob7Blhx-e3J733E2h1azdt9XF-ojlDOBb-jwSP2VrI3vB81kz7oHZh_nsrEuZfEXOx-BuPKYznZZRzsg8040Uj506nXHEkCVprqZy6CdRF0cF1Hnzfnokhgay8_e1EIqEojKGgHm_WGNf4NyJljvSkqsqVx__2DNEE1JxYoLh2X.LYteiGkM5x7PBvwkngzmvg",
    twi_message_type: "twilio.voice.call",
    twi_from: "+13526182752",
    twi_to: "client:cb027839app",
    from: "451334629226",
    messageId: "0:1677516526495808%064013f2f9fd7ecd",
    sentTime: 1677516526465,
    ttl: 600
}; // Set the payload

// Set the device token (obtained from the device)
const deviceToken = ['9623541e957350f0f36ad7dcf2ea77cc85e06d036a422d589b8f3de35858965f'];
notification.topic = 'com.prospectx.app.voip';

// Send the notification
apnProvider.send(notification, deviceToken).then((result) => {
    // Check the result for any failed devices
    console.log(result)
    for (const key in result) {
        if (result[key].length > 0) {
            for (const i in result[key]) {
                if (key == 'failed') {
                    console.log('Status:', result[key][i].status)
                    console.log('Device ID:', result[key][i].device)
                    console.log('Response:', result[key][i].response);
                } else {
                    console.log(result[key][i]);
                }
            }
        }
    }
    process.exit(0);
});`

When I run this code with the app open, I get the notification and the logs are shown in XCode (see screenshots), but when the app is in the background I don't get anything, not even in the XCode logs.

![image](https://github.com/twilio/twilio-voice-react-native/assets/36927150/1392430a-1795-4d3b-9824-91c018846269)
![WhatsApp Image 2024-01-31 at 16 32 13](https://github.com/twilio/twilio-voice-react-native/assets/36927150/a72a0854-3306-49e3-878b-d4ab1c37c026)



**Podfile**

`# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
'require.resolve(
"react-native/scripts/react_native_pods.rb",
{paths: [process.argv[1]]},
)', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
# dependencies: {
# ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
use_frameworks! :linkage => linkage.to_sym
end

target 'ProspectX' do
config = use_native_modules!

use_frameworks! :linkage => :static
use_modular_headers!
$RNFirebaseAsStaticFramework = true

# Flags change depending on the env values.
flags = get_default_flags()

use_react_native!(
:path => config[:reactNativePath],
# Hermes is now enabled by default. Disable by setting this flag to false.
:hermes_enabled => flags[:hermes_enabled],
:fabric_enabled => flags[:fabric_enabled],
# Enables Flipper.
#
# Note that if you have use_frameworks! enabled, Flipper will not work and
# you should disable the next line.
# :flipper_configuration => flipper_config,
# An absolute path to your application root.
:app_path => "#{Pod::Config.instance.installation_root}/.."
)

pod 'RNFS', :path => '../node_modules/react-native-fs'

target 'ProspectXTests' do
inherit! :complete
# Pods for testing
end

post_install do |installer|
# https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
installer.pods_project.build_configurations.each do |config|
config.build_settings["CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES"] = true
end
installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
    config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
  end
end
react_native_post_install(
installer,
config[:reactNativePath],
:mac_catalyst_enabled => false
)
__apply_Xcode_12_5_M1_post_install_workaround(installer)
end
end`

**AppDelegate.mm**

`#import "AppDelegate.h"
#import <Firebase.h>

#import <React/RCTBundleURLProvider.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  self.moduleName = @"ProspectX";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  // Add me --- \/
  [FIRApp configure];
  // Add me --- /\
  // ...
  self.initialProps = @{};

  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end
`





Thank you very much for the help.

**Comment by bobiechen-twilio** [comment]
Hi @dianamariand92 

The iOS native layer of the React Native SDK by default has a PushKit handler to initialize and handle incoming push notifications. All the application needs to do is calling the `Voice.initializePushRegistry()` if you want the SDK to handle these for you.

Since you are using your own iOS APN library, please check out this doc and make sure you pass the push notification payload to the SDK so the SDK can report the incoming call to iOS CallKit and also establish the connection: https://github.com/twilio/twilio-voice-react-native/blob/main/docs/applications-own-pushkit-handler.md

**Comment by dianamariand92** [comment]
Hi @bobiechen-twilio I am calling voice.initializePushRegistry(); in my initTwilio function. The APN library is just for testing, I am using twilio numbers.  I don't know why but is working now. Thanks for your help.
