### ISSUE TITLE
Create full documentation for setting up Twilio in the new project

### ISSUE THREAD

**Issue by dmitriy-uvin** [twilio/twilio-voice-react-native#295]
# Issue

## Pre-submission Checklist
- [x] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
In the installation instructions, there is no word about android/ios changes that need to be made only executing of npm command.

## Expected Behavior
Following the clean steps of installation any developer can receive fully-functional Twilio integration in React Native app.

## Actual Behavior
In the documentation there is only only instruction - npm install, but no other related to android/ios setup.

**Comment by amitava82** [comment]
I'm not sure why this is closed. README file still have npm install.

**Comment by mhuynh5757** [comment]
Hi all, I'd like to help out by making our documentation as useful as possible for everyone. Can you please elaborate on what our README file is lacking? We have a usage snippet underneath the installation instructions, but perhaps that is not sufficient?

**Comment by mhuynh5757** [comment]
We've also recently added the RN SDK to the official Twilio docs here:
https://www.twilio.com/docs/voice/sdks/react-native/getting-started-with-the-voice-react-native-sdk

Please reach out and feel free to re-open this issue if those docs do not suffice.

**Comment by amitava82** [comment]
@mhuynh5757 I believe the doc is incomplete. In the readme file it says for installation: 
```
yarn add @twilio/voice-react-native-sdk
```
And then it tells us how to initialize the Voice sdk and use it. 

What I've found is, only installing the module is not enough, some of the native code (in case of Android, files under android folder) has to be changed too for it to be usable. All these instructions are missing. Users are being asked to look into Reference app which isn't helpful.

Please update readme file with exact changes user has to make in order to use this library.

**Comment by ilyagru** [comment]
+1 to @amitava82. The current docs are not helpful and I have to do my own research to figure out how to integrate it into a new app.
