### ISSUE TITLE
Microphone permission is granted for android, But still voice is not audible on other side

### ISSUE THREAD

**Issue by himanshupkarak** [twilio/twilio-voice-react-native#297]
# Issue
Microphone permission is granted for android, But still voice is not audible on other side
## Pre-submission Checklist
- I have sdk version  1.0.0-beta.3 
- I am not sharing any [Personally Identifiable Information or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
- when i make call or .accept() any incoming call, My microphone is not working on androind (permission is granted) (not tested this on IOS yet.)
- I hear only a beeeep sound (during whole tiime of call).

## Reproduction Steps
1. execute voice.connect() to make a call
2. now i can hear caller voice, but one on the other side  can not

## Expected Behavior
My voice should be audible on other side too

## Actual Behavior
voice is not audible on other side, only can hear i continues beeeeeep sound

## Reproduction Frequency
100%

## Screenshots
can not take a screen shot of this issue (related to voice)

## Software and Device Information
**Please complete the following information.**
 - Device: [Pixel 4] emulator (also tested on real device (oppo - android 13 and samsung - don't know))
 - OS: [ Android 13 API Level 33]
 - React version: [18.2.0]
 - React Native version: [0.73.2]
 - Node version: [18.18.2]
 - npm version: [9.8.1]

## Additional Context
I am sharing AndroidManifest.xml file here :

<manifest xmlns:android="http://schemas.android.com/apk/res/android">

<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.RECORD_AUDIO" />
<uses-permission android:name="android.Manifest.permission.RECORD_AUDIO" />

<uses-permission android:name="android.permission.USE_FULL_SCREEN_INTENT" />
<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
<uses-permission android:name="android.permission.DISABLE_KEYGUARD" />
<uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />

<uses-permission android:name="android.permission.BIND_TELECOM_CONNECTION_SERVICE"/>
<uses-permission android:name="android.permission.READ_PHONE_STATE" />
<uses-permission android:name="android.permission.CALL_PHONE" />
<uses-permission android:name="android.permission.READ_CONTACTS" />
<uses-permission android:name="android.permission.READ_PHONE_NUMBERS" />
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.ACCESS_MEDIA_LOCATION" />
<uses-permission android:name="android.permission.POST_NOTIFICATIONS" />

<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|screenSize|smallestScreenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize"
        android:exported="true">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      
  
  <service android:name="com.twiliovoicereactnative.VoiceFirebaseMessagingService" android:stopWithTask="false" android:exported="true">
    <intent-filter>
      <action android:name="com.google.firebase.MESSAGING_EVENT" />
    </intent-filter>
  </service>
  <service android:enabled="true" android:name="com.twiliovoicereactnative.IncomingCallNotificationService" android:foregroundServiceType="microphone" android:exported="true">
    <intent-filter>
      <action android:name="ACTION_ACCEPT" />
      <action android:name="ACTION_REJECT" />
    </intent-filter>
  </service>
  <activity
    android:name="com.twiliovoicereactnative.NotificationProxyActivity"
    android:parentActivityName=".MainActivity"
    android:noHistory="true"
    android:excludeFromRecents="true"
    android:taskAffinity=""
    android:launchMode="singleTask"
    android:theme="@android:style/Theme.Translucent.NoTitleBar"
    android:exported="true" /> 
    </application>
</manifest>

------------------------- MainActivity.kt----------------------------------------
package com.dialsightconnect

import com.facebook.react.ReactActivity
import com.facebook.react.ReactActivityDelegate
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.fabricEnabled
import com.facebook.react.defaults.DefaultReactActivityDelegate

class MainActivity : ReactActivity() {

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  override fun getMainComponentName(): String = "DialSightConnect"

  /**
   * Returns the instance of the [ReactActivityDelegate]. We use [DefaultReactActivityDelegate]
   * which allows you to enable New Architecture with a single boolean flags [fabricEnabled]
   */
  override fun createReactActivityDelegate(): ReactActivityDelegate =
      DefaultReactActivityDelegate(this, mainComponentName, fabricEnabled)
}

------------------------- MainApplication.kt----------------------------------------
package com.dialsightconnect

import android.app.Application
import com.facebook.react.PackageList
import com.facebook.react.ReactApplication
import com.facebook.react.ReactHost
import com.facebook.react.ReactNativeHost
import com.facebook.react.ReactPackage
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.load
import com.facebook.react.defaults.DefaultReactHost.getDefaultReactHost
import com.facebook.react.defaults.DefaultReactNativeHost
import com.facebook.react.flipper.ReactNativeFlipper
import com.facebook.soloader.SoLoader

class MainApplication : Application(), ReactApplication {

  override val reactNativeHost: ReactNativeHost =
      object : DefaultReactNativeHost(this) {
        override fun getPackages(): List<ReactPackage> =
            PackageList(this).packages.apply {
              // Packages that cannot be autolinked yet can be added manually here, for example:
              // add(MyReactNativePackage())
            }

        override fun getJSMainModuleName(): String = "index"

        override fun getUseDeveloperSupport(): Boolean = BuildConfig.DEBUG

        override val isNewArchEnabled: Boolean = BuildConfig.IS_NEW_ARCHITECTURE_ENABLED
        override val isHermesEnabled: Boolean = BuildConfig.IS_HERMES_ENABLED
      }

  override val reactHost: ReactHost
    get() = getDefaultReactHost(this.applicationContext, reactNativeHost)

  override fun onCreate() {
    super.onCreate()
    SoLoader.init(this, false)
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
      // If you opted-in for the New Architecture, we load the native entry point for this app.
      load()
    }
    ReactNativeFlipper.initializeFlipper(this, reactNativeHost.reactInstanceManager)
  }
}

--> Please help<---

**Comment by afalls-twilio** [comment]
Two things..
1).  long press the app in on your andoird phone, then select app info, then select permissions and make sure that audio permissions are turned on. 
2) Please post your adb logs here if the above doesn't work.

**Comment by mhuynh5757** [comment]
Hi @himanshupkarak are you still encountering this issue? I'd like to close the issue as stale for now but feel free to re-open if you still need further assistance.
