### ISSUE TITLE
Unable to load script but app is running (npm run start & npm run android)

### ISSUE THREAD

**Issue by dmitriy-uvin** [twilio/twilio-voice-react-native#298]
# Issue

## Pre-submission Checklist
- [x] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
After implementing required instructions for migration to beta4 my app is not able to load anymore.
![image](https://github.com/twilio/twilio-voice-react-native/assets/51481296/f3d7e475-966a-455d-8611-e1393dcf38e7)

## Reproduction Steps
1. Clone https://github.com/dmitriy-uvin/mobile-dialpad
2. Go to the root directory
3. npm i
4. npm run start
5. npm run android

## Expected Behavior
App works as usual.

## Actual Behavior
App is not loaded.

## Software and Device Information
**Please complete the following information.**
 - OS: Android API Level 33, Tiramisy, Android 13.0
 - React version: 18.2.0
 - React Native version: 0.73.3
 - Node version: 20.9.0
 - npm or yarn version: 10.1.0

**Comment by mhuynh5757** [comment]
Hi @dmitriy-uvin thanks for reaching out. This is issue with the `react-native` scripts and not this library. There is a step in the `yarn run android` command that creates an adb tunnel from the emulator to your local environment and allows the emulator to communicate with the metro bundler. Sometimes, that adb command does not work. What I recommend is that you stop the emulator, cold boot it, and then start the app again the same way you're currently doing.

If that fails, you can try `adb reverse tcp:8081 tcp:8081` to manually perform that reverse tunneling.

**Comment by dmitriy-uvin** [comment]
Thank you for response @mhuynh5757, tried and It didn't work, but works on other project. So, I think there is some error with setup.

**Comment by dmitriy-uvin** [comment]
Hi @mhuynh5757, I think it can be closed for now. Fixed the problem.
