### ISSUE TITLE
[iOS] How to respond when user taps on call history

### ISSUE THREAD

**Issue by bojandurmic** [twilio/twilio-voice-react-native#303]
# Issue

## Pre-submission Checklist
- [x] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
When I create a call using `voice.connect()`, the app correctly creates an entry in call history. My question is how do I handle the event where a user taps on a call in call history?

I don't see any similar event in `voice.on`, nor do I see anything in CallKit configuration that would help me resolve this.

## Reproduction Steps
1. Make an outgoing call
2. End the call
3. Observe that there is a call in call history
4. Tap on your call

## Expected Behavior
I would like to have an ability to set an event listener, something like `"callHistoryTapped"`, which would tell me the number that was called and other relevant call information. I'd use that information to make a new call.

## Actual Behavior
Nothing happens.

## Reproduction Frequency
Every time

## Software and Device Information
**Please complete the following information.**
 - Device: iPhone 14 Pro Max
 - OS: iOS 17

**Comment by bojandurmic** [comment]
Hi @bobiechen-twilio 

Thank you for taking the time to answer my question! I'll try to implement this with basic Swift skills that I have.

I was wondering if there are plans to expose this to the JavaScript side? I believe this will be useful to almost anyone who's implementing calling functionality in their app.

**Comment by mhuynh5757** [comment]
Thanks for the feedback and suggestions @bojandurmic, we'll file an internal ticket to track this feature request.

**Comment by bojandurmic** [comment]
Thanks a lot @mhuynh5757 . Appreciate the work you guys already did!
