### ISSUE TITLE
Twilio voice not found

### ISSUE THREAD

**Issue by GaganJatana55** [twilio/twilio-voice-react-native#305]
› Compiling @twilio/voice-react-native-sdk Pods/twilio-voice-react-native » TwilioVoiceReactNative+CallKit.m

❌  (node_modules/@twilio/voice-react-native-sdk/ios/TwilioVoiceReactNative+CallKit.m:9:9)

   7 | 
   8 | @import CallKit;
>  9 | @import TwilioVoice;
     |         ^ module 'TwilioVoice' not found
  10 | 
  11 | #import "TwilioVoiceReactNative.h"
  12 | #import "TwilioVoiceReactNativeConstants.h"

› Compiling @twilio/voice-react-native-sdk Pods/twilio-voice-react-native » TwilioVoicePushRegistry.m

❌  (node_modules/@twilio/voice-react-native-sdk/ios/TwilioVoicePushRegistry.m:10:9)

   8 | @import PushKit;
   9 | @import Foundation;
> 10 | @import TwilioVoice;
     |         ^ module 'TwilioVoice' not found
  11 | 
  12 | #import "TwilioVoicePushRegistry.h"
  13 | #import "TwilioVoiceReactNative.h"
  
  
  Package json is: 
  
  {
  "name": "zing-app-ui",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "pods": "cd example && pod-install --quiet",
    "test:eslint": "echo \"\\033[33mRunning eslint check\" &&  eslint .",
    "test:tsc": "echo \"\\033[33mRunning typescript check\" && tsc"
  },
  "dependencies": {
    "@babel/plugin-proposal-export-namespace-from": "^7.18.9",
    "@dietime/react-native-date-picker": "^1.2.1",
    "@expo/webpack-config": "~18.0.1",
    "@fanchenbao/react-native-scroll-indicator": "^0.2.1",
    "@pdftron/webviewer": "^8.12.1",
    "@react-native-async-storage/async-storage": "1.17.11",
    "@react-native-community/netinfo": "9.3.7",
    "@react-native-community/slider": "4.4.2",
    "@react-native/metro-config": "^0.73.2",
    "@twilio/video-processors": "^2.0.0",
    "@twilio/voice-react-native-sdk": "^1.0.0-beta.4",
    "@twilio/voice-sdk": "^2.7.1",
    "axios": "^1.4.0",
    "dayjs": "^1.11.9",
    "expo": "~48.0.21",
    "expo-auth-session": "~4.0.3",
    "expo-av": "~13.2.1",
    "expo-constants": "~14.2.1",
    "expo-crypto": "~12.2.1",
    "expo-document-picker": "~11.5.4",
    "expo-file-system": "~15.2.2",
    "expo-font": "~11.1.1",
    "expo-image-picker": "~14.1.1",
    "expo-linear-gradient": "~12.1.2",
    "expo-linking": "~4.0.1",
    "expo-router": "^1.0.0",
    "expo-splash-screen": "~0.18.2",
    "expo-status-bar": "~1.4.4",
    "formik": "^2.4.2",
    "i18next": "^23.5.1",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "moment-timezone": "^0.5.43",
    "nativewind": "^2.0.11",
    "pod-install": "^0.1.39",
    "pusher-js": "^8.3.0",
    "qs": "^6.11.2",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-dropzone": "^14.2.3",
    "react-file-picker": "^0.0.6",
    "react-i18next": "^13.2.1",
    "react-native": "0.71.14",
    "react-native-big-calendar": "^4.5.0",
    "react-native-calendars": "^1.1300.0",
    "react-native-callkeep": "^4.3.12",
    "react-native-collapsible": "^1.6.1",
    "react-native-date-picker": "^4.3.3",
    "react-native-device-info": "^10.11.0",
    "react-native-document-picker": "^4.3.0",
    "react-native-draggable": "^3.3.0",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-gridview": "^0.1.2",
    "react-native-indicators": "^0.17.0",
    "react-native-pager-view": "6.1.2",
    "react-native-permissions": "^4.1.1",
    "react-native-popable": "^0.4.3",
    "react-native-popover-view": "^5.1.8",
    "react-native-reanimated": "2.17.0",
    "react-native-reanimated-carousel": "3.0.0",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "~3.20.0",
    "react-native-simple-radio-button": "^2.7.4",
    "react-native-tab-view": "^3.5.2",
    "react-native-toast-message": "^2.1.6",
    "react-native-twilio-video-webrtc": "^3.2.0",
    "react-native-web": "~0.18.10",
    "react-outside-click-handler": "^1.3.0",
    "react-native-flipper": "^0.164.0",
    "react-phone-number-input": "^3.3.7",
    "react-timer-hook": "^3.0.7",
    "rn-country-dropdown-picker": "^2.1.8",
    "slugify": "^1.6.6",
    "twilio": "^4.15.0",
    "twilio-video": "^2.27.0",
    "twrnc": "^3.6.4",
    "use-file-picker": "^2.1.1",
    "usehooks-ts": "^2.9.1",
    "uuid-by-string": "^4.0.0",
    "yup": "^1.2.0",
    "zustand": "^4.3.9"
  },
  "devDependencies": {
    "@babel/core": "^7.20.2",
    "@types/react": "~18.0.27",
    "@types/react-native": "^0.72.2",
    "@typescript-eslint/eslint-plugin": "^5.60.1",
    "@typescript-eslint/parser": "^5.60.1",
    "autoprefixer": "^10.4.14",
    "eslint": "^8.43.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-config-universe": "^11.2.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-react": "^7.32.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "postcss": "^8.4.26",
    "postcss-loader": "^4.2.0",
    "prettier": "^2.8.8",
    "prettier-plugin-tailwindcss": "^0.3.0",
    "react-native-dotenv": "^3.4.9",
    "tailwindcss": "3.3.2",
    "typescript": "^4.9.4"
  },
  "overrides": {
    "metro": "0.76.0",
    "metro-resolver": "0.76.0"
  },
  "private": true,
  "volta": {
    "node": "14.21.3"
  },
  "engines": {
    "node": "14.21.1"
  },
  "resolutions": {
    "@babel/core": "^7.20.2",
    "babel-loader": "^8.3.0"
  }
}
  
  
  and Pod file in ios is : 
  

use_modular_headers!
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = '1' if podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR'] == 'true'

platform :ios, podfile_properties['ios.deploymentTarget'] || '13.0'
install! 'cocoapods',
  :deterministic_uuids => false

prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...), which will be excluded. To fix this,
# you can also exclude `react-native-flipper` in `react-native.config.js`
#
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
#   }
# }
# ```
flipper_config = FlipperConfiguration.disabled
if ENV['NO_FLIPPER'] == '1' then
  # Explicitly disabled through environment variables
  flipper_config = FlipperConfiguration.disabled
elsif podfile_properties.key?('ios.flipper') then
  # Configure Flipper in Podfile.properties.json
  if podfile_properties['ios.flipper'] == 'true' then
    flipper_config = FlipperConfiguration.enabled(["Debug", "Release"])
  elsif podfile_properties['ios.flipper'] != 'false' then
    flipper_config = FlipperConfiguration.enabled(["Debug", "Release"], { 'Flipper' => podfile_properties['ios.flipper'] })
  end
end

target 'ZING' do
  use_expo_modules!
  config = use_native_modules!

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    # Note that if you have use_frameworks! enabled, Flipper will not work if enabled
    :flipper_configuration => flipper_config
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
end

unable to compile

**Comment by bojandurmic** [comment]
Hey there!

I see you are using Expo. To be able to use any native code in Expo, you need to create a development client. Please refer to the official docs on how to do that.

For iOS, I also had to create a custom Expo config plugin. First, create a file `expo-plugins/callCapabilities.plugin.js`:

```javascript
const { withInfoPlist } = require('@expo/config-plugins');

const callCapabilitiesPlugin = (config) => {
  return withInfoPlist(config, (config) => {
    // Add permissions
    config.modResults['NSMicrophoneUsageDescription'] =
      'We need access to your microphone to be able to make calls and send voicemail.';
    config.modResults['NSUserActivityTypes'] = [
      'INStartAudioCallIntent',
      'INStartCallIntent',
    ];

    // Add audio and voip to UIBackgroundModes
    config.modResults['UIBackgroundModes'] = ['audio', 'voip'];

    // Set APS Environment to development
    config.modResults['aps-environment'] = 'development';

    return config;
  });
};

module.exports = callCapabilitiesPlugin;
```

This will add some capabilities to your `Info.plist` file.

Then, in `app.json`, add it to your plugins, for example:

```
"plugins": ["expo-router", "./expo-plugins/callCapabilities.plugin"]
```

**Comment by mhuynh5757** [comment]
Hi all, thanks for the community discussion and problem solving. Unfortunately, we do not have official Expo support and no plans in the near future.

@bojandurmic thanks for the recommendations, @GaganJatana55 could you try to implement these changes?

**Comment by bojandurmic** [comment]
@mhuynh5757 it's not that difficult to set this up to work with Expo. The most issues come with setting up proper capabilities in `Info.plist` file, as well as configuring backend (adding APN certificate etc.).

I'll write a blog post about this in the near future, so someone else doesn't spend dozens of errors of trial and error 😆

**Comment by mhuynh5757** [comment]
Thanks @bojandurmic! I'm looking forward to your blog post!

**Comment by mhuynh5757** [comment]
Hi @GaganJatana55 are you still encountering this issue?

**Comment by kpchoy** [comment]
Closing for now. Please create a new issue if you are experiencing problems.
