### ISSUE TITLE
Twilio doesn't init the call, but works as a test call within TwilML app (Dial error?)

### ISSUE THREAD

**Issue by dmitriy-uvin** [twilio/twilio-voice-react-native#307]
# Issue

## Pre-submission Checklist
- [x] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
Installed sdk and want to implement outbound calls for iOS and  it doesn't work but works on android. It even doesnt' create any calls/logs in Twilio console.

## Reproduction Steps
1. Go to https://github.com/dmitriy-uvin/dialer-rn
2. Clone repo and follow common init flow of RN app

## Expected Behavior
Outbound calls work both on android & iOS.

## Software and Device Information
**Please complete the following information.**
 - Device: iPhone 15
 - OS: iOS 15
 - React version: 18.2.0
 - React Native version: 0.73.4
 - Node version: 21.6.1
 - npm or yarn version: 10.2.4

## Additional Context
package.json

```
{
  "name": "mobile",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start --reset-cache",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.21.0",
    "@react-navigation/bottom-tabs": "^6.5.11",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/native-stack": "^6.9.17",
    "@twilio/voice-react-native-sdk": "^1.0.0-beta.4",
    "axios": "^1.6.7",
    "react": "18.2.0",
    "react-hook-form": "^7.50.0",
    "react-native": "^0.73.4",
    "react-native-safe-area-context": "^4.9.0",
    "react-native-screens": "^3.29.0",
    "react-native-toast-notifications": "^3.4.0",
    "react-native-vector-icons": "^10.0.3",
    "twilio": "^4.21.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "0.73.20",
    "@react-native/eslint-config": "0.73.2",
    "@react-native/metro-config": "0.73.4",
    "@react-native/typescript-config": "0.73.1",
    "@types/react": "^18.2.6",
    "@types/react-native-vector-icons": "^6.4.18",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "babel-plugin-module-resolver": "^5.0.0",
    "eslint": "^8.19.0",
    "jest": "^29.6.3",
    "prettier": "2.8.8",
    "react-native-dotenv": "^3.4.9",
    "react-test-renderer": "18.2.0",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  }
}
```

**Comment by dmitriy-uvin** [comment]
@mhuynh5757 @afalls-twilio I will appreciate your help guys.

**Comment by dmitriy-uvin** [comment]
UPD: made it work, and for some reason all calls from the first second with "Cancelled" status, but if I make test call from TwilML app page it works as expected, callee receives a call.

**Comment by mhuynh5757** [comment]
Hi @dmitriy-uvin thanks for reaching out, glad to see that you solved your issue. This means that your problem is very very likely your TwiML configuration and not related to this library. I will close this issue now, but if you have further issues please feel free to reach out again.

**Comment by dmitriy-uvin** [comment]
@mhuynh5757 maybe you can help we to understand the problem better. There are two calls:
- works as expected (test call from TwilML app), response from my API
**Request:**
```
ApplicationSid	"app sid"
ApiVersion	"2010-04-01"
Called	""
Caller	"client:Anonymous"
CallStatus	"ringing"
CallSid	"CAda94baaf8114ad4e998555d88b68664c"
From	"client:Anonymous"
To	""
Direction	"inbound"
AccountSid	"account Sid"
```
**Response from my API:**
```
<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Dial answerOnBridge="true" callerId="+12672449950" record="record-from-ringing-dual" timeout="5">
        <Number>+16592087485</Number>
    </Dial>
</Response>
```
- calls right from the initialising become Cancelled
**Request:**
```
ApplicationSid	"app sid"
ApiVersion	"2010-04-01"
Called	""
recipientType	"number"
Caller	"client:user_id"
CallStatus	"ringing"
CallSid	"CA2492cabfdc923aa0fc438a052b748391"
From	"client:user_id"
To	"+16592087485"
Direction	"inbound"
AccountSid	"acc sid"
```

**Response:**
```
<?xml version="1.0" encoding="UTF-8"?>
<Response>
    <Dial answerOnBridge="true" callerId="+12672449950" record="record-from-ringing-dual" timeout="5">
        <Number>+16592087485</Number>
    </Dial>
</Response>
```

Where is the problem can be?

**Comment by dmitriy-uvin** [comment]
And question about iOS setup, is everything correct?

**Comment by dmitriy-uvin** [comment]
I think something wrong in my iOS setup, because calls work from TwilML app (Call using Twilio Client from TwilML app) & my API returns the same XML.

**Comment by dmitriy-uvin** [comment]
@mhuynh5757 @afalls-twilio hi guys, our business is suffering from inability to make outbound calls on iOS
It triggers the call (can see in console), but it'c cancelled right after creation (but on android everything works perfectly).
Could we have a call or something similar to speed up and solve within couple of hours? (can pay for your consulting)
I am duplicating the link to the repo and will appreciate a lot if you can point what's wrong - https://github.com/dmitriy-uvin/dialer-rn.

**Comment by mhuynh5757** [comment]
Hi @dmitriy-uvin are you using a real physical iOS device and not a simulator? Apple limits the capabilities of simulators for one reason or another, there's nothing we can do about it unfortunately.

**Comment by dmitriy-uvin** [comment]
@bobiechen-twilio here it's 
https://gist.github.com/dmitriy-uvin/1ec115f956353ee02191c52ef25ebdbf

**Comment by bobiechen-twilio** [comment]
@dmitriy-uvin from the Call SID you provided:
- `call.disconnect()` was called from the local client immediately after the call was started
- also from the call record, the TwiML request failed with a 404 response from your app server. (TwiML App SID ending with `1f9f`)

**Comment by dmitriy-uvin** [comment]
1 second

**Comment by dmitriy-uvin** [comment]
@bobiechen-twilio fixed twilml url
https://gist.github.com/dmitriy-uvin/6e19e75c8d3214c617b4dbc6795c2f0c

**Comment by dmitriy-uvin** [comment]
@mhuynh5757 I mean, is it expected twilio calls don't work on simulator?

**Comment by himanshupkarak** [comment]
@dmitriy-uvin I had same issue as you, working fine with android but same issue with IOS...   i just test it on real device iphone 14 not on simulator.  and it works fine for me

**Comment by himanshupkarak** [comment]
@dmitriy-uvin my call is not disconnect (or cancelled) automatically now on real device

**Comment by mhuynh5757** [comment]
Hi @dmitriy-uvin yes, it is expected that our library will not work on iOS simulators. This is a limitation imposed by Apple, not by Twilio. There's nothing we can do about it unfortunately.

**Comment by mhuynh5757** [comment]
Hi @dmitriy-uvin have you been able to try our library with a real iOS device?

**Comment by mhuynh5757** [comment]
Hi @dmitriy-uvin I'd like to close this issue as stale for now, please reach out again if you need further assistance.
