### ISSUE TITLE
Low ringtone volume on mobile phones only 

### ISSUE THREAD

**Issue by greenraze13** [twilio/twilio-voice-react-native#318]
I have implemented twilio-voice-react-native in app and testing the call feature from other app.Overall call is working fine. But Incoming ring tone volume is very low on android phones. But its working fine on android tablets  

When incoming call start notification also appear but ringtone is slow.
Some times I have noticed incoming call Ringtone volume loud on very start but instantly it become slow. This happened very rarely.

Tested on 
Google pixel 6  Android version 13 
moto e13      Android version 13 
Honor 8c        Android version 8.1
Incoming ringtone  volume is very slow.Even mobile volume is full. 

and Galaxy Tab A8  Android 12 
on tab  incoming ringtone volume is louder.
 
My sdk version is  "@twilio/voice-react-native-sdk": "^1.0.0-rc8", Its not latest  because already features are working according to this version. I have planned to update it later.

**Comment by mhuynh5757** [comment]
Hi @greenraze13 we've made significant changes to the native Android layer, if you could try it on the latest versions to confirm the issue that would be appreciated. If you could also provide a video of the issue, that would also help us to diagnose the issue, as well as providing ADB logs.

**Comment by mhuynh5757** [comment]
Hi @greenraze13 I'd like to close this issue as stale for now, please create another issue if you still need further assistance.

**Comment by fakenlol** [comment]
Hi, @greenraze13. Did you can solved the problem and how?

**Comment by sshodges** [comment]
Any solution to this? Volume of ring town is very low
