### ISSUE TITLE
how can i cancel or reject the incoming call

### ISSUE THREAD

**Issue by shubham-pal-clecotech** [twilio/twilio-voice-react-native#319]
# Issue

## Pre-submission Checklist
- [ ] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [ ] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [ ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
A clear and concise description of what the issue is.

## Actual Behavior
What actually happens.

## Reproduction Frequency
Is the reproducibility of the issue deterministic? If not, what percentage of the time does the issue occur? In how many attempts was the issue observed?

## Software and Device Information
**Please complete the following information.**
 - Device: [e.g. iPhone 12, Pixel 3]
 - OS: [e.g. iOS 16, Android API Level 31]
 - React version: [e.g. 18.1.0]
 - React Native version: [e.g. 0.70.9]
 - Node version: [e.g. 16.18.1]
 - npm or yarn version: [e.g. 8.19.2, 1.22.19]

**Comment by mhuynh5757** [comment]
Hi @shubham-pal-clecotech please fill out the issue description.

**Comment by shubham-pal-clecotech** [comment]
@mhuynh5757 
import React from 'react';
import {
  CallInvite,
  Voice,
  Call,
  CancelledCallInvite,
  AudioDevice,
} from '@twilio/voice-react-native-sdk';
const voice = new Voice();
let call = new Call({});
var token = '';
async function login() {
  console.log('hiilogin');
  try {
    await voice.initVoice();
    const response = await fetch(
      'https://67b8-122-168-238-141.ngrok-free.app/twilio/twilio_numbers/get_mobile_app_token?id=14243468978&push_credential_sid=CR94014b9797f27bfb4e06990ae524c543',
    );
    console.log(response, 'response');
    const accessToken = await response.json();
    console.log(accessToken, 'accessToken');
    token = accessToken.token;

    voice.on(Voice.Event.Registered, e => {
      console.log('Registered', e);
    });
    const register = await voice.register(accessToken.token);
    console.log('registeredc', register);
    voice.on(Voice.Event.RegistrationFailed, e => {
      console.log('Registration Failed', e);
    });
  } catch (err) {
    console.log(err);
  }
}

voice.on(Voice.Event.CallInvite, callInvite => {
  console.log('Incoming call:', callInvite);
  const incomingCall = new Call(callInvite);
  // Now `incomingCall` is available for further handling
  console.log('afterhadnle');
});

async function connect(phoneNumber) {
  try {
    let test = await voice.connect(token, {
      params: {
        To: '14245522537',
        From: '14243468978',
      },
    });
    console.log(test, 'TESSSTTT');
    call = test;
    console.log('Call initiated successfully', call);
  } catch (err) {
    console.log(err);
  }
}
// Add event handlers for the connected call
call.on('connected', () => {
  console.log('Call connected');
});

call.on('disconnected', (call, error) => {
  console.log('Call disconnected', error);
});

call.on('connecting', () => {
  console.log('Call connecting');
});

call.on('reconnected', () => {
  console.log('Call reconnected');
});

call.on('reconnecting', (call, error) => {
  console.log('Call reconnecting', error);
});

call.on('ringing', () => {
  console.log('Call ringing');
});

call.on('connectFailure', (call, error) => {
  console.log('Call connect failure', error);
  if (error) {
    if (error.code) {
      console.log('Error Code:', error.code);
    }
    if (error.message) {
      console.log('Error Message:', error.message);
    }
    if (error.description) {
      console.log('Error Description:', error.description);
    }
  } else {
    console.log('No error details available');
  }
});

voice.on(Voice.Event.Unregistered, e => {
  console.log('Unregistered', e);
});
voice.on(Voice.Event.Error, e => {
  console.log('Error', e);
});
voice.on(Voice.Event.AudioDevicesUpdated, e => {
  console.log('AudioDevicesUpdated', e);
});
voice.on(Voice.Event.CallInvite, e => {
  console.log('CallInvite', e);
});
voice.on(Voice.Event.CallInviteAccepted, e => {
  console.log('CallInviteAccepted', e);
});
voice.on(Voice.Event.CallInviteNotificationTapped, e => {
  console.log('CallInviteAccepted', e);
});
voice.on(Voice.Event.CallInviteRejected, e => {
  console.log('CallInviteRejected', e);
});
voice.on(Voice.Event.CancelledCallInvite, e => {
  console.log('CancelledCallInvite', e);
});

async function rejectCall(event) {
  console.log('hiiirejectcall');
  console.log('hiidisconect', event);
  let sid = event.twi_call_sid;
  console.log('siddd', sid);
  try {
    if (call && call.state === 'connecting') {
      await call.disconnect();
      console.log('Call disconnected successfully');
    } else {
      console.log('goinginlese');
      const cancelCall = new CancelledCallInvite(sid);

      console.log('Call rejected successfully', cancelCall);
    }
  } catch (error) {
    console.error('Error disconnecting call:', error);
  }
}

async function callMute(e) {
  const isMuted = await call.mute(e);
  console.log('isMuted', isMuted);
}

async function sendDigits(digit) {
  const digits = await call.sendDigits(digit);
  console.log('digits', digits);
}

async function callDisconnect(event) {
  console.log('hiidisconect', event);
  console.log('hiidisconect', call);

  const disconnect = await new Call(event).disconnect();
  console.log('disconnect', disconnect);
}

export {login, connect, callMute, sendDigits, callDisconnect, rejectCall};
I am trying with this i have successfully call i am getting the call but now i want to try to reject  and accept an incoming call i am unable to do this how can i achieve this can you help even i am not getting the callinvite console listener i am stuck here

**Comment by shubham-pal-clecotech** [comment]
please reply as soon as possible @mhuynh5757 i am stuck

**Comment by bojandurmic** [comment]
@shubham-pal-clecotech you need to listen to `Voice.Event.CallInvite` event.

```
useEffect(() => {
  const callInviteReceivedHandler = (callInvite: CallInvite) => {
    console.log('Call invite received.');
    setCallInvite(callInvite);
  };

  voice.on(Voice.Event.CallInvite, callInviteReceivedHandler);
  return () => {
    voice.off(Voice.Event.CallInvite, callInviteReceivedHandler);
  }
}, []);
```

This code will listen to the event. Event sends you a `CallInvite` instance, which you should store somewhere, usually as a piece of state in `useState` hook.

Then, you'll have a function like this one:

```
const rejectIncomingCall = async () => {
    if (!callInvite) {
      console.warn('No call invite to reject');
    } else {
      await callInvite.reject();
      setCallInvite(null);
    }
};
```
You'll call `rejectIncomingCall` somewhere in your code.

**Comment by shubham-pal-clecotech** [comment]
import React, { Component } from "react";
import {
  CallInvite,
  Voice,
  Call,
  CancelledCallInvite,
  AudioDevice,
} from "@twilio/voice-react-native-sdk";
import { View } from "react-native";
const voice = new Voice();
let call = new Call({});
var token = "";
var callAccept = "";
var activeCallInvite;
class Plivo extends Component {
  constructor(props) {
    super(props);
    this.state = {
      callInvite: null,
    };
    this.callInviteReceivedHandler = this.callInviteReceivedHandler.bind(this);
    this.login = this.login.bind(this);
    this.connect = this.connect.bind(this);
    this.rejectCall = this.rejectCall.bind(this);
    this.callMute = this.callMute.bind(this);
    this.sendDigits = this.sendDigits.bind(this);
    this.callDisconnect = this.callDisconnect.bind(this);
  }
  componentDidMount() {
    const callInviteReceivedHandler = (callInvite) => {
      console.log("Call invite received.");
      this.setState({ callInvite });
    };
    voice.on(Voice.Event.CallInvite, callInviteReceivedHandler);
    this.cleanup = () => {
      voice.off(Voice.Event.CallInvite, callInviteReceivedHandler);
    };
    voice.on(Voice.Event.Unregistered, (e) => {
      console.log("Unregistered", e);
    });
    voice.on(Voice.Event.Error, (e) => {
      console.log("Error", e);
    });
    voice.on(Voice.Event.AudioDevicesUpdated, (e) => {
      console.log("AudioDevicesUpdated", e);
    });
    voice.on(Voice.Event.CallInviteAccepted, (e) => {
      console.log("CallInviteAccepted", e);
    });
    voice.on(Voice.Event.CallInviteNotificationTapped, (e) => {
      console.log("CallInviteNotificationTapped", e);
    });
    voice.on(Voice.Event.CallInviteRejected, (e) => {
      console.log("CallInviteRejected", e);
    });
    voice.on(Voice.Event.CancelledCallInvite, (e) => {
      console.log("CancelledCallInvite", e);
    });
  }
  componentWillUnmount() {
    this.cleanup();
    voice.off(Voice.Event.Unregistered);
    voice.off(Voice.Event.Error);
    voice.off(Voice.Event.AudioDevicesUpdated);
    voice.off(Voice.Event.CallInviteAccepted);
    voice.off(Voice.Event.CallInviteNotificationTapped);
    voice.off(Voice.Event.CallInviteRejected);
    voice.off(Voice.Event.CancelledCallInvite);
  }
  async login() {
    console.log("hiilogin");
    try {
      const response = await fetch(
        "https://active-sunny-loon.ngrok-free.app/twilio/twilio_numbers/get_mobile_app_token?id=14245522537&push_credential_sid=CR94014b9797f27bfb4e06990ae524c543"
      );
      console.log(response, "response");
      const accessToken = await response.json();
      console.log(accessToken, "accessToken");
      token = accessToken.token;
      voice.on(Voice.Event.Registered, (e) => {
        console.log("Registered", e);
      });
      voice.on(Voice.Event.RegistrationFailed, (e) => {
        console.log("Registration Failed", e);
      });
      const register = await voice.register(accessToken.token);
      console.log("registeredc", register);
    } catch (err) {
      console.log(err);
    }
  }
  async connect(phoneNumber) {
    try {
      let test = await voice.connect(token, {
        params: {
          To: "14243468978",
          From: "14245522537",
        },
      });
      call = new Call(test);
      console.log("Call initiated successfully", call);
    } catch (err) {
      console.log(err);
    }
  }
  async rejectCall(event) {
    console.log("hiiirejectcall", event);
    let sid = event.twi_call_sid;
    let from = event.twi_from;
    let to = event.twi_to;
    console.log("siddd", sid);
    try {
      if (call && call.state === "connecting") {
        await call.disconnect();
        console.log("Call disconnected successfully");
      } else {
        console.log("goinginlese");
        await Voice.hangup(sid);
        console.log("Call rejected successfully");
      }
    } catch (error) {
      console.error("Error disconnecting call:", error);
    }
  }
  async callMute(e) {
    const isMuted = await call.mute(e);
    console.log("isMuted", isMuted);
  }
  async sendDigits(digit) {
    const digits = await call.sendDigits(digit);
    console.log("digits", digits);
  }
  async callDisconnect(event) {
    console.log("hiidisconect", event);
    if (!this.state.callInvite) {
      console.warn("No call invite to reject");
    } else {
      await this.state.callInvite.reject();
      this.setState({ callInvite: null });
    }
  }
  // Other methods and event handlers...
  render() {
    return <View>{/* Your component's JSX here */}</View>;
  }
}
const plivoInstance = new Plivo();
export default plivoInstance;
@bojandurmic this is my code i have tried but it goes everytime in if condition it gives me No call invite to reject

**Comment by shubham-pal-clecotech** [comment]
@bojandurmic i am trying with below code but i goes eveytime in if condition it gives me No Call invite to reject everytime please help me to solve this
import React, { Component } from "react";
import {
  CallInvite,
  Voice,
  Call,
  CancelledCallInvite,
  AudioDevice,
} from "@twilio/voice-react-native-sdk";
import { View } from "react-native";
const voice = new Voice();
let call = new Call({});
var token = "";
var callAccept = "";
var activeCallInvite;
class Plivo extends Component {
  constructor(props) {
    super(props);
    this.state = {
      callInvite: null,
    };
    this.callInviteReceivedHandler = this.callInviteReceivedHandler.bind(this);
    this.login = this.login.bind(this);
    this.connect = this.connect.bind(this);
    this.rejectCall = this.rejectCall.bind(this);
    this.callMute = this.callMute.bind(this);
    this.sendDigits = this.sendDigits.bind(this);
    this.callDisconnect = this.callDisconnect.bind(this);
  }
  componentDidMount() {
    voice.on(Voice.Event.CallInvite, callInviteReceivedHandler);
    this.cleanup = () => {
      voice.off(Voice.Event.CallInvite, callInviteReceivedHandler);
    };
    voice.on(Voice.Event.Unregistered, (e) => {
      console.log("Unregistered", e);
    });
    voice.on(Voice.Event.Error, (e) => {
      console.log("Error", e);
    });
    voice.on(Voice.Event.AudioDevicesUpdated, (e) => {
      console.log("AudioDevicesUpdated", e);
    });
    voice.on(Voice.Event.CallInviteAccepted, (e) => {
      console.log("CallInviteAccepted", e);
    });
    voice.on(Voice.Event.CallInviteNotificationTapped, (e) => {
      console.log("CallInviteNotificationTapped", e);
    });
    voice.on(Voice.Event.CallInviteRejected, (e) => {
      console.log("CallInviteRejected", e);
    });
    voice.on(Voice.Event.CancelledCallInvite, (e) => {
      console.log("CancelledCallInvite", e);
    });
  }
  componentWillUnmount() {
    this.cleanup();
    voice.off(Voice.Event.Unregistered);
    voice.off(Voice.Event.Error);
    voice.off(Voice.Event.AudioDevicesUpdated);
    voice.off(Voice.Event.CallInviteAccepted);
    voice.off(Voice.Event.CallInviteNotificationTapped);
    voice.off(Voice.Event.CallInviteRejected);
    voice.off(Voice.Event.CancelledCallInvite);
  }
  callInviteReceivedHandler(callInvite) {
    console.log("Call invite received.");
    this.setState({ callInvite });
  }
  async login() {
    console.log("hiilogin");
    try {
      const response = await fetch(
        "https://active-sunny-loon.ngrok-free.app/twilio/twilio_numbers/get_mobile_app_token?id=14245522537&push_credential_sid=CR94014b9797f27bfb4e06990ae524c543"
      );
      console.log(response, "response");
      const accessToken = await response.json();
      console.log(accessToken, "accessToken");
      token = accessToken.token;
      voice.on(Voice.Event.Registered, (e) => {
        console.log("Registered", e);
      });
      voice.on(Voice.Event.RegistrationFailed, (e) => {
        console.log("Registration Failed", e);
      });
      const register = await voice.register(accessToken.token);
      console.log("registeredc", register);
    } catch (err) {
      console.log(err);
    }
  }
  async connect(phoneNumber) {
    try {
      let test = await voice.connect(token, {
        params: {
          To: "14243468978",
          From: "14245522537",
        },
      });
      call = new Call(test);
      console.log("Call initiated successfully", call);
    } catch (err) {
      console.log(err);
    }
  }
  async rejectCall(event) {
    console.log("hiiirejectcall", event);
    let sid = event.twi_call_sid;
    let from = event.twi_from;
    let to = event.twi_to;
    console.log("siddd", sid);
    try {
      if (call && call.state === "connecting") {
        await call.disconnect();
        console.log("Call disconnected successfully");
      } else {
        console.log("goinginlese");
        await Voice.hangup(sid);
        console.log("Call rejected successfully");
      }
    } catch (error) {
      console.error("Error disconnecting call:", error);
    }
  }
  async callMute(e) {
    const isMuted = await call.mute(e);
    console.log("isMuted", isMuted);
  }
  async sendDigits(digit) {
    const digits = await call.sendDigits(digit);
    console.log("digits", digits);
  }
  async callDisconnect(event) {
    console.log("hiidisconect", event);
    if (!this.state.callInvite) {
      console.warn("No call invite to reject");
    } else {
      await this.state.callInvite.reject();
      this.setState({ callInvite: null });
    }
  }
  // Other methods and event handlers...
  render() {
    return <View>{/* Your component's JSX here */}</View>;
  }
}
const plivoInstance = new Plivo();
export default plivoInstance;

**Comment by bojandurmic** [comment]
@shubham-pal-clecotech can you please format that code as GitHub code block?

**Comment by shubham-pal-clecotech** [comment]
@bojandurmic sure please check below my code 
import React, { Component } from "react";
import { CallInvite, Voice, Call, CancelledCallInvite, AudioDevice } from "@twilio/voice-react-native-sdk";
import { View } from "react-native";

const voice = new Voice();
let call = new Call({});
var token = "";
var callAccept = "";
var activeCallInvite;

class Plivo extends Component {
  constructor(props) {
    super(props);
    this.state = {
      callInvite: null,
    };
    this.callInviteReceivedHandler = this.callInviteReceivedHandler.bind(this);
    this.login = this.login.bind(this);
    this.connect = this.connect.bind(this);
    this.rejectCall = this.rejectCall.bind(this);
    this.callMute = this.callMute.bind(this);
    this.sendDigits = this.sendDigits.bind(this);
    this.callDisconnect = this.callDisconnect.bind(this);
  }

  componentDidMount() {
    voice.on(Voice.Event.CallInvite, callInviteReceivedHandler);
    this.cleanup = () => {
      voice.off(Voice.Event.CallInvite, callInviteReceivedHandler);
    };

    voice.on(Voice.Event.Unregistered, (e) => {
      console.log("Unregistered", e);
    });

    voice.on(Voice.Event.Error, (e) => {
      console.log("Error", e);
    });

    voice.on(Voice.Event.AudioDevicesUpdated, (e) => {
      console.log("AudioDevicesUpdated", e);
    });

    voice.on(Voice.Event.CallInviteAccepted, (e) => {
      console.log("CallInviteAccepted", e);
    });

    voice.on(Voice.Event.CallInviteNotificationTapped, (e) => {
      console.log("CallInviteNotificationTapped", e);
    });

    voice.on(Voice.Event.CallInviteRejected, (e) => {
      console.log("CallInviteRejected", e);
    });

    voice.on(Voice.Event.CancelledCallInvite, (e) => {
      console.log("CancelledCallInvite", e);
    });
  }

  componentWillUnmount() {
    this.cleanup();
    voice.off(Voice.Event.Unregistered);
    voice.off(Voice.Event.Error);
    voice.off(Voice.Event.AudioDevicesUpdated);
    voice.off(Voice.Event.CallInviteAccepted);
    voice.off(Voice.Event.CallInviteNotificationTapped);
    voice.off(Voice.Event.CallInviteRejected);
    voice.off(Voice.Event.CancelledCallInvite);
  }

  callInviteReceivedHandler(callInvite) {
    console.log("Call invite received.");
    this.setState({ callInvite });
  }

  async login() {
    console.log("hiilogin");
    try {
      const response = await fetch("https://active-sunny-loon.ngrok-free.app/twilio/twilio_numbers/get_mobile_app_token?id=14245522537&push_credential_sid=CR94014b9797f27bfb4e06990ae524c543");
      console.log(response, "response");
      const accessToken = await response.json();
      console.log(accessToken, "accessToken");
      token = accessToken.token;

      voice.on(Voice.Event.Registered, (e) => {
        console.log("Registered", e);
      });

      voice.on(Voice.Event.RegistrationFailed, (e) => {
        console.log("Registration Failed", e);
      });

      const register = await voice.register(accessToken.token);
      console.log("registeredc", register);
    } catch (err) {
      console.log(err);
    }
  }

  async connect(phoneNumber) {
    try {
      let test = await voice.connect(token, {
        params: {
          To: "14243468978",
          From: "14245522537",
        },
      });
      call = new Call(test);
      console.log("Call initiated successfully", call);
    } catch (err) {
      console.log(err);
    }
  }

  async rejectCall(event) {
    console.log("hiiirejectcall", event);
    let sid = event.twi_call_sid;
    let from = event.twi_from;
    let to = event.twi_to;
    console.log("siddd", sid);
    try {
      if (call && call.state === "connecting") {
        await call.disconnect();
        console.log("Call disconnected successfully");
      } else {
        console.log("goinginlese");
        await Voice.hangup(sid);
        console.log("Call rejected successfully");
      }
    } catch (error) {
      console.error("Error disconnecting call:", error);
    }
  }

  async callMute(e) {
    const isMuted = await call.mute(e);
    console.log("isMuted", isMuted);
  }

  async sendDigits(digit) {
    const digits = await call.sendDigits(digit);
    console.log("digits", digits);
  }

  async callDisconnect(event) {
    console.log("hiidisconect", event);
    if (!this.state.callInvite) {
      console.warn("No call invite to reject");
    } else {
      await this.state.callInvite.reject();
      this.setState({ callInvite: null });
    }
  }

 

  render() {
    return {<View></View>};
  }
}

const plivoInstance = new Plivo();
export default plivoInstance;

**Comment by mhuynh5757** [comment]
Hi all, thanks for the community discussion.

@shubham-pal-clecotech it seems like you're instantiating the Call or CallInvite objects yourself. You should not do this, the SDK will instantiate all Call and CallInvite objects for you. The only class you will need to instantiate yourself is the Voice object. If you check the API documentation for the Voice object, you'll see that `voice.connect` returns a call for you. And `voice.on(Voice.Event.CallInvite, ...)` will pass your listener a CallInvite. When you try to instantiate one yourself, none of the event handlers are properly registered.

Also, please format your code blocks, it's incredibly hard to read your code without them. You can search for GitHub markdown guides, or click the "Markdown is supported" button for a guide.

**Comment by shubham-pal-clecotech** [comment]
import React, { Component } from 'react';
import { Voice } from '@twilio/voice-react-native-sdk';
import { View } from 'react-native';

const voice = new Voice();
let token = '';

class Plivo extends Component {
  constructor(props) {
    super(props);
    this.state = {
      callInvite: null,
    };
    this.callInviteReceivedHandler = this.callInviteReceivedHandler.bind(this);
    this.login = this.login.bind(this);
    this.connect = this.connect.bind(this);
    this.rejectCall = this.rejectCall.bind(this);
    this.callMute = this.callMute.bind(this);
    this.sendDigits = this.sendDigits.bind(this);
    this.callDisconnect = this.callDisconnect.bind(this);
  }

  componentDidMount() {
    console.log('Plivo DidMount');
    voice.on(Voice.Event.CallInvite, this.callInviteReceivedHandler);
    this.cleanup = () => {
      voice.off(Voice.Event.CallInvite, this.callInviteReceivedHandler);
    };
    // Other event handlers...
    voice.on(Voice.Event.CancelledCallInvite, (e) => {
      console.log('CancelledCallInvite', e);
    });
  }

  componentWillUnmount() {
    this.cleanup();
    // Remove other event handlers...
    voice.off(Voice.Event.CancelledCallInvite);
  }

  callInviteReceivedHandler(callInvite) {
    console.log('Call invite received.');
    this.setState({ callInvite });
  }

  async login() {
    console.log('hii login');
    try {
      const response = await fetch(
        'https://www.voicerules.com/twilio/twilio_numbers/get_mobile_app_token?id=14243468978&push_credential_sid=CR94014b9797f27bfb4e06990ae524c543'
      );
      console.log(response, 'response');
      const accessToken = await response.json();
      console.log(accessToken, 'accessToken');
      token = accessToken.token;
      voice.on(Voice.Event.Registered, (e) => {
        console.log('Registered', e);
      });
      voice.on(Voice.Event.RegistrationFailed, (e) => {
        console.log('Registration Failed', e);
      });
      const register = await voice.register(accessToken.token);
      console.log('registered', register);
    } catch (err) {
      console.log(err);
    }
  }

  async connect(phoneNumber) {
    try {
      const call = await voice.connect(token, {
        params: {
          To: '16289000355',
          From: '14243468978',
        },
      });
      // The call instance is provided by the SDK
      console.log('call', call);
    } catch (err) {
      console.log(err);
    }
  }

  async rejectCall(event) {
    console.log('hiii reject call', event);
    let sid = event.twi_call_sid;
    try {
      await voice.hangup(sid);
      console.log('Call rejected successfully');
    } catch (error) {
      console.error('Error disconnecting call:', error);
    }
  }

  async callMute(e) {
    const isMuted = await voice.mute(e);
    console.log('isMuted', isMuted);
  }

  async sendDigits(digit) {
    const digits = await voice.sendDigits(digit);
    console.log('digits', digits);
  }

  async callDisconnect(event) {
    console.log('hii disconnect', event);
    if (!this.state.callInvite) {
      console.warn('No call invite to reject');
    } else {
      await this.state.callInvite.reject();
      this.setState({ callInvite: null });
    }
  }

  render() {
    return <View>{/* Your component's JSX here */}</View>;
  }
}

const plivoInstance = new Plivo();
export default plivoInstance;

**Comment by bojandurmic** [comment]
I don't intend to be rude, but you can't bother to properly format your code, I can't bother to help you out.

**Comment by mhuynh5757** [comment]
Hey all, going to close this issue as stale for now. Thanks.
