### ISSUE TITLE
Urgent: Registering multiple tokens with different identifiers in the same device.

### ISSUE THREAD

**Issue by dianamariand92** [twilio/twilio-voice-react-native#327]
# Issue

## Pre-submission Checklist
- [ x] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [ x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [ x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
When I register more than one token, the SDK only receives incoming calls for the last token. For example: 

voice variable is for broadcast incoming calls and conference var is for specific incoming call

`
const voice = new Voice(); // 
const conference = new Voice();

 await voice.register(token, phones);
await conference.register(user_token, phones);
`

In the code, only the incoming calls for the user_token token are received in the application. 

The output of Xcode shows the register process for both tokens, but only the incoming calls for the latest register are received.

TRACE:Twilio:[Platform](0x16b56f000) : Registering for Twilio push notifications
Access Token:	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImN0eSI6InR3aWxpby1mcGE7dj0xIn0.eyJqdGkiOiJTSzVjZTBhYzczZDYyNTJmOTJiY2YwOWIyM2Q0OWVkMzdkLTE3MDkzMjE3OTMiLCJncmFudHMiOnsiaWRlbnRpdHkiOiJjZDRkM2E2N2I3N2VjZDJldXNlciIsInZvaWNlIjp7ImluY29taW5nIjp7ImFsbG93Ijp0cnVlfSwib3V0Z29pbmciOnsiYXBwbGljYXRpb25fc2lkIjoiQVBjODk5Mjk3NjRkNjVmOTk1NDVhMjNlOTIwMWFiZTI3MSJ9LCJwdXNoX2NyZWRlbnRpYWxfc2lkIjoiQ1I1Y2EzZjE5MGFjYzFjM2JhZGJmMTZkOGJlNDcxNGY4NiJ9fSwiaWF0IjoxNzA5MzIxNzkzLCJleHAiOjE3MDk0MDgxOTMsImlzcyI6IlNLNWNlMGFjNzNkNjI1MmY5MmJjZjA5YjIzZDQ5ZWQzN2QiLCJzdWIiOiJBQ2QwM2JlOTc0YjlmZDdkNGU0N2IyZWM3ODc4MTQyMGU5In0.S2sM1laM0JfdZKsTWyjlJmK-IJ_HErkeihlKGRp52TN
VoIP Registry Token:	9623541e957350f0f36ad7dcf2ea77cc85e06d036a422d589b8f3de35829ac5f

TRACE:Twilio:[Platform](0x16b33f000) : Registering for Twilio push notifications
Access Token:	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImN0eSI6InR3aWxpby1mcGE7dj0xIn0.eyJqdGkiOiJTSzVjZTBhYzczZDYyNTJmOTJiY2YwOWIyM2Q0OWVkMzdkLTE3MDkzMjE3OTMiLCJncmFudHMiOnsiaWRlbnRpdHkiOiJjYjRkNjkzOWIyYXBwIiwidm9pY2UiOnsiaW5jb21pbmciOnsiYWxsb3ciOnRydWV9LCJvdXRnb2luZyI6eyJhcHBsaWNhdGlvbl9zaWQiOiJBUGM4OTkyOTc2NGQ2NWY5OTU0NWEyM2U5MjAxYWJlMjcxIn0sInB1c2hfY3JlZGVudGlhbF9zaWQiOiJDUjVjYTNmMTkwYWNjMWMzYmFkYmYxNmQ4YmU0NzE0Zjg2In19LCJpYXQiOjE3MDkzMjE3OTMsImV4cCI6MTcwOTQwODE5MywiaXNzIjoiU0s1Y2UwYWM3M2Q2MjUyZjkyYmNmMDliMjNkNDllZDM3ZCIsInN1YiI6IkFDZDAzYmU5NzRiOWZkN2Q0ZTQ3YjJlYzc4NzgxNDIwZTkifQ.WFfCrDOp87FtJKAwf_Mxo4YSTEGnt3gbw0h2cz0rsKM
VoIP Registry Token:	9623541e957350f0f36ad7dcf2ea77cc85e06d036a422d589b8f3de35829ac5f

When I use the Javascript SDK it works.

## Reproduction Steps
1. Register two tokens

## Expected Behavior
Register both tokens and receive the incoming calls that are generated to all the tokens.

## Actual Behavior
Only the incoming calls of the latest token are received.

## Reproduction Frequency
100%

## Software and Device Information
**Please complete the following information.**
 Device: iPhone 13 pro
OS: iOS 17.3
{
"name": "ProspectX",
"version": "0.0.1",
"private": true,
"scripts": {
"android": "react-native run-android",
"ios": "react-native run-ios",
"lint": "eslint .",
"start": "react-native start",
"test": "jest",
"postinstall": "patch-package",
"setup-ios": "npx react-native setup-ios-permissions && cd ios && pod install",
"debug-build-android": "react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/ && cd android && ./gradlew assembleDebug && cd ..",
"release-build-android": "cd android && ./gradlew bundleRelease && cd .."
},
"dependencies": {
"@react-native-async-storage/async-storage": "^1.19.2",
"@react-native-firebase/app": "^18.3.0",
"@react-native-firebase/messaging": "^18.3.0",
"@react-navigation/bottom-tabs": "^6.5.8",
"@react-navigation/native": "^6.1.7",
"@react-navigation/native-stack": "^6.9.13",
"@twilio/voice-react-native-sdk": "^1.0.0-beta.3",
"@twotalltotems/react-native-otp-input": "^1.3.11",
"axios": "^1.4.0",
"libphonenumbers": "^1.3.0",
"moment": "^2.29.4",
"numeral": "^2.0.6",
"patch-package": "^8.0.0",
"react": "18.2.0",
"react-native": "0.72.4",
"react-native-calendar-picker": "^7.1.4",
"react-native-document-picker": "^8.2.1",
"react-native-dropdown-picker": "^5.4.6",
"react-native-file-viewer": "^2.1.5",
"react-native-fs": "^2.20.0",
"react-native-gifted-chat": "^2.4.0",
"react-native-image-picker": "^5.0.2",
"react-native-linear-gradient": "^2.8.2",
"react-native-paper": "^5.10.3",
"react-native-permissions": "^3.8.4",
"react-native-raw-bottom-sheet": "^2.2.0",
"react-native-render-html": "^6.3.4",
"react-native-responsive-screen": "^1.4.2",
"react-native-safe-area-context": "^4.7.1",
"react-native-screens": "^3.24.0",
"react-native-simple-dialogs": "^2.0.1",
"react-native-svg": "^13.12.0",
"react-native-svg-transformer": "^1.1.0",
"react-native-toast-message": "^2.1.6",
"react-native-track-player": "^4.0.1-nightly-47b2d08033563ef4d7e76a7f061c244ac3dba1ec",
"react-redux": "^8.1.2",
"redux": "^4.2.1",
"redux-persist": "^6.0.0",
"redux-thunk": "^2.4.2"
},
"reactNativePermissionsIOS": [
"Camera",
"Microphone",
"PhotoLibrary",
"Notifications",
"MediaLibrary"
],
"devDependencies": {
"@babel/core": "^7.20.0",
"@babel/preset-env": "^7.20.0",
"@babel/runtime": "^7.20.0",
"@react-native/eslint-config": "^0.72.2",
"@react-native/metro-config": "^0.72.11",
"@tsconfig/react-native": "^3.0.0",
"@types/react": "^18.0.24",
"@types/react-test-renderer": "^18.0.0",
"babel-jest": "^29.2.1",
"eslint": "^8.19.0",
"jest": "^29.2.1",
"metro-react-native-babel-preset": "0.76.8",
"prettier": "^2.4.1",
"react-test-renderer": "18.2.0"
},
"engines": {
"node": ">=16"
}
}

**Comment by mhuynh5757** [comment]
Hi @dianamariand92 you should remove your tokens from the issue description, they are considered secrets and should not be shared.

The issue that you're describing is intentional, a device cannot be registered to multiple client identities at the same time. If you need routing, your TwiML generation should handle this. For example, in your TwiML endpoint, you can listen for requests to "alice" and "bob", and then make a call to "charlie" which would be your registered device.

**Comment by dianamariand92** [comment]
Hi @mhuynh5757 thanks for your response, I changed the tokens. The problem is that Twilio only notifies at maximum 10 devices and if I have more than 10 devices it doesn't work. I assign the same identity to several users (more than 10), so everyone is notified, but sometimes I need to notify one specific user, so I need a specific token too. I believe this is a limitation, I will search about this on other platforms.
