### ISSUE TITLE
How to implement VoIP using this package and onesignal notification

### ISSUE THREAD

**Issue by dheerajgill25** [twilio/twilio-voice-react-native#345]
I want to show a call notification when the app is killed or in background mode like WhatsApp 
Thanks in advance

**Comment by mhuynh5757** [comment]
Hi @dheerajgill25 please fill out the issue template, it helps us tremendously knowing the context of your dev environment when asking for help or feature requests.

What platform are you targetting? iOS and Android? Or just one? This feature should be working on the latest version of the SDK.

**Comment by dheerajgill25** [comment]
I want to use both Android and iOS and I installed the latest SDK.

**Comment by mhuynh5757** [comment]
Hi @dheerajgill25 forgive me for being insistent, but I still need all the other information from the Issue Template about your development environment. Those questions I asked were just a few from the Issue Template.

Please see the Issue Template here: https://github.com/twilio/twilio-voice-react-native/blob/main/.github/ISSUE_TEMPLATE.md
