### ISSUE TITLE
I want to develop an app for person with speech disability. TTS is key. So during a call, he would send texts and other recipient will receive audio.

### ISSUE THREAD

**Issue by arsen037** [twilio/twilio-voice-react-native#350]
# Issue

Is there any method to send audio data to Twilio session with caller sid?

## Description 

Info: I tried "say" tag in Twiml, but it made the call ends.
for more easy way, I am looking for such interface to send audio data to call session.
Please help me on this.

Regards,
Arsen

**Comment by MykolaKobetiakCloudGenie** [comment]
@arsen037 
This one can be helpful: https://www.twilio.com/en-us/blog/twilio-conference-now-supports-announcements-html

**Comment by mhuynh5757** [comment]
Hi all, thanks for reaching out and discussing solutions. Unfortunately, this kind of question is outside the scope of this repository's GitHub Issues Page. For your query, you can reach out to your account manager if you have one, or create a support ticket via your Twilio account through the Twilio console.
