### ISSUE TITLE
Fullscreen Incoming Call Notifications with Interface

### ISSUE THREAD

**Issue by Itsadityaverma** [twilio/twilio-voice-react-native#353]
Hello devs,

I wanted to have fullscreen notifications just like a normal phone call, which will wake up the screen and ring like a call and give the interface to accept or reject the call, without opening the application or running in the background (yes after clicking accept it will surely redirect to the application, I am talking about the fullscreen notification)

I have created another fullscreen notification in one signal for VOIP, but they are saying they cannot do anything in that, as we need to implement code specifically for Android and ios  instead of doing it in react native and then converting it

This is a very urgent and main requirement I am having right now, please provide me the fix or any other solutions you have

Thanks

**Comment by Itsadityaverma** [comment]
add on - I am using one signal for notification, and there I have created a VOIP notification separately but it's not working.
Also my users mostly keep the phone on silent as they do the field work, so they wanted to have a fullscreen notification, which can alert the user properly that yeah call is coming, and they can directly pick or end without opening the application.

Provide me the fix otherwise suggest me the alternative to do this or any same thing.
Thanks again

**Comment by mhuynh5757** [comment]
Hi @Itsadityaverma unfortunately this kind of design question is outside the scope of this repo, that functionality is not baked into the SDK and there are no plans to do so. It would be scope creep in terms of the design of this library.

Doing a quick Google search for your feature turns up some results, here's one I found and skimmed through briefly. It might assist you: https://stackoverflow.com/questions/77271376/how-to-implement-a-full-screen-notification-like-whatsapp-call-in-react-native-a

Full disclaimer that we are not associated with any of the links or participants in that StackOverflow post.
