### ISSUE TITLE
push notification call - use version 1.0.0-beta.4

### ISSUE THREAD

**Issue by phongdev20** [twilio/twilio-voice-react-native#355]
What are the steps to handle when initiating a call, sending notifications on the application, and how to handle the recipient receiving call notifications when the application is turned off?

**Comment by mhuynh5757** [comment]
Hi @phongdev20 could you please fill out the Issue Template so we can have the full context of your development environment? It helps tremendously with debugging issues.

Also, I'm having a hard time understanding your issue? Are you encountering problems trying to make outgoing calls and receiving incoming calls? Or do you need a guide to getting started?

**Comment by mhuynh5757** [comment]
Hi @phongdev20 are you still having this issue? I'd like to close it as stale for now, please feel free to reopen or create a new issue if you need further assistance.
