### ISSUE TITLE
Cannot read property 'voice_connect_android' of null", using expo

### ISSUE THREAD

**Issue by dialmyline** [twilio/twilio-voice-react-native#360]
# Issue
Cannot read property 'voice_connect_android' of null", using expo react-native

## Pre-submission Checklist
- [x] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
voice.connect() throws errors when making outgoing call "Cannot read property 'voice_connect_android' of null", using expo"

Cannot read property 'voice_getAudioDevices' of null

## Reproduction Steps
voice.connect() throws errors when making outgoing call

## Expected Behavior
voice.connect() throws errors when making outgoing call

## Actual Behavior
voice.connect() throws errors when making outgoing call on button click

## Reproduction Frequency
throws errors when making outgoing call

## Screenshots
![Screenshot 2024-04-21 134708](https://github.com/twilio/twilio-voice-react-native/assets/156711413/5149641d-ee5f-4e56-9d97-19dbb4de496e)

## Software and Device Information
**Please complete the following information.**
 - Device: [e.g. iPhone 12, Pixel 3]
 - OS: [e.g. iOS 16, Android API Level 31]
 - React version: [e.g. 18.1.0]
 - React Native version: [e.g. 0.70.9]
 - Node version: [e.g. 16.18.1]
 - npm or yarn version: [e.g. 8.19.2, 1.22.19]

**Comment by solidneeds** [comment]
![Screenshot 2024-04-21 134708](https://github.com/twilio/twilio-voice-react-native/assets/156711413/13e989ab-363a-47b6-9e46-c31c5cbbc0ba)

**Comment by mhuynh5757** [comment]
Hi @solidneeds thanks for bringing this to our attention. It seems like this issue results from using Expo, is it possible for you to test using the Test App baked into this repo, just to verify? It is located in the `test/app/` folder.

**Comment by solidneeds** [comment]
> Hi @solidneeds thanks for bringing this to our attention. It seems like this issue results from using Expo, is it possible for you to test using the Test App baked into this repo, just to verify? It is located in the `test/app/` folder.

i get this error 
![Screenshot 2024-04-23 105423](https://github.com/twilio/twilio-voice-react-native/assets/156711413/2fa0c46b-3a09-4b66-acc3-9aa33220cbdd)

**Comment by SidMasih** [comment]
@solidneeds  did you resolve this? 

Pretty sure that this will only work with prebuild expo (aka no expo go and a few conifg requirements)

**Comment by SidMasih** [comment]
https://github.com/twilio/twilio-voice-react-native/issues/305 check this out if anyone is running into this issue

**Comment by mhuynh5757** [comment]
Hey all, thanks for the community problem solving. I'd like to close this issue as stale for now, especially since it seems to be an Expo related issue. I've discussed with the team to try and prioritize Expo support for the SDK, but I cannot make any promises at this time. Thanks for your understanding.

**Comment by MuhammadIqbalDev** [comment]
> @solidneeds did you resolve this?
> 
> Pretty sure that this will only work with prebuild expo (aka no expo go and a few conifg requirements)

It does not!
