### ISSUE TITLE
Receiving calls stops working on the iPhone after a while.

### ISSUE THREAD

**Issue by greenraze13** [twilio/twilio-voice-react-native#369]
# Issue

## Pre-submission Checklist
- [ yes ] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [ Yes] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and  

## Description 
I am testing calls from Android to iOS. The call is received on the iPhone while in the foreground and background. However, after some calls, it stops working in the app's killed state on the iPhone. I delete the app from the iPhone and then reinstall it. The call works fine again on the iPhone in the killed state, but after some calls, no call is received in the app's killed state. The call always works fine in the foreground.
In xcode project in  sigining and capbilities  background modes on for Voip.That why app works fine for a while.
I have integrated the sentry Where received  error  related to voip 
NSInternalInconsistencyException: Killing app because it never posted an incoming call to the system after receiving a PushKit VoIP push.

## Reproduction Steps
1. Install app on android 
2. Call from android client to client 
3.  Receive call on   iphone app
4.  Call will receive on iphone but after some calls not receiving  while iphone app is in killed state  (fine in foreground state )

## Expected Behavior
Iphone app should  receive  the call while in killed state every time

## Actual Behavior
 On start of testing call from android to iphone app   worked fine on both fore ground and killed state. But after some times / some calls iphone app is not receiving the calls  while in killed state. 

## Reproduction Frequency
 Issue can be produce by calling multiple times  from android to iphone.Pick some calls and after some times iphone app will stop works while app is in killed state.

 
## Software and Device Information
**Please complete the following information.**
 -  Calling device   Android pixel 6 android 13               "react-native": "0.72.6", 
 - Receiving device iPhone 15 with ios version 17+.          "react-native": "0.72.6", 
 
 With yarn 
twilio-voice-react-native@1.0.0

**Comment by bobiechen-twilio** [comment]
Hi @greenraze13 

The message `NSInternalInconsistencyException: Killing app because it never posted an incoming call to the system after receiving a PushKit VoIP push.` indicates that the component that handles the iOS PushKit events might not be instantiated to report the VoIP push notification to the iOS CallKit framework as an incoming call.
Is your application calling the [Voice.initializePushRegistry() method](https://github.com/twilio/twilio-voice-react-native/blob/main/test/app/src/hook.ts#L437) or handles the PushKit events in a different module?

**Comment by greenraze13** [comment]
Hi @bobiechen-twilio 
Thanks for your response. I am calling    await voice.initializePushRegistry() function like below 
This is useVoice hook.
`React.useEffect(() => {
    voice.getVersion().then(setSdkVersion);
    const bootstrap = async () => {
      if (Platform.OS === 'ios') {
        **await voice.initializePushRegistry();**
      }
      const calls = await voice.getCalls();
      for (const call of calls.values()) {
        console.log('existing call', call.getCustomParameters());
        callHandler(call);
      }
      const callInvites = await voice.getCallInvites();
      for (const callInvite of callInvites.values()) {
        console.log('existing call invite', callInvite.getCustomParameters());
        callInviteHandler(callInvite);
      }
    };
    bootstrap();
    voice.on(Voice.Event.CallInvite, callInviteHandler);
    voice.on(Voice.Event.AudioDevicesUpdated, audioDevicesUpdateHandler);
    return () => {
      voice.off(Voice.Event.CallInvite, callInviteHandler);
      voice.off(Voice.Event.AudioDevicesUpdated, audioDevicesUpdateHandler);
    };
  }, [
    audioDevicesUpdateHandler,
    callHandler,
    callInviteHandler,
    voice,
  ]);`

**Comment by greenraze13** [comment]
Hi @bobiechen-twilio 
Any update here ?

**Comment by bobiechen-twilio** [comment]
Hi @greenraze13 

Have you tried the [example app](https://github.com/twilio/twilio-voice-react-native/tree/main/test/app) with your environment? The example app is able to receive incoming calls when the app was previously terminated

**Comment by greenraze13** [comment]
@bobiechen-twilio 
Hi Thanks .I have tried that its working fine now.

**Comment by bobiechen-twilio** [comment]
Glad to see it's working for you now @greenraze13 
Is it possible for you to share the fix you did in your app so the terminated app is able to wake up and handle the incoming call?

**Comment by greenraze13** [comment]
@bobiechen-twilio 
Yes in killed state App is working fine and now every time and its receiving calls
The thing is now  I awaking this await voice.initializePushRegistry()  in App.tsx file.

**Comment by bobiechen-twilio** [comment]
Hi @greenraze13 

From what I can see the call notification was sent to the mobile client successfully. Is your app able not receiving call notification even when it's active?
A while ago we received a report saying their iOS app stopped receiving call notifications and only started to receive push notification again after uninstalling and installing the app again. Note that in this case they also observed that the iOS PushKit device token is different than the one before the reinstallation.
We have reached out to Apple and they confirmed there was a bug and was fixed in iOS 17, although they did not explicitly what versions have the issue and the exact version it was fixed.

Can you try uninstall and reinstall the app, and see if the notification started to work again? And if it's not too much trouble, can you use the `Voice.getDeviceToken()` method to capture the iOS device token before and after the reinstallation so we can confirm it's the root cause?

**Comment by greenraze13** [comment]
HI @bobiechen-twilio 
Thanks for you response.
I am using iPhone 11 Pro Max iOS 17.6.1
const tokenVoice = await voice.getDeviceToken();

and tokenVoice is always empty

**Comment by bobiechen-twilio** [comment]
This means the PushRegistry module is never initialized, which could also be the reason your app is not receiving the push notification from iOS.

**Comment by greenraze13** [comment]
@bobiechen-twilio 
But call always receiving when app is in foreground /active It shows full screen call Native UI. Not the small notification on top of mobile. 

And I have noticed the issue on sentry 
<img width="1332" alt="Screenshot 2024-10-09 at 13 18 56" src="https://github.com/user-attachments/assets/d18b48e7-705f-40f0-9d3d-9cc1d0b73f9e">

I am doing   await defaultStore.dispatch(bootstrapPushRegistry()); in app.tsx file 
and this is main function 
export const bootstrapPushRegistry = createTypedAsyncThunk<
  void,
  void,
  {rejectValue: BootstrapPushRegistryRejectValue}
>(bootstrapPushRegistryActionTypes.prefix, async (_, {rejectWithValue}) => {
  if (Platform.OS !== 'ios') {
    return;
  }

  const initializeResult = await settlePromise(voice.initializePushRegistry());
  if (initializeResult.status === 'rejected') {
    console.log('INITIALIZE_PUSH_REGISTRY_REJECTED');
    return rejectWithValue({
      reason: 'INITIALIZE_PUSH_REGISTRY_REJECTED',
      error: miniSerializeError(initializeResult.reason),
    });
  } else {
    console.log('INITIALIZE_PUSH_REGISTRY Success');
  }
});
It gives success log when I open the app


If the PushRegistry module is never initialized then how I can debug this ?

**Comment by bobiechen-twilio** [comment]
The exception does indicate that most likely the iOS PushRegistry module is not initialized and ready to handle the VoIP push notification and report to iOS CallKit in time. I don't have full knowledge of your implementation, but the `createTypedAsyncThunk` method seems to me is not initializing and returning in time. Please check this out in our example app.

**Comment by greenraze13** [comment]
I have commented this createTypedAsyncThunk and 

I have done this await voice.initializePushRegistry() directly into useEffect of app.tsx, Still same call not receiving when app is closed/killed

**Comment by vilnius1998** [comment]
> Hi @greenraze13
> 
> From what I can see the call notification was sent to the mobile client successfully. Is your app able not receiving call notification even when it's active? A while ago we received a report saying their iOS app stopped receiving call notifications and only started to receive push notification again after uninstalling and installing the app again. Note that in this case they also observed that the iOS PushKit device token is different than the one before the reinstallation. We have reached out to Apple and they confirmed there was a bug and was fixed in iOS 17, although they did not explicitly what versions have the issue and the exact version it was fixed.
> 
> Can you try uninstall and reinstall the app, and see if the notification started to work again? And if it's not too much trouble, can you use the `Voice.getDeviceToken()` method to capture the iOS device token before and after the reinstallation so we can confirm it's the root cause?

I am currently encountering the issue with Voip notifications not working after some time when the app is in the background or terminated. However, if I uninstall and reinstall the dev build, it works again. I'm running iOS 18.0.1
