### ISSUE TITLE
when make an outgoing call, speaker audio is selected, and there is no sound

### ISSUE THREAD

**Issue by devBjn** [twilio/twilio-voice-react-native#371]
# Issue
The first time logged in to the app, I saw that the audio type speaker was default and there was no sounde. At ringing listener, I already set the earpiece but it's not updated. 

      outgoingCall.callEvent.on("ringing", async () => {
          console.log("ringing");
          if (selectedDevice.type === "speaker") {
            await earpiece.select();
          }
        });

        outgoingCall.callEvent.on("connected", async () => {
          console.log("connected");

          setTimerRunning(true);
          handleCallEvent(
            outgoingCall?.callEvent?.getState(),
            outgoingCall?.callEvent?.isMuted()
          );
        });

<img width="609" alt="Screenshot 2024-06-01 at 22 19 51" src="https://github.com/twilio/twilio-voice-react-native/assets/63631036/13fa86e7-7a98-463d-a8ce-1c9dad3c5789">

## Pre-submission Checklist
- [ ] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [ ] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [ ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
A clear and concise description of what the issue is.

## Actual Behavior
What actually happens.

## Reproduction Frequency
Is the reproducibility of the issue deterministic? If not, what percentage of the time does the issue occur? In how many attempts was the issue observed?

## Software and Device Information
**Please complete the following information.**
 - Device: [e.g. iPhone 12, Pixel 3]
 - OS: [e.g. iOS 16, Android API Level 31]
 - React version: [e.g. 18.1.0]
 - React Native version: [e.g. 0.70.9]
 - Node version: [e.g. 16.18.1]
 - npm or yarn version: [e.g. 8.19.2, 1.22.19]

**Comment by mhuynh5757** [comment]
Hi @devBjn, thanks for bringing this to our attention. Please fill out the entire Issue Template, including the device info and development environment. It helps us with debugging and addressing your issue.

**Comment by mhuynh5757** [comment]
Hello @devBjn I would like to close this issue as stale for now. Please feel free to add the additional info and reopen the issue if you need further assistance.
