### ISSUE TITLE
How to change the ringtone of an incoming call on the phone, depending on the parameters of the incoming call?

### ISSUE THREAD

**Issue by SumDanil** [twilio/twilio-voice-react-native#372]
## Description 
Can I change the ringtone of the phone during an incoming call, depending on the parameters of the incoming call (parameters that come in the push notification)? For example, for everyday incoming calls, I want to use one ringtone, and when I want to highlight an incoming call, so that the user understands that it is a special incoming call, I play another ringtone on the phone. If it is possible, please tell me how to do it, thanks in advance

**Comment by afalls-twilio** [comment]
@SumDanil in order to do this, you would need to modify the native code... you cannot do this from JS.

**Comment by mhuynh5757** [comment]
Hi @SumDanil do you still need assistance with this? If not, I'd like to close this issue as stale. Thanks!
