### ISSUE TITLE
How to change heading text on voip notification IOS 

### ISSUE THREAD

**Issue by greenraze13** [twilio/twilio-voice-react-native#373]
# Issue

## Pre-submission Checklist
- [ yes] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [ yes] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [yes ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 

I am using Twilio Voice React Native for incoming calls on iPhone. When an incoming call arrives, it shows the VoIP notification. I want to change the title of that notification.

Currently, it shows:
'App Name Audio Call
Client ID: c78'

I want to change it to 'You have an audio call from client c78.'

I have also attached a screenshot of iphone notification where i wants to change.

In Android, I have changed it in the library files, and there it's working fine.

Thanks.

## Reproduction Steps
1. Call from one mobile to iphone 
2. Call notification appears on iphone 
3. need to change the title of that notification 
 
 
 

## Screenshots
 
<img width="513" alt="Screenshot 2024-06-06 at 16 17 22" src="https://github.com/twilio/twilio-voice-react-native/assets/51110762/a4bfe473-7e0a-483a-9d7c-2ac46181bd13">

**Comment by bobiechen-twilio** [comment]
Hi @greenraze13 

The header (app name) is controlled by the iOS CallKit framework and there is nothing the SDK can do to update it, however the default caller name "client:xxxx" can be changed by the follow ways:
- You can programmatically update the handle string before it is passed to the iOS CallKit as an incoming call: https://github.com/twilio/twilio-voice-react-native/blob/main/ios/TwilioVoiceReactNative%2BCallKit.m#L70
- You can also use the `CallInvite.updateCallerHandle()` method during runtime to update the display name: https://github.com/twilio/twilio-voice-react-native/blob/main/src/CallInvite.tsx#L601
