### ISSUE TITLE
How to change voip title on ios 

### ISSUE THREAD

**Issue by greenraze13** [twilio/twilio-voice-react-native#374]
**This is not a issue.**

 I am using Twilio Voice React Native for incoming calls on iPhone. When an incoming call arrives, it shows the VoIP notification. I want to change the title of that notification.

Currently, it shows:

'App Name Audio Call

Client ID: c89'
with accept reject button 

I want to change it to 'You have an audio call from client c78.'

I have also attached a screenshot of iphone notification where i wants to change.
<img width="513" alt="Screenshot 2024-06-06 at 16 17 22" src="https://github.com/twilio/twilio-voice-react-native/assets/51110762/10eb05cf-43ed-46cd-8ff1-fdddf4ff0417">

In Android, I have changed it in the library files, and there it's working fine.

Thanks.

**Comment by greenraze13** [comment]
Hi @bobiechen-twilio 
Can you please help me here.

Thanks

**Comment by bobiechen-twilio** [comment]
HI @greenraze13 

For the title it will always be the app display name. This is controlled by the iOS CallKit framework and there is no way to programmatically update the value.
For the caller name, there are a few ways to update the value:
- You can directly modify the string value that is being passed to the iOS CallKit when reporting a new incoming call: https://github.com/twilio/twilio-voice-react-native/blob/main/ios/TwilioVoiceReactNative%2BCallKit.m#L69
- We also have a method in the React Native layer `CallInvite.updateCallerHandle()` to update the value during runtime: https://github.com/twilio/twilio-voice-react-native/blob/main/src/CallInvite.tsx#L601

**Comment by bobiechen-twilio** [comment]
close as dup #373
