### ISSUE TITLE
CallInvite issue in release mode

### ISSUE THREAD

**Issue by shrutigarg-reactnative** [twilio/twilio-voice-react-native#375]
CallInvite event listener work fine in debug mode but in release mode it is not triggering. Although I receive push notification in release mode.

**Comment by bobiechen-twilio** [comment]
Hi @shrutigarg-reactnative 

Please complete the questions from the issue template next time.
I have a feeling the Push Credential in the access token is not changed to a production one (without the sandbox option): [Voice iOS quickstart readme](https://github.com/twilio/voice-quickstart-ios?tab=readme-ov-file#6-create-a-push-credential-with-your-voip-service-certificate)

**Comment by shrutigarg-reactnative** [comment]
Issue is in android

**Comment by mhuynh5757** [comment]
Hi @shrutigarg-reactnative, could you please provide more information? The development info we ask in the Issue Template is not optional, it helps us debug issues.

For example, React Native versions, Android versions, etc.

**Comment by mhuynh5757** [comment]
Hello, I would like to close this issue as stale for now. Please feel free to add the required info and reopen the issue if you are still in need of assistance.
