### ISSUE TITLE
The ringtone for the IOS application does not change. 

### ISSUE THREAD

**Issue by AlekseiEDT** [twilio/twilio-voice-react-native#376]
## Description 
Hi everyone. I was trying to change the ringtone for an app (ios) using a key (callKitRingtoneSound). Here is my code
```
  import { Voice } from '@twilio/voice-react-native-sdk';
  
  const token = getAccessToken();
  const voice = new Voice();
  
  voice.setCallKitConfiguration({'callKitRingtoneSound': 'tone‘})
  
  await voice.register(token);
```
This code works without any errors, but the ringtone does not change. I tried with different file formats (wav, mp3)

Here is my file in Xcode
![image](https://github.com/twilio/twilio-voice-react-native/assets/138133071/0229227e-340f-411d-815d-65c0d2d4e820)

I added tone.wav to xcode in this way 
![image](https://github.com/twilio/twilio-voice-react-native/assets/138133071/dca0c0e2-ea23-4462-acd9-edb62adfc66d)
then
![image](https://github.com/twilio/twilio-voice-react-native/assets/138133071/4d7eec09-3c46-4928-8614-be572c3b6096)

## Software and Device Information
**Please complete the following information.**
 - Device: [e.g. iPhone 8]
 - OS: [e.g. iOS 16]
 - React version: [e.g. 18.2.0]
 - React Native version: [e.g. 0.71.6]

## Additional Context
Also I tried these docs (https://github.com/twilio/twilio-voice-react-native/blob/latest/docs/play-outgoing-call-ringback-tone.md) and in this case everything works fine

**Comment by bobiechen-twilio** [comment]
Hi @AlekseiEDT 

Other than including the file into the Xcode project, the app also needs to specify the file extension in the `setCallKitConfiguration()` method.
