### ISSUE TITLE
iOS: Incoming call is not received when the app is terminated (killed state)

### ISSUE THREAD

**Issue by manpreetaj** [twilio/twilio-voice-react-native#379]
# Issue

Incoming calls are not received when the application is not running (killed state). However, I can receive and answer calls when the app is in the active or background state.

## Pre-submission Checklist
- [x] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
 Calling the Voice.initializePushRegistry() method as soon as the Voice module is initialized as follows for iOS:

```
const voice = new Voice();
  await voice.initializePushRegistry(); 
  
  //Then registering accessToken
  await voice.register(accessToken)
```

SDK version:  @twilio/voice-react-native-sdk": "^1.0.0"

## Expected Behavior
Incoming call must be shown when application is not running. 

## Actual Behavior
When trying to receive an incoming call while the app is in the killed state, the React Native console log shows :
 BUNDLE  ./index.js
 
 But no further information is shown. 

## Reproduction Frequency
Is the reproducibility of the issue deterministic? If not, what percentage of the time does the issue occur? In how many attempts was the issue observed?

## Software and Device Information
**Please complete the following information.**
 - Device: iPhone 7 Plus
 - OS: 15.7.9
 - React version: 18.2.0
 - React Native version: 0.72.6
 - Node version: v22.1.0
 - npm or yarn version: 10.7.0

**Comment by bobiechen-twilio** [comment]
HI @manpreetaj 

Thanks for reaching out. You haven't provided any Twilio Call SID but based on the description very likely your app has the same symptom as this issue: https://github.com/twilio/twilio-voice-react-native/issues/369
Please check out the example app of the repo and make sure your app handles the iOS push-registry initialization at launch.

**Comment by manpreetaj** [comment]
Hi @bobiechen-twilio 
Thanks for your response.

Yes, my app handles the iOS push-registry initialization at launch (in app.tsx file).

Now, I tested my app on an iPhone 11 with iOS version 17.5.1, and incoming calls are working fine even when the app is in the killed state. I noticed that the issue was only with iOS 15.7.9 on an iPhone 7 Plus.


Thanks
