### ISSUE TITLE
Missed Call

### ISSUE THREAD

**Issue by shrutigarg-reactnative** [twilio/twilio-voice-react-native#383]
Any event where I can get missed call callback

**Comment by bobiechen-twilio** [comment]
Hi @shrutigarg-reactnative 

Please follow the issue template and fill out information so the team can better help you. Thanks.

**Comment by mhuynh5757** [comment]
Hey all, going to close this issue as stale for now. Please feel free to reach out again if you need further assistance. I would like to note that going forward, if the Issue Template is not used properly, the team has decided to close Issues that do not use the template without warning. Thanks for your understanding.
