### ISSUE TITLE
Could not find com.getkeepsafe.relinker:relinker:1.2.2.

### ISSUE THREAD

**Issue by corasphinx** [twilio/twilio-voice-react-native#387]
My steps are very simple.
react-native init exampleApp
npm install react-native-twilio-programmable-voice
react-native run-android
-----------------------------------------
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.getkeepsafe.relinker:relinker:1.2.2.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/com/getkeepsafe/relinker/relinker/1.2.2/relinker-1.2.2.pom
       - https://repo.maven.apache.org/maven2/com/getkeepsafe/relinker/relinker/1.2.2/relinker-1.2.2.pom
       - file:/D:/z/front/node_modules/jsc-android/dist/com/getkeepsafe/relinker/relinker/1.2.2/relinker-1.2.2.pom
       - https://dl.google.com/dl/android/maven2/com/getkeepsafe/relinker/relinker/1.2.2/relinker-1.2.2.pom
       - https://www.jitpack.io/com/getkeepsafe/relinker/relinker/1.2.2/relinker-1.2.2.pom
     Required by:
         project :app > project :react-native-twilio-programmable-voice > com.twilio:voice-android:4.5.0

**Comment by mhuynh5757** [comment]
Hi @corasphinx, that's not our package. Please refer to this step in our README: https://github.com/twilio/twilio-voice-react-native?tab=readme-ov-file#installation
