### ISSUE TITLE
[Android] Bluetooth Headset keys not able to answer/reject incoming calls

### ISSUE THREAD

**Issue by thetyagiayush** [twilio/twilio-voice-react-native#390]
We have integrated the Twilio Voice SDK into our React Native project, and while it mostly functions as expected, we've encountered an issue with Bluetooth headsets on Android devices. When a call comes in, pressing the buttons on the Bluetooth headset doesn't affect the call notification. Ideally, the headset buttons should allow us to accept or reject the call. I've verified that this isn't a problem with the Bluetooth headset itself, as it works correctly for answering regular cellular calls.

- [ YES] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [YES] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [YES] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

I have also confirmed that Bluetooth works for VOIP calls once I manually accept the call from the notification. I can switch to my Bluetooth device, use its microphone, and listen to the caller's audio through the headset. However, the issue remains that the answer/reject functionality via the headset buttons is not working.

## Reproduction Steps
1. Connect a bluetooth device to android
2. Make an inbound call
3. Press the keys on bluetooth device

## Expected Behavior
Should ideally answer or reject the call according to the key pressed.

## Actual Behavior
Nothing happens on key press

## Reproduction Frequency
100%

## Software and Device Information
 - Device: Nothing Phone 1
 - OS: Android 14
 
 Any help is appreciated!

**Comment by mhuynh5757** [comment]
Hello @thetyagiayush thanks for reaching out to us. I've internally asked our Android expert to weigh in. In the meantime, could you also provide some more version info, like React Native version, are you using expo, etc.

**Comment by thetyagiayush** [comment]
@mhuynh5757 Hey, I am using React native 0.74.3 and No, I am not using Expo

**Comment by afalls-twilio** [comment]
@thetyagiayush AudioSwitch does not support bluetooth device keys. Those tend to be manufacturer specific. AudioSwitch is open source, which you can modify to support your bluetooth headset keys.

https://github.com/twilio/audioswitch

**Comment by mhuynh5757** [comment]
Hey all, going to close this question as answered for now. Please reach out if you need further assistance.
