### ISSUE TITLE
How to get callinvite when there is incoming call when the app is in kill mode

### ISSUE THREAD

**Issue by ankitCompunnel** [twilio/twilio-voice-react-native#391]
Hii team,

I am struggling to manage the call when there is incoming call when the app is kill state.
For foreground and background it works fine but in kill state does not work.

import React, { useEffect, useState } from "react";
import { Text, View, Dimensions, Image, Linking, Alert, AppState, } from "react-native";
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";
import { createNativeStackNavigator } from "@react-navigation/native-stack";
import { Voice, CallInvite, Call } from '@twilio/voice-react-native-sdk';
import { RFValue } from "react-native-responsive-fontsize";
import messaging from '@react-native-firebase/messaging';

// redux
import { useDispatch } from "../redux/store";
import { setCallInvite, setIncomingMessageData } from "../redux/slices/user";

import { StaticMessage } from "../_helpers/constants";
import { ThemeColor, FontName } from "../_helpers/GlobalStyle";

import HistoryScreen from "./History/HistoryScreen";
import MoreScreen from "./More/MoreScreen";
import UserProfile from "./UserProfile/UserProfile";
import KeyPadScreen from "./KeyPad/KeypadScreen";
import ContactsScreen from "./Contacts/ContactsScreen";
import ContactsDetailsScreen from "./Contacts/ContactsDetailsScreen";
import IncomingCall from "./IncomingCallScreen/IncomingCall";
import { useNavigation } from "@react-navigation/native";
import HistoryDetailsScreen from "./History/HistoryDetailsScreen";

const height = Dimensions.get("window").height;

function ChatScreen() {
  return (
    <View style={{ flex: 1, justifyContent: "center", alignItems: "center" }}>
      <Text>Home Screen!</Text>
    </View>
  );
}

const Tab = createBottomTabNavigator();
const Stack = createNativeStackNavigator();

export default function HomeTabScreen() {

  const voice = new Voice();
  const dispatch = useDispatch()
  const navigation = useNavigation()

  useEffect(() => {
    const unsubscribeMessaging = messaging().onMessage(async remoteMessage => {
      console.log("remoteMessage===", remoteMessage)
      dispatch(setIncomingMessageData(remoteMessage))
    });
    const handleCallInvite = (invite) => {
      dispatch(setCallInvite(invite))
      console.log("invite----", invite)
      navigation.navigate("IncomingCall")

      // Listen for call invite cancellation
      invite.on('cancelled', () => {
        console.log('Call invite canceled');
        dispatch(setCallInvite(null));
        navigation.navigate("Keypad"); // Navigate back if the call is canceled
      });

      // Listen for call invite cancellation
      invite.on('accepted', (responsive) => {
        console.log('Call invite accepted',responsive);
        dispatch(setCallInvite(responsive));
        navigation.navigate("Keypad"); // Navigate back if the call is canceled
      });

      // Optionally, listen for other events if needed
      invite.on('notificationTapped', (pressed) => {
        console.log('notificationTapped', pressed);
        // navigation.navigate("Keypad");
        // Handle acceptance logic here
      });
    };
    voice.on('callInvite', handleCallInvite)

  }, []);

  return (
    <Stack.Navigator
      screenOptions={{
        headerTitleAlign: "left",

        headerStyle: {},
        headerTintColor: "#353535",
        headerTitleStyle: {
          fontWeight: "bold",
          fontSize: 16,
          headerTitleAlign: "left",
        },
        labelStyle: {
          fontSize: 16,
          headerTitleAlign: "left",
        },
        headerBackTitleVisible: false,
      }}
    >
      <Stack.Screen
        name="Home"
        component={HomeTabs}
        initialParams={{ itemId: 42 }}
        options={{ headerShown: false, headerBackTitle: "", }}
      />
      <Stack.Screen
        name="Profile"
        component={UserProfile}
        initialParams={{ itemId: 42 }}
        options={{ headerShown: false, headerTitleAlign: "left", }}
      />
      <Stack.Screen
        name="ContactsDetails"
        component={ContactsDetailsScreen}
        initialParams={{ itemId: 42 }}
        options={{ headerShown: false, headerTitleAlign: "left", }}
      />

      <Stack.Screen
        name="IncomingCall"
        component={IncomingCall}
        initialParams={{ itemId: 42 }}
        options={{ headerShown: false, headerTitleAlign: "left", }}
      />
      <Stack.Screen
        name="HistoryDetails"
        component={HistoryDetailsScreen}
        initialParams={{ itemId: 42 }}
        options={{ headerShown: false, headerTitleAlign: "left", }}
      />
    </Stack.Navigator>
  );
}

const HomeTabs = ({ navigation }) => {

  const getTabBarIcon = (route, focused) => {
    let iconName;

    if (route.name === "History") {
      iconName = focused
        ? require("../assets/images/call_history_Active.png")
        : require("../assets/images/call_history.png");
    } else if (route.name === "Contacts") {
      iconName = focused
        ? require("../assets/images/contact-book_active.png")
        : require("../assets/images/contact-book.png");
    } else if (route.name === "Keypad") {
      iconName = focused
        ? require("../assets/images/dial-pad-active.png")
        : require("../assets/images/dial-pad.png");
    } else if (route.name === "Lookup") {
      iconName = focused
        ? require("../assets/images/loupe-active.png")
        : require("../assets/images/loupe.png");
    } else if (route.name === "More") {
      iconName = focused
        ? require("../assets/images/more-active.png")
        : require("../assets/images/more.png");
    }
    return (
      <Image
        resizeMode="contain"
        style={{ width: 25, height: 25 }}
        source={iconName}
      />
    );
  };

  return (
    <Tab.Navigator
      initialRouteName={"History"}
      screenOptions={({ route }) => ({
        tabBarActiveTintColor: "#3868E9", // Color for active tab
        tabBarInactiveTintColor: "black", // Color for inactive tab
        tabBarStyle: [
          {
            display: "flex",
          },
          null,
        ],
        headerTitleAlign: "left",
        labelStyle: {
          fontSize: RFValue(16, height),
        },
        tabBarIcon: ({ focused }) => getTabBarIcon(route, focused),
      })}
    >
      <Tab.Screen
        name="History"
        component={HistoryScreen}
        options={{
          headerTintColor: ThemeColor.PrimaryGrey,
          headerTitleStyle: {
            fontSize: RFValue(20, height),
            fontFamily: FontName.Bold,
          },
          headerShown: false,
          tabBarLabel: "History",

        }}
      />
      <Tab.Screen
        name="Keypad"
        component={KeyPadScreen}
        options={{
          headerTintColor: ThemeColor.PrimaryGrey,
          headerTitleStyle: {
            fontSize: RFValue(20, height),
            fontFamily: FontName.Bold,
          },
          headerShown: false,
          headerTitleAlign: "left",
          tabBarLabel: "Keypad",
        }}
      />
      <Tab.Screen
        name="Contacts"
        component={ContactsScreen}
        initialParams={{
          searchKeyword: "",
          company: [],
          jobCategory: [],
          assignmentType: [],
        }}
        options={{
          headerTintColor: ThemeColor.PrimaryGrey,
          headerTitleStyle: {
            fontSize: RFValue(20, height),
            fontFamily: FontName.Bold,
          },
          headerShown: false,
          tabBarLabel: "Contacts",
        }}
      />

      {/* <Tab.Screen
        name="Lookup"
        component={ChatScreen}
        options={{
          headerTintColor: ThemeColor.PrimaryGrey,
          headerTitleStyle: {
            fontSize: RFValue(20, height),
            fontFamily: FontName.Bold,
          },
          headerShown: true,
          headerTitleAlign: "left",
          tabBarLabel: "Lookup",
        }}
      /> */}
      <Tab.Screen
        name="More"
        component={MoreScreen}
        options={{
          headerTintColor: ThemeColor.PrimaryGrey,
          headerTitleStyle: {
            fontSize: RFValue(20, height),
            fontFamily: FontName.Bold,
          },
          headerShown: false,
          headerTitleAlign: "left",
          tabBarLabel: "More",
        }}
      />

    </Tab.Navigator>
  );
};

In my useEffect I am getting the call invite and storing in my store by which i am able to handle the call like accept,  reject, disconnect , hold, mute and speaker but when there is incoming call when app is kill mode and I tap notification it redirects to me the app but call invite does not work and I am able to handle call action in my incoming call screen.
And I also want to redirect to incoming call screen when it in kill mode. 
So guy's can you help me out. Is there any event or function to be called or any configuration need to add in my android folder for this. 

And I also want to disconnect the call when the app is being killed . Currently when I kill the app call is ongoing and state get's destroyed in my app which i can't handle the call action any more. 

Note - This issue is only in android

**Comment by mhuynh5757** [comment]
Hi @ankitCompunnel please fill out the issue template instead of removing it and pasting all your code. Please also format your code. The info in the issue template is critical to us debugging your issue.

**Comment by ankitCompunnel** [comment]
@mhuynh5757 , It's very difficult to give my all code template.
Can you just let me know that how can i get the "callinvite" after clicking on notification tap when the application is in kill state.

  useEffect(() => {
    const handleCallInvite = (invite) => {
      console.log("invite",invite)
    };
    voice.on('callInvite', handleCallInvite)
  }, []);
  
  
 the above code that i pasted i have called in App.js file and I am able to get the log for incoming invite log when the app is in foreground and background mode but I when I am tapping on notification banner when the app is in kill mode it is redirected to the app but above logs are not getting logged. So can you  suggest  me that how can resolve this. Am I  missing any configuration in manifest file or any other file in android folder or is there any other way to do it .

**Comment by mhuynh5757** [comment]
Hello @ankitCompunnel, I'm not asking for your entire codebase. I'm simply asking that you fill out the entire Issue Template so I can get more context on your issue and help you debug: https://github.com/twilio/twilio-voice-react-native/blob/main/.github/ISSUE_TEMPLATE.md

I'm also asking you to _format_ your code so it's reasonable for me to read and debug it.
