### ISSUE TITLE
How to record call or create voicemail?

### ISSUE THREAD

**Issue by oleksiiSevrukovRedvike** [twilio/twilio-voice-react-native#395]
# Issue

## Pre-submission Checklist
- [x] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
I need to record calls and send voicemails, but I haven't found any tool for such features in react native. Can someone help please?

**Comment by mhuynh5757** [comment]
Hello @oleksiiSevrukovRedvike please reach out to Twilio support for help regarding voicemail features: https://help.twilio.com/

You can also ask Twilio support about call recording, or refer to these docs: https://www.twilio.com/docs/voice/twiml/record#twilio-docs-content-area
