### ISSUE TITLE
How to achieve conference call in react native twilio sdk

### ISSUE THREAD

**Issue by ankitCompunnel** [twilio/twilio-voice-react-native#397]
Hii team,

I want to know that how can  I achieve the conference call in this sdk. As I can see that there is no any such code or functionality in reference app for conference call .

Can you describe the proccess or provide any reference or documentation achieve conference call.

**Comment by mhuynh5757** [comment]
Hi @ankitCompunnel please do not remove the Issue Template when creating a Github Issue on this repository. The team has decided to be more strict about these.

**Comment by mhuynh5757** [comment]
For questions about conference and call recording, please reach out to the official Twilio support line: https://help.twilio.com/
