### ISSUE TITLE
The Android build is failing due to a mismatch between the minSdkVersion specified in the React Native version (0.74.3) and the project's configuration.

### ISSUE THREAD

**Issue by Jaydeep9963** [twilio/twilio-voice-react-native#409]
Issue

## Pre-submission Checklist
- [✅ ] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [✅ ] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [ ✅ ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii) or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description
The build fails with an error indicating that the `minSdkVersion` in the project (21) is lower than the version required by `react-android` (23).

## Reproduction Steps
1. Build the project using Gradle.
2. Observe the build failure.

## Expected Behavior
The build should succeed without compatibility errors.

## Actual Behavior
Build fails with the following error: `uses-sdk:minSdkVersion 21 cannot be smaller than version 23 declared in library [com.facebook.react:react-android:0.74.3]`.

## Reproduction Frequency
Consistently reproducible whenever attempting to build the project.

## Screenshots
![Screenshot 2024-08-27 at 6 32 14 p m](https://github.com/user-attachments/assets/bfb3a85b-d553-4e47-9bbd-f636a28dcf0b)

## Software and Device Information
- Device: Google Pixel 6 
- OS: MacOS
- React version: 18.2.0
- React Native version: 0.74.3
- Node version: 20
- Yarn version: 4.3.1

**Comment by mhuynh5757** [comment]
Hey @Jaydeep9963 thanks for bringing this to our attention. Do you mind modifying the `minSdkVersion` of the SDK in your `node_modules/` folder, just to test that adjusting the `minSdkVersion` to `23` will fix your specific use case?

**Comment by mhuynh5757** [comment]
I also see that the error that you're receiving suggests a workaround, could you try that for now as we work on a long-term solution? Thanks for your cooperation.

**Comment by Jaydeep9963** [comment]
> I also see that the error that you're receiving suggests a workaround, could you try that for now as we work on a long-term solution? Thanks for your cooperation.

Hello @mhuynh5757 
I attempted to modify the `minSdkVersion` to 23 in the `node_modules/@twilio/voice-react-native-sdk/android/build.gradle` file, but the issue still persists.
![Screenshot 2024-08-28 at 11 05 36 a m](https://github.com/user-attachments/assets/2b7adfb3-7755-488c-8f66-e38e90710641)

**Comment by mhuynh5757** [comment]
Hey @Jaydeep9963 we just released `1.1.1` of the SDK which should fix this issue. Please upgrade at your earliest convenience. I'm going to close this issue for now, but please feel free to reopen or submit a new issue if you still have this problem.
