### ISSUE TITLE
TVOAudioDeviceMustBeSetBeforeMediaStackSetup error on incoming calls (iOS)

### ISSUE THREAD

**Issue by culov** [twilio/twilio-voice-react-native#413]
**Description**:

I’m encountering a persistent error with the Twilio Voice React Native SDK where the stack trace reports TVOAudioDeviceMustBeSetBeforeMediaStackSetup in TVOMediaFactory.mm:191. This issue occurs every time I receive an incoming call, regardless of whether the app is in the foreground, background, or killed state. The error does not crash the app, but it significantly clutters my error logs.

**Steps to Reproduce:**

Initialize the Twilio Voice SDK in a React Native app.
Receive an incoming call in any state (foreground, background, or killed).
Observe the error log for the TVOAudioDeviceMustBeSetBeforeMediaStackSetup error.
Expected Behavior: The call should be received without triggering the TVOAudioDeviceMustBeSetBeforeMediaStackSetup error.

Actual Behavior: The error TVOAudioDeviceMustBeSetBeforeMediaStackSetup appears in the logs every time an incoming call is received.

**Stack Trace:**
```

TVOAudioDeviceMustBeSetBeforeMediaStackSetup · WebRTC does not allow updating the audio device once the media stack is created (i.e once a track is created or memory allocated for previously created call or connect option is not deleted). You should provide the audio device to SDK prior to creating the tracks.
3
TwilioVoice
TVOMediaFactory.mm:191:13
+[TVOMediaFactory setAudioDevice:]
4
TwilioVoice
TwilioVoice.mm:507:21
+[TwilioVoiceSDK setAudioDevice:]
5
MyApp
-[TwilioVoiceReactNative init]
6
MyApp
__44-[RCTModuleData initWithModuleClass:bridge:]_block_invoke
7
MyApp
-[RCTModuleData setUpInstanceAndBridge:]
8
MyApp
__25-[RCTModuleData instance]_block_invoke
9
MyApp
RCTUnsafeExecuteOnMainQueueSync
10
MyApp

```

**Workarounds Tried:**

I tried setting the audio device immediately after initializing the Voice object as suggested in previous issues:
```
this.voice.getAudioDevices()
  .then(({ audioDevices }) => {
    const audioDevice = audioDevices[0];
    return audioDevice.select();
  });

```
However, the error persists, and I haven’t found a solution.

**Similar Issues:**

https://github.com/twilio/twilio-voice-react-native/issues/362
https://github.com/twilio/twilio-voice-react-native/issues/187
Both issues reported the same error, but neither has a completed ticket template or a resolution.

**Environment:**

Twilio Voice React Native SDK version: 1.1.0
React Native version: 0.64.0
iOS version: 17.5.1
Device: iPhone 14 Pro

**Comment by bobiechen-twilio** [comment]
Thanks for reaching out and sorry that I haven't been able to reply sooner.

The exception is a mechanism inside the iOS SDK to ensure the audio stack (which is different from the audio-device method of the React Native API) is working properly with the media dependency. We are aware of this and will be updating the native SDK to improve the experience.

**Comment by liemdo** [comment]
@bobiechen-twilio Is there any update on resolving this issue? It causes the app to crash.

**Comment by Rolstenhouse** [comment]
@bobiechen-twilio can we re-open this PR? running into the same issue
