### ISSUE TITLE
CallInvite event not being triggered on Android

### ISSUE THREAD

**Issue by LukakHR** [twilio/twilio-voice-react-native#427]
# Issue
Around a month ago, incoming calls stopped working on Android devices for my app

## Pre-submission Checklist
- [x] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [x] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [x] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
I have a Twilio VoIP app on iOS and Android that used to work properly. About 15-25 days ago we started getting reports that incoming calls aren't working on Android. We did some testing and they weren't working for us either (there have been no updates in this time). 

In the Twilio console, the calls are properly logged but they have no errors. They just show as 'No answer' calls. For the caller, the call is ringing so some sort of connection is being established but it's not showing for some reason.

We tested on multiple devices with multiple Android versions in foreground, background and kill state and nothing works. iOS works properly

## Reproduction Steps
1. Follow the installation instructions to install the dependency
2. Register the device for incoming calls
3. Call the device
4. There won't be an incoming call notification

## Reproduction Frequency
It is deterministic

## Software and Device Information
**Please complete the following information.**
 - OS: Android
 - React version: 18.2.0
 - React Native version: 0.72.10
 - Node version: 21.6.2
 - npm or yarn version: 1.22.19

**Comment by siddiquesheikh30** [comment]
Hey, I am also having the same problem did you find any solution to this problem?

**Comment by mhuynh5757** [comment]
Hello all, thanks for reaching out. Do you happen to be using the Legacy Firebase Push Notification credentials/system? Google recently deprecated those APIs and credentials, and you'll need to update to their new v1 Push Notification system.

**Comment by mhuynh5757** [comment]
You can check out the Voice Android Quickstart for info related to this: https://github.com/twilio/voice-quickstart-android#quickstart

**Comment by nustony** [comment]
Hi @mhuynh5757,
I have the same problem.
I also updated the new FCM. However, I only get a notification like the attached image without triggering the callInvite function.
<img width="1437" alt="Screenshot 2024-09-24 at 10 38 47" src="https://github.com/user-attachments/assets/e9dee24d-69f0-4c76-9cc7-024e11b3b055">

**Comment by nustony** [comment]
Hi @mhuynh5757
I have the same problem.
I also updated the new FCM. However, I only get a notification like the attached image without triggering the callInvite function.
<img width="1437" alt="Screenshot 2024-09-24 at 10 38 47" src="https://github.com/user-attachments/assets/1fec6d55-5909-45e3-a26d-e9d7c9df044a">

**Comment by LukakHR** [comment]
I did update to the new Push notifications system. Before that, I was getting an error in Twilio console that clearly described what was happening. After fixing that error, it is back to "No answer" as described

**Comment by mhuynh5757** [comment]
Hi @nustony it seems like you're using RNFirebase package. We are aware of some issues when using that package with our SDK, there's another issue that's tracking this. The issue is unfortunately quite complicated and we're working on a solution. Please see this issue: #370

**Comment by mhuynh5757** [comment]
@LukakHR could you try our test app that's embedded in this repo? I'm wondering if it could be your app/configuration.

**Comment by mhuynh5757** [comment]
Hello @nustony we released `1.2.1` that includes a new API for supporting your use case, please update at your earliest convenience.
