### ISSUE TITLE
When I install this package I am getting error: Attempt to read from field 'come.twiliovoicereactnative.JSEventEmitter com.twiliovoicereactnative.VoiceApplicationProxy.JSEventEmiiter" on a null object reference in the method com.twiliovoicereactnative.JSEventEmittercom.twiliovoicereactnative.VoiceApplicationProxy.get.JSEventEmitter()

### ISSUE THREAD

**Issue by sathishvadivelu** [twilio/twilio-voice-react-native#435]
# Issue

## Pre-submission Checklist
- [ ] I have verified that the issue occurs with the latest release and is not marked as a known issue in the [CHANGELOG.md](https://github.com/twilio/twilio-voice-react-native/blob/main/CHANGELOG.md).
- [ ] I reviewed the [Common Issues](https://github.com/twilio/twilio-voice-react-native/blob/main/COMMON_ISSUES.md) and open GitHub issues and verified that this report represents a potentially new issue.
- [ ] I am not sharing any [Personally Identifiable Information (PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
       or sensitive account information (API keys, credentials, etc.) when reporting this issue.

## Description 
A clear and concise description of what the issue is.

## Actual Behavior
What actually happens.

## Reproduction Frequency
Is the reproducibility of the issue deterministic? If not, what percentage of the time does the issue occur? In how many attempts was the issue observed?

## Software and Device Information
**Please complete the following information.**
 - Device: [e.g. iPhone 12, Pixel 3]
 - OS: [e.g. iOS 16, Android API Level 31]
 - React version: [e.g. 18.1.0]
 - React Native version: [e.g. 0.70.9]
 - Node version: [e.g. 16.18.1]
 - npm or yarn version: [e.g. 8.19.2, 1.22.19]

**Comment by isaacVzz** [comment]
I have se same issue with the 1.2.0 version and it seams that still don't have soultion

**Comment by Harshizonnet** [comment]
Facing this same issue here... Team is not responding

**Comment by mhuynh5757** [comment]
Hi @sathishvadivelu please fill out the issue template in it's entirety when filing bugs. It helps the team tremendously when debugging customer issues. You're most likely seeing this issue due to some missing Android integration steps. Please follow this guide: https://github.com/twilio/twilio-voice-react-native/blob/main/docs/migration-guide-beta.4.md

For reference, you can also check our reference app: https://github.com/twilio/twilio-voice-react-native-app/tree/main/app/android/app/src/main/java/com/twiliovoicereactnativereferenceapp

**Comment by mhuynh5757** [comment]
Hi all, it seems like this is a documentation issue. Here's a link to our current docs: https://github.com/twilio/twilio-voice-react-native/tree/main/docs

We're working on improving them at the moment, please stay tuned! I'm going to close this issue for now, but if you still need further assistance please file a new issue.
