### ISSUE TITLE
Voice.registration(token) throw a code error : "Voice error"

### ISSUE THREAD

**Issue by FrunzaAndrei** [twilio/twilio-voice-react-native#451]
## Description 
 The error appears at voice.registration function.

## Reproduction Steps
<img width="436" alt="Screenshot 2024-11-14 at 11 17 09" src="https://github.com/user-attachments/assets/b4f2ef86-ff3c-484d-8dc5-4ca50ad81a59">

![Screenshot 2024-11-14 at 11 17 50](https://github.com/user-attachments/assets/aa16e7f4-989a-4d94-a6d7-64b463718bcd)

## Expected Behavior
Registration successful

## Actual Behavior
Registration in progress

## Reproduction Frequency
Every time when I call this voice.registration

## Software and Device Information
**Please complete the following information.**
 - only ios devices 
 - on android is another problem, there crash the app, probably it will be another issue topic
 - React version: 18.2.0
 - React Native version: 0.71.0
 - Node version: 20.7.0
 - yarn version: 4.2.2

**Comment by clinicsoftware** [comment]
Any help would be greatly appreciated!

@mhuynh5757
@bobiechen-twilio
@kpchoy
@kbagchiGWC
@twilio-vblocks-ci
@afalls-twilio
@manjeshbhargav
@bld010
@mluotwilio
@kevinlegoff-tdl

**Comment by mhuynh5757** [comment]
@FrunzaAndrei in your code snippet, can you log how many times you invoke `voice.register`? The error is suggesting that you're invoking it repeatedly without waiting for the function to resolve. This is not supported.

**Comment by FrunzaAndrei** [comment]
@mhuynh5757 Thank you. I passed this problem but I faced another.
Now I am registred but nothing's happend after I try to execut this code. Why ?

This is the code:
<img width="629" alt="Screenshot 2024-11-15 at 14 02 21" src="https://github.com/user-attachments/assets/b41cc94f-5dd5-4e7f-b8ec-9f357471fd34">

This are the logs:
![Screenshot 2024-11-15 at 14 02 30](https://github.com/user-attachments/assets/602cd2e3-65c8-4b6c-85f6-85f02268ca5e)

**Comment by mhuynh5757** [comment]
This is on iOS correct? Those logs appear to be from the chrome browser, so I'm just making sure. This library does not work for browsers, just iOS and Android. Are you using a real iOS device or a simulator? Our iOS SDK (and consequently the RN SDK) does not work on simulators due to limitations on CallKit imposed by Apple themselves, and there's unfortunately nothing we can do about it.

As an aside, you actually don't need to register to make outgoing calls, in case you were unfamiliar with Twilio Voice.

Hope that answers your questions.

**Comment by FrunzaAndrei** [comment]
@mhuynh5757 thank you for your response.

Yeah, I was using an ios but it was a simulator. And yeah I am unfamiliar with Twilio Voice. Thank you for your help.

**Comment by mhuynh5757** [comment]
Hi @FrunzaAndrei it seems like the original issue has been resolved. Please reach out again if you have more questions, for now I will close this issue. Good luck with your project!
